### ISSUE TITLE
多机微调batchsize不能为1

### ISSUE THREAD

**Issue by TaChao** [THUDM/ChatGLM3#1004]
### System Info / 系統信息

jieba>=0.42.1
ruamel_yaml>=0.18.5
rouge_chinese>=1.0.3
jupyter>=1.0.0
datasets>=2.16.1
peft==0.7.1
transformers>=4.37.2

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

设置`configs/lora.yaml` `per_device_train_batch_size: 1`

报错：
```
tc-test-glm-worker-0: │    491 │   │   │   )                                                         │                                                                    [0/1801]
tc-test-glm-worker-0: │ ❱  492 │   │   torch.autograd.backward(                                      │
tc-test-glm-worker-0: │    493 │   │   │   self, gradient, retain_graph, create_graph, inputs=inputs │
tc-test-glm-worker-0: │    494 │   │   )                                                             │
tc-test-glm-worker-0: │    495                                                                       │
tc-test-glm-worker-0: │                                                                              │
tc-test-glm-worker-0: │ /opt/conda/lib/python3.10/site-packages/torch/autograd/__init__.py:251 in    │
tc-test-glm-worker-0: │ backward                                                                     │
tc-test-glm-worker-0: │                                                                              │
tc-test-glm-worker-0: │   248 │   # The reason we repeat the same comment below is that              │
tc-test-glm-worker-0: │   249 │   # some Python versions print out the first line of a multi-line fu │
tc-test-glm-worker-0: │   250 │   # calls in the traceback and some print out the last line          │
tc-test-glm-worker-0: │ ❱ 251 │   Variable._execution_engine.run_backward(  # Calls into the C++ eng │
tc-test-glm-worker-0: │   252 │   │   tensors,                                                       │
tc-test-glm-worker-0: │   253 │   │   grad_tensors_,                                                 │
tc-test-glm-worker-0: │   254 │   │   retain_graph,                                                  │
tc-test-glm-worker-0: ╰──────────────────────────────────────────────────────────────────────────────╯
tc-test-glm-worker-0: RuntimeError: NCCL Error 1: unhandled cuda error (run with NCCL_DEBUG=INFO for
tc-test-glm-worker-0: details)
tc-test-glm-worker-0: [2024-03-15 19:33:27,560] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 51910
tc-test-glm-worker-0: [2024-03-15 19:33:27,711] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 51911
tc-test-glm-worker-0: [2024-03-15 19:33:27,860] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 51912
tc-test-glm-worker-0: [2024-03-15 19:33:27,860] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 51913
tc-test-glm-worker-1: [2024-03-15 19:33:27,878] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 39185
tc-test-glm-worker-0: [2024-03-15 19:33:28,008] [ERROR] [launch.py:321:sigkill_handler] ['/opt/conda/bin/python', '-u', 'finetune_hf.py', '--local_rank=3', '/root/dataset/advert$
segen/AdvertiseGen_fix/', '/root/data/model', '/root/data/code/ChatGLM3/finetune_demo/configs/lora.yaml', '--deepspeed', '/root/data/code/ChatGLM3/finetune_demo/configs/ds_zero_$
.json'] exits with return code = 1
tc-test-glm-worker-1: [2024-03-15 19:33:28,073] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 39186
tc-test-glm-worker-1: [2024-03-15 19:33:28,073] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 39187
tc-test-glm-worker-1: [2024-03-15 19:33:28,265] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 39188
tc-test-glm-worker-1: [2024-03-15 19:33:28,266] [ERROR] [launch.py:321:sigkill_handler] ['/opt/conda/bin/python', '-u', 'finetune_hf.py', '--local_rank=3', '/root/dataset/advert$
segen/AdvertiseGen_fix/', '/root/data/model', '/root/data/code/ChatGLM3/finetune_demo/configs/lora.yaml', '--deepspeed', '/root/data/code/ChatGLM3/finetune_demo/configs/ds_zero_$
.json'] exits with return code = 1
```

### Expected behavior / 期待表现

可以在batch_size=1情况下训练

**Comment by TaChao** [comment]
详细报错信息
```
[W reducer.cpp:1346] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[W reducer.cpp:1346] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /root/data/code/ChatGLM3/finetune_demo/finetune_hf.py:526 in main                                │
│                                                                                                  │
│   523 │   │   tokenizer=tokenizer,                                                               │
│   524 │   │   compute_metrics=functools.partial(compute_metrics, tokenizer=tokenizer),           │
│   525 │   )                                                                                      │
│ ❱ 526 │   trainer.train()                                                                        │
│   527 │                                                                                          │
│   528 │   # test stage                                                                           │
│   529 │   if test_dataset is not None:                                                           │
│                                                                                                  │
│ /opt/conda/lib/python3.10/site-packages/transformers/trainer.py:1553 in train                    │
│                                                                                                  │
│   1550 │   │   │   finally:                                                                      │
│   1551 │   │   │   │   hf_hub_utils.enable_progress_bars()                                       │
│   1552 │   │   else:                                                                             │
│ ❱ 1553 │   │   │   return inner_training_loop(                                                   │
│   1554 │   │   │   │   args=args,                                                                │
│   1555 │   │   │   │   resume_from_checkpoint=resume_from_checkpoint,                            │
│   1556 │   │   │   │   trial=trial,                                                              │
│                                                                                                  │
│ /opt/conda/lib/python3.10/site-packages/transformers/trainer.py:1835 in _inner_training_loop     │
│                                                                                                  │
│   1832 │   │   │   │   │   self.control = self.callback_handler.on_step_begin(args, self.state,  │
│   1833 │   │   │   │                                                                             │
│   1834 │   │   │   │   with self.accelerator.accumulate(model):                                  │
│ ❱ 1835 │   │   │   │   │   tr_loss_step = self.training_step(model, inputs)                      │
│   1836 │   │   │   │                                                                             │
│   1837 │   │   │   │   if (                                                                      │
│   1838 │   │   │   │   │   args.logging_nan_inf_filter                                           │
│                                                                                                  │
│ /opt/conda/lib/python3.10/site-packages/transformers/trainer.py:2690 in training_step            │
│                                                                                                  │
│   2687 │   │   │   with amp.scale_loss(loss, self.optimizer) as scaled_loss:                     │
│   2688 │   │   │   │   scaled_loss.backward()                                                    │
│   2689 │   │   else:                                                                             │
│ ❱ 2690 │   │   │   self.accelerator.backward(loss)                                               │
│   2691 │   │                                                                                     │
│   2692 │   │   return loss.detach() / self.args.gradient_accumulation_steps                      │
│   2693                                                                                           │
│                                                                                                  │
│ /opt/conda/lib/python3.10/site-packages/accelerate/accelerator.py:1964 in backward               │
│                                                                                                  │
│   1961 │   │   elif self.scaler is not None:                                                     │
│   1962 │   │   │   self.scaler.scale(loss).backward(**kwargs)                                    │
│   1963 │   │   else:                                                                             │
│ ❱ 1964 │   │   │   loss.backward(**kwargs)                                                       │
│   1965 │                                                                                         │
│   1966 │   def set_trigger(self):                                                                │
│   1967 │   │   """                                                                               │
│                                                                                                  │
│ /opt/conda/lib/python3.10/site-packages/torch/_tensor.py:492 in backward                         │
│                                                                                                  │
│    489 │   │   │   │   create_graph=create_graph,                                                │
│    490 │   │   │   │   inputs=inputs,                                                            │
│    491 │   │   │   )                                                                             │
│ ❱  492 │   │   torch.autograd.backward(                                                          │
│    493 │   │   │   self, gradient, retain_graph, create_graph, inputs=inputs                     │
│    494 │   │   )                                                                                 │
│    495                                                                                           │
│                                                                                                  │
│ /opt/conda/lib/python3.10/site-packages/torch/autograd/__init__.py:251 in backward               │
│                                                                                                  │
│   248 │   # The reason we repeat the same comment below is that                                  │
│   249 │   # some Python versions print out the first line of a multi-line function               │
│   250 │   # calls in the traceback and some print out the last line                              │
│ ❱ 251 │   Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the bac   │
│   252 │   │   tensors,                                                                           │
│   253 │   │   grad_tensors_,                                                                     │
│   254 │   │   retain_graph,                                                                      │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: NCCL Error 1: unhandled cuda error (run with NCCL_DEBUG=INFO for details)
  0%|                                                                                                                                                    | 0/6000 [00:03<?, ?it/s]
[2024-03-20 20:12:30,394] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 48076 closing signal SIGTERM
[2024-03-20 20:12:30,508] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 48075) of binary: /opt/conda/bin/python
Traceback (most recent call last):
  File "/opt/conda/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.1.2', 'console_scripts', 'torchrun')())
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
finetune_hf.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-03-20_20:12:30
```

configs/lora.yaml
```
data_config:
  train_file: train.json
  val_file: dev.json
  test_file: dev.json
  num_proc: 16
max_input_length: 4096
max_output_length: 4096
training_args:
  # see `transformers.Seq2SeqTrainingArguments`
  output_dir: /root/data/code/ChatGLM3/finetune_demo/output
  max_steps: 6000
  # settings for data loading
  per_device_train_batch_size: 1
  dataloader_num_workers: 16
  remove_unused_columns: false
  # settings for saving checkpoints
  save_strategy: steps
  save_steps: 6000
  # settings for logging
  log_level: info
  logging_strategy: steps
  logging_steps: 10
  # settings for evaluation
  per_device_eval_batch_size: 16
  evaluation_strategy: steps
  eval_steps: 6000
  # settings for optimizer
  # adam_epsilon: 1e-6
  # uncomment the following line to detect nan or inf values
  # debug: underflow_overflow
  predict_with_generate: true
  # see `transformers.GenerationConfig`
  generation_config:
    max_new_tokens: 4096
  # set your absolute deepspeed path here
  #deepspeed: ds_zero_2.json
  # set to true if train with cpu.
  use_cpu: false
peft_config:
  peft_type: LORA
  task_type: CAUSAL_LM
  r: 8
  lora_alpha: 32
  lora_dropout: 0.1
```

configs/ds_zero_2.json
```
{
  "fp16": {
    "enabled": "auto",
    "loss_scale": 0,
    "loss_scale_window": 1000,
    "initial_scale_power": 16,
    "hysteresis": 2,
    "min_loss_scale": 1
  },
  "bf16": {
    "enabled": "auto"
  },
  "zero_optimization": {
    "stage": 2,
    "allgather_partitions": true,
    "allgather_bucket_size": 500000000,
    "overlap_comm": true,
    "reduce_scatter": true,
    "reduce_bucket_size": 500000000,
    "contiguous_gradients": true
  },
  "gradient_accumulation_steps": 1,
  "gradient_clipping": "auto",
  "steps_per_print": 2000,
  "train_batch_size": "auto",
  "train_micro_batch_size_per_gpu": "auto",
  "wall_clock_breakdown": false
}
```

**Comment by KerryElwood** [comment]
我也出了同样的报错。

我的问题是，曾经单卡微调，在finetune.py中固定了只使用某张卡os.environ['CUDA_VISIBLE_DEVICES']='0'
所以多卡微调会出这个错。

希望能有所帮助参考

**Comment by zRzRzRzRzRzRzR** [comment]
多卡微调上ds吧，然后我刚才试了一下可以为1
