### ISSUE TITLE
本地有下载好模型，却报这样的错：Could not locate the tokenization_chatglm.py

### ISSUE THREAD

**Issue by zhangyue2709** [THUDM/ChatGLM3#1031]
### System Info / 系統信息

python 版本
![image](https://github.com/THUDM/ChatGLM3/assets/137603553/e06550d7-aadc-405a-a602-4084c30038de)
pytorch信息如下
![image](https://github.com/THUDM/ChatGLM3/assets/137603553/6097365f-2547-4c08-8cc8-a41d23e3cb1b)
显卡信息
![image](https://github.com/THUDM/ChatGLM3/assets/137603553/2cbd584e-4b45-4c07-b1e9-a46e24b35197)
![image](https://github.com/THUDM/ChatGLM3/assets/137603553/584c1e1b-e969-468d-abe7-6c2805886084)
系统信息

centos 9

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

git clone https://github.com/THUDM/ChatGLM3
cd ChatGLM3 
pip install -r requirements.txt

python 

from transformers import AutoTokenizer, AutoModel

模型路径：
(chatglm3-10) [root@localhost ChatGLM3-6B]# pwd
/home/shen-jun/Linly-Talker-main/models/ChatGLM3-6B

tokenizer = AutoTokenizer.from_pretrained("/home/shen-jun/Linly-Talker-main/models/ChatGLM3-6B", trust_remote_code=True)

报错信息：
Could not locate the tokenization_chatglm.py inside THUDM/chatglm3-6b.
Traceback (most recent call last):
  File "/root/anaconda3/envs/chatglm3-10/lib/python3.10/site-packages/urllib3/connection.py", line 198, in _new_conn
    sock = connection.create_connection(
  File "/root/anaconda3/envs/chatglm3-10/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/root/anaconda3/envs/chatglm3-10/lib/python3.10/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/anaconda3/envs/chatglm3-10/lib/python3.10/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "/root/anaconda3/envs/chatglm3-10/lib/python3.10/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
  File "/root/anaconda3/envs/chatglm3-10/lib/python3.10/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/root/anaconda3/envs/chatglm3-10/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "/root/anaconda3/envs/chatglm3-10/lib/python3.10/site-packages/urllib3/connection.py", line 616, in connect
    self.sock = sock = self._new_conn()
  File "/root/anaconda3/envs/chatglm3-10/lib/python3.10/site-packages/urllib3/connection.py", line 213, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7efb297f0ee0>: Failed to establish a new connection: [Errno 101] Network is unreachable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/anaconda3/envs/chatglm3-10/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/root/anaconda3/envs/chatglm3-10/lib/python3.10/site-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "/root/anaconda3/envs/chatglm3-10/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /THUDM/chatglm3-6b/resolve/main/tokenization_chatglm.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7efb297f0ee0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/envs/chatglm3-10/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1261, in hf_hub_download
    metadata = get_hf_file_metadata(
  File "/root/anaconda3/envs/chatglm3-10/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/root/anaconda3/envs/chatglm3-10/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1667, in get_hf_file_metadata
    r = _request_wrapper(
  File "/root/anaconda3/envs/chatglm3-10/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 385, in _request_wrapper
    response = _request_wrapper(
  File "/root/anaconda3/envs/chatglm3-10/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 408, in _request_wrapper
    response = get_session().request(method=method, url=url, **params)
  File "/root/anaconda3/envs/chatglm3-10/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/anaconda3/envs/chatglm3-10/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/root/anaconda3/envs/chatglm3-10/lib/python3.10/site-packages/huggingface_hub/utils/_http.py", line 67, in send
    return super().send(request, *args, **kwargs)
  File "/root/anaconda3/envs/chatglm3-10/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /THUDM/chatglm3-6b/resolve/main/tokenization_chatglm.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7efb297f0ee0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"), '(Request ID: 6207d2c9-7ac7-409b-9c9e-3065706eeda9)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/anaconda3/envs/chatglm3-10/lib/python3.10/site-packages/transformers/utils/hub.py", line 398, in cached_file
    resolved_file = hf_hub_download(
  File "/root/anaconda3/envs/chatglm3-10/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/root/anaconda3/envs/chatglm3-10/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1406, in hf_hub_download
    raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/anaconda3/envs/chatglm3-10/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 818, in from_pretrained
    tokenizer_class = get_class_from_dynamic_module(class_ref, pretrained_model_name_or_path, **kwargs)
  File "/root/anaconda3/envs/chatglm3-10/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 489, in get_class_from_dynamic_module
    final_module = get_cached_module_file(
  File "/root/anaconda3/envs/chatglm3-10/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 294, in get_cached_module_file
    resolved_module_file = cached_file(
  File "/root/anaconda3/envs/chatglm3-10/lib/python3.10/site-packages/transformers/utils/hub.py", line 441, in cached_file
    raise EnvironmentError(
OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like THUDM/chatglm3-6b is not the path to a directory containing a file named tokenization_chatglm.py.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

### Expected behavior / 期待表现

能向demo里面一样正常加载模型，然后可以正常对话。

**Comment by yutianli2023** [comment]
这个你要把里面模型的路径换为本地模型的路径，就是这段出现了问题“THUDM/chatglm3-6b”。

**Comment by ROY-SNN** [comment]
我也遇到同样的问题，但是我没理解上面的意思？我加载本地模型的代码：

`MODEL_PATH = "/home/lsdx/lys-project/llm/Langchain-Chatchat-master/THUDM/chatglm3-6b/"
tokenizer = AutoTokenizer.from_pretrained(MODEL_PATH, trust_remote_code=True)`

**Comment by Leawnn** [comment]
请问解决了吗，我也遇到这个问题

**Comment by zhangyue2709** [comment]
重新到官网下载模型就可以了
