### ISSUE TITLE
openai_demo/langchain_openai_api.py 脚本运行出错:Error raised during decoding response from inference endpoint

### ISSUE THREAD

**Issue by MuuuShin** [THUDM/ChatGLM3#1110]
### System Info / 系統信息

Linux
Python 3.9.19
Cuda compilation tools, release 10.1, V10.1.243

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1. 下载requirement.txt包
2. 启动api_server.py作为服务器
3. 启动langchain_openai_api.py,输入 HELLO
4. 报错

服务器表现正常:
INFO:     127.0.0.1:33232 - "POST /v1/chat/completions HTTP/1.1" 200 OK
2024-04-09 23:10:12.684 | DEBUG    | __main__:create_chat_completion:239 - ==== request ====
{'messages': [ChatMessage(role='system', content='You are an intelligent AI assistant, named ChatGLM3.', name=None, function_call=None), ChatMessage(role='user', content='HELLO', name=None, function_call=None)], 'temperature': 0.1, 'top_p': 0.9, 'max_tokens': 8096, 'echo': False, 'stream': True, 'repetition_penalty': 1.1, 'tools': None}

客户端报错:
<details>

```
Traceback (most recent call last):
  File "/data/bch/miniconda3/envs/chatsql/lib/python3.9/site-packages/langchain_community/llms/chatglm3.py", line 129, in _call
    parsed_response = response.json()
  File "/data/bch/miniconda3/envs/chatsql/lib/python3.9/site-packages/httpx/_models.py", line 764, in json
    return jsonlib.loads(self.content, **kwargs)
  File "/data/bch/miniconda3/envs/chatsql/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/data/bch/miniconda3/envs/chatsql/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/data/bch/miniconda3/envs/chatsql/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/bch/LLM/ChatGLM3/openai_api_demo/langchain_openai_api.py", line 56, in <module>
    continuous_conversation()
  File "/data/bch/LLM/ChatGLM3/openai_api_demo/langchain_openai_api.py", line 47, in continuous_conversation
    ai_response = get_ai_response(llm_chain, user_input)
  File "/data/bch/LLM/ChatGLM3/openai_api_demo/langchain_openai_api.py", line 34, in get_ai_response
    ai_response = llm_chain.invoke({"input": user_message})
  File "/data/bch/miniconda3/envs/chatsql/lib/python3.9/site-packages/langchain/chains/base.py", line 163, in invoke
    raise e
  File "/data/bch/miniconda3/envs/chatsql/lib/python3.9/site-packages/langchain/chains/base.py", line 153, in invoke
    self._call(inputs, run_manager=run_manager)
  File "/data/bch/miniconda3/envs/chatsql/lib/python3.9/site-packages/langchain/chains/llm.py", line 103, in _call
    response = self.generate([inputs], run_manager=run_manager)
  File "/data/bch/miniconda3/envs/chatsql/lib/python3.9/site-packages/langchain/chains/llm.py", line 115, in generate
    return self.llm.generate_prompt(
  File "/data/bch/miniconda3/envs/chatsql/lib/python3.9/site-packages/langchain_core/language_models/llms.py", line 569, in generate_prompt
    return self.generate(prompt_strings, stop=stop, callbacks=callbacks, **kwargs)
  File "/data/bch/miniconda3/envs/chatsql/lib/python3.9/site-packages/langchain_core/language_models/llms.py", line 748, in generate
    output = self._generate_helper(
  File "/data/bch/miniconda3/envs/chatsql/lib/python3.9/site-packages/langchain_core/language_models/llms.py", line 606, in _generate_helper
    raise e
  File "/data/bch/miniconda3/envs/chatsql/lib/python3.9/site-packages/langchain_core/language_models/llms.py", line 593, in _generate_helper
    self._generate(
  File "/data/bch/miniconda3/envs/chatsql/lib/python3.9/site-packages/langchain_core/language_models/llms.py", line 1209, in _generate
    self._call(prompt, stop=stop, run_manager=run_manager, **kwargs)
  File "/data/bch/miniconda3/envs/chatsql/lib/python3.9/site-packages/langchain_community/llms/chatglm3.py", line 143, in _call
    raise ValueError(
ValueError: Error raised during decoding response from inference endpoint: Expecting value: line 1 column 1 (char 0).
Response: data: {"model":"chatglm3-6b","id":"","object":"chat.completion.chunk","choices":[{"delta":{"role":"assistant","content":"\n Hello!","function_call":null},"finish_reason":null,"index":0}],"created":1712675313}

data: {"model":"chatglm3-6b","id":"","object":"chat.completion.chunk","choices":[{"delta":{"role":"assistant","content":" How","function_call":null},"finish_reason":null,"index":0}],"created":1712675313}

data: {"model":"chatglm3-6b","id":"","object":"chat.completion.chunk","choices":[{"delta":{"role":"assistant","content":" can","function_call":null},"finish_reason":null,"index":0}],"created":1712675313}

data: {"model":"chatglm3-6b","id":"","object":"chat.completion.chunk","choices":[{"delta":{"role":"assistant","content":" I","function_call":null},"finish_reason":null,"index":0}],"created":1712675313}

data: {"model":"chatglm3-6b","id":"","object":"chat.completion.chunk","choices":[{"delta":{"role":"assistant","content":" assist","function_call":null},"finish_reason":null,"index":0}],"created":1712675313}

data: {"model":"chatglm3-6b","id":"","object":"chat.completion.chunk","choices":[{"delta":{"role":"assistant","content":" you","function_call":null},"finish_reason":null,"index":0}],"created":1712675313}

data: {"model":"chatglm3-6b","id":"","object":"chat.completion.chunk","choices":[{"delta":{"role":"assistant","content":" today","function_call":null},"finish_reason":null,"index":0}],"created":1712675313}

data: {"model":"chatglm3-6b","id":"","object":"chat.completion.chunk","choices":[{"delta":{"role":"assistant","content":"?","function_call":null},"finish_reason":null,"index":0}],"created":1712675313}

data: {"model":"chatglm3-6b","id":"","object":"chat.completion.chunk","choices":[{"delta":{"role":"assistant","content":"","function_call":null},"finish_reason":"stop","index":0}],"created":1712675313}

data: [DONE]
```
</details>

感觉是两边格式没对上,streaming也没改成false,不懂

### Expected behavior / 期待表现

客户端正常输出回答

**Comment by MuuuShin** [comment]
绝活 streaming这个参数应该被设置为False
原来streaming是指打字机模式

**Comment by MuuuShin** [comment]
原有的langchain_openai_api.py不支持打字机模式,不是很懂怎么调

**Comment by zRzRzRzRzRzRzR** [comment]
streaming 改成 False就没有了啊

**Comment by MuuuShin** [comment]
> streaming 改成 False就没有了啊
你指的没有是指没有了什么呢?

看起来 langchain_openai_api.py 在默认情况设置了streaming=true (打字机模式?) 但是又没有做相应的配套解析导致报错

**Comment by zRzRzRzRzRzRzR** [comment]
默认是打字机，False关闭打字机

在demo中仅仅返回了内容，没有在做任何处理，也就是
```
data: {"model":"chatglm3-6b","id":"","object":"chat.completion.chunk","choices":[{"delta":{"role":"assistant","content":" How","function_call":null},"finish_reason":null,"index":0}],"created":1712675313}

data: {"model":"chatglm3-6b","id":"","object":"chat.completion.chunk","choices":[{"delta":{"role":"assistant","content":" can","function_call":null},"finish_reason":null,"index":0}],"created":1712675313}

data: {"model":"chatglm3-6b","id":"","object":"chat.completion.chunk","choices":[{"delta":{"role":"assistant","content":" I","function_call":null},"finish_reason":null,"index":0}],"created":1712675313}

data: {"model":"chatglm3-6b","id":"","object":"chat.completion.chunk","choices":[{"delta":{"role":"assistant","content":" assist","function_call":null},"finish_reason":null,"index":0}],"created":1712675313}

data: {"model":"chatglm3-6b","id":"","object":"chat.completion.chunk","choices":[{"delta":{"role":"assistant","content":" you","function_call":null},"finish_reason":null,"index":0}],"created":1712675313}

data: {"model":"chatglm3-6b","id":"","object":"chat.completion.chunk","choices":[{"delta":{"role":"assistant","content":" today","function_call":null},"finish_reason":null,"index":0}],"created":1712675313}

data: {"model":"chatglm3-6b","id":"","object":"chat.completion.chunk","choices":[{"delta":{"role":"assistant","content":"?","function_call":null},"finish_reason":null,"index":0}],"created":1712675313}

data: {"model":"chatglm3-6b","id":"","object":"chat.completion.chunk","choices":[{"delta":{"role":"assistant","content":"","function_call":null},"finish_reason":"stop","index":0}],"created":1712675313}

data: [DONE]
```
是正常的代码现象

**Comment by MuuuShin** [comment]
请看报错这部分
```
 File "/data/bch/miniconda3/envs/chatsql/lib/python3.9/site-packages/langchain_core/language_models/llms.py", line 593, in _generate_helper
    self._generate(
  File "/data/bch/miniconda3/envs/chatsql/lib/python3.9/site-packages/langchain_core/language_models/llms.py", line 1209, in _generate
    self._call(prompt, stop=stop, run_manager=run_manager, **kwargs)
  File "/data/bch/miniconda3/envs/chatsql/lib/python3.9/site-packages/langchain_community/llms/chatglm3.py", line 143, in _call
    raise ValueError(
ValueError: Error raised during decoding response from inference endpoint: Expecting value: line 1 column 1 (char 0).
Response: data: {"model":"chatglm3-6b","id":"","object":"chat.completion.chunk","choices":[{"delta":{"role":"assistant","content":"\n Hello!","function_call":null},"finish_reason":null,"index":0}],"created":1712675313}

data: {"model":"chatglm3-6b","id":"","object":"chat.completion.chunk","choices":[{"delta":{"role":"assistant","content":" How","function_call":null},"finish_reason":null,"index":0}],"created":1712675313}

data: {"model":"chatglm3-6b","id":"","object":"chat.completion.chunk","choices":[{"delta":{"role":"assistant","content":" can","function_call":null},"finish_reason":null,"index":0}],"created":1712675313}

data: {"model":"chatglm3-6b","id":"","object":"chat.completion.chunk","choices":[{"delta":{"role":"assistant","content":" I","function_call":null},"finish_reason":null,"index":0}],"created":1712675313}

data: {"model":"chatglm3-6b","id":"","object":"chat.completion.chunk","choices":[{"delta":{"role":"assistant","content":" assist","function_call":null},"finish_reason":null,"index":0}],"created":1712675313}

data: {"model":"chatglm3-6b","id":"","object":"chat.completion.chunk","choices":[{"delta":{"role":"assistant","content":" you","function_call":null},"finish_reason":null,"index":0}],"created":1712675313}

data: {"model":"chatglm3-6b","id":"","object":"chat.completion.chunk","choices":[{"delta":{"role":"assistant","content":" today","function_call":null},"finish_reason":null,"index":0}],"created":1712675313}

data: {"model":"chatglm3-6b","id":"","object":"chat.completion.chunk","choices":[{"delta":{"role":"assistant","content":"?","function_call":null},"finish_reason":null,"index":0}],"created":1712675313}

data: {"model":"chatglm3-6b","id":"","object":"chat.completion.chunk","choices":[{"delta":{"role":"assistant","content":"","function_call":null},"finish_reason":"stop","index":0}],"created":1712675313}

data: [DONE]
```


可以看到调用了langchain_community/llms/chatglm3.py, line 143 位置的
```python
        except json.JSONDecodeError as e:
            raise ValueError(
                f"Error raised during decoding response from inference endpoint: {e}."
                f"\nResponse: {response.text}"
            )
```

服务端是以打字机模式输出给客户端的,但是客户端无法解析最终只能报错将原始数据全吐了出来

**Comment by zRzRzRzRzRzRzR** [comment]
已复现，会处理

**Comment by MuuuShin** [comment]
好的,感谢!

**Comment by zRzRzRzRzRzRzR** [comment]
发现一个问题，langchain这好像没处理流的问题，这个得给langchain 提出 PR了

**Comment by zRzRzRzRzRzRzR** [comment]
langchain chatchat没有用到ChatGLM3这个组件，是自己弄的

**Comment by MuuuShin** [comment]
了解，感谢
