### ISSUE TITLE
lora微调后没有pytorch_model.bin

### ISSUE THREAD

**Issue by zhengshi119** [THUDM/ChatGLM3#1203]
### System Info / 系統信息

应该不是环境的问题

### Who can help? / 谁可以帮助到您？

lora微调后没有pytorch_model.bin，运行comosite_demo的main.py会出错：
Traceback (most recent call last):
  File "/usr/local/python3.10/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 584, in _run_script
    exec(code, module.__dict__)
  File "/root/workspace_zs/ChatGLM3-main/composite_demo/main.py", line 11, in <module>
    import demo_chat, demo_ci, demo_tool
  File "/root/workspace_zs/ChatGLM3-main/composite_demo/demo_chat.py", line 7, in <module>
    client = get_client()
  File "/usr/local/python3.10/lib/python3.10/site-packages/streamlit/runtime/caching/cache_utils.py", line 168, in wrapper
    return cached_func(*args, **kwargs)
  File "/usr/local/python3.10/lib/python3.10/site-packages/streamlit/runtime/caching/cache_utils.py", line 197, in __call__
    return self._get_or_create_cached_value(args, kwargs)
  File "/usr/local/python3.10/lib/python3.10/site-packages/streamlit/runtime/caching/cache_utils.py", line 224, in _get_or_create_cached_value
    return self._handle_cache_miss(cache, value_key, func_args, func_kwargs)
  File "/usr/local/python3.10/lib/python3.10/site-packages/streamlit/runtime/caching/cache_utils.py", line 280, in _handle_cache_miss
    computed_value = self._info.func(*func_args, **func_kwargs)
  File "/root/workspace_zs/ChatGLM3-main/composite_demo/client.py", line 30, in get_client
    client = HFClient(MODEL_PATH, TOKENIZER_PATH, PT_PATH)
  File "/root/workspace_zs/ChatGLM3-main/composite_demo/client.py", line 147, in __init__
    prefix_state_dict = torch.load(os.path.join(pt_checkpoint, "pytorch_model.bin"))
  File "/usr/local/python3.10/lib/python3.10/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/usr/local/python3.10/lib/python3.10/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/python3.10/lib/python3.10/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/root/workspace/ChatGLM3-main/finetune_demo/output/checkpoint-3000/pytorch_model.bin'

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

我将composite_demo中的client.py中的：
MODEL_PATH = os.environ.get('MODEL_PATH', '/root/workspace/chatglm3-6b')
PT_PATH = os.environ.get('PT_PATH', None)
PRE_SEQ_LEN = int(os.environ.get("PRE_SEQ_LEN", 128))
TOKENIZER_PATH = os.environ.get("TOKENIZER_PATH", MODEL_PATH)
修改成了：
MODEL_PATH = os.environ.get('MODEL_PATH', '/root/workspace/chatglm3-6b')
PT_PATH = os.environ.get('PT_PATH', '/root/workspace_zs/ChatGLM3-main/finetune_demo/output_med_train30_dev16_pu/checkpoint-3000')
PRE_SEQ_LEN = int(os.environ.get("PRE_SEQ_LEN", 128))
TOKENIZER_PATH = os.environ.get("TOKENIZER_PATH", MODEL_PATH)

注：我主要加上了PT_PATH = os.environ.get('PT_PATH', '/root/workspace_zs/ChatGLM3-main/finetune_demo/output_med_train30_dev16_pu/checkpoint-3000')

### Expected behavior / 期待表现

希望可以使用微调后的模型，运行composite_demo。

**Comment by zRzRzRzRzRzRzR** [comment]
lora微调不是这么用的，查看我们的模型加载代码

**Comment by wangdae** [comment]
我用ptuning第一次微调还能生成model，后面再微调就一直生成不了

**Comment by HXX2020** [comment]
> lora微调不是这么用的，查看我们的模型加载代码

但是我在lora训练后 output文件里没有torch文件，只有一个events.out.tfevents.1716881054.autodl-container-a62d4480bf-b5e9b8dd.6607.0
