### ISSUE TITLE
api_server.py只能用post请求调用吗

### ISSUE THREAD

**Issue by Yapeng-Gao** [THUDM/ChatGLM3#1204]
### System Info / 系統信息

服务器上用 openai_api_demo/api_server.py部署,我电脑上正常用post请求时可以的,但是用openai_api_request.py和zhuipu_api_request.py这两个脚本就报错,不知道什么原因
报错信息Traceback (most recent call last):
  File "E:\projects\backend\static\openai_api_request.py", line 100, in <module>
    simple_chat(use_stream=False)
  File "E:\projects\backend\static\openai_api_request.py", line 68, in simple_chat
    response = client.chat.completions.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\projects\backend\.venv\Lib\site-packages\openai\_utils\_utils.py", line 277, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\projects\backend\.venv\Lib\site-packages\openai\resources\chat\completions.py", line 590, in create
    return self._post(
           ^^^^^^^^^^^
  File "E:\projects\backend\.venv\Lib\site-packages\openai\_base_client.py", line 1240, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\projects\backend\.venv\Lib\site-packages\openai\_base_client.py", line 921, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "E:\projects\backend\.venv\Lib\site-packages\openai\_base_client.py", line 1005, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "E:\projects\backend\.venv\Lib\site-packages\openai\_base_client.py", line 1053, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "E:\projects\backend\.venv\Lib\site-packages\openai\_base_client.py", line 1005, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "E:\projects\backend\.venv\Lib\site-packages\openai\_base_client.py", line 1053, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "E:\projects\backend\.venv\Lib\site-packages\openai\_base_client.py", line 1020, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.InternalServerError: Error code: 502

### Information / 问题信息

- [x] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

用openai_api_request.py和zhuipu_api_request.py这两个脚本就报错

### Expected behavior / 期待表现

帮我解决这个问题

**Comment by SongSongK** [comment]
我也遇到了

**Comment by zRzRzRzRzRzRzR** [comment]
是 然后返回是see
