### ISSUE TITLE
openai_api_request.py运行不成功

### ISSUE THREAD

**Issue by SENVENHUHU** [THUDM/ChatGLM3#1258]
### System Info / 系統信息

在api_server.py成功运行同时，尝试运行openai_api_request.py文件，报如下错误：
Traceback (most recent call last):
  File "/home/admin1/桌面/ChatGLM3/openai_api_demo/openai_api_request.py", line 16, in <module>
    client = OpenAI(api_key="EMPTY", base_url=base_url)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin1/.local/lib/python3.11/site-packages/openai/_client.py", line 122, in __init__
    super().__init__(
  File "/home/admin1/.local/lib/python3.11/site-packages/openai/_base_client.py", line 825, in __init__
    self._client = http_client or SyncHttpxClientWrapper(
                                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin1/.local/lib/python3.11/site-packages/openai/_base_client.py", line 723, in __init__
    super().__init__(**kwargs)
  File "/home/admin1/.local/lib/python3.11/site-packages/httpx/_client.py", line 683, in __init__
    proxy_map = self._get_proxy_map(proxies or proxy, allow_env_proxies)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin1/.local/lib/python3.11/site-packages/httpx/_client.py", line 217, in _get_proxy_map
    return {
           ^
  File "/home/admin1/.local/lib/python3.11/site-packages/httpx/_client.py", line 218, in <dictcomp>
    key: None if url is None else Proxy(url=url)
                                  ^^^^^^^^^^^^^^
  File "/home/admin1/.local/lib/python3.11/site-packages/httpx/_config.py", line 336, in __init__
    raise ValueError(f"Unknown scheme for proxy URL {url!r}")
ValueError: Unknown scheme for proxy URL URL('socks://127.0.0.1:2334/')

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

Traceback (most recent call last):
  File "/home/admin1/桌面/ChatGLM3/openai_api_demo/openai_api_request.py", line 16, in <module>
    client = OpenAI(api_key="EMPTY", base_url=base_url)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin1/.local/lib/python3.11/site-packages/openai/_client.py", line 122, in __init__
    super().__init__(
  File "/home/admin1/.local/lib/python3.11/site-packages/openai/_base_client.py", line 825, in __init__
    self._client = http_client or SyncHttpxClientWrapper(
                                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin1/.local/lib/python3.11/site-packages/openai/_base_client.py", line 723, in __init__
    super().__init__(**kwargs)
  File "/home/admin1/.local/lib/python3.11/site-packages/httpx/_client.py", line 683, in __init__
    proxy_map = self._get_proxy_map(proxies or proxy, allow_env_proxies)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin1/.local/lib/python3.11/site-packages/httpx/_client.py", line 217, in _get_proxy_map
    return {
           ^
  File "/home/admin1/.local/lib/python3.11/site-packages/httpx/_client.py", line 218, in <dictcomp>
    key: None if url is None else Proxy(url=url)
                                  ^^^^^^^^^^^^^^
  File "/home/admin1/.local/lib/python3.11/site-packages/httpx/_config.py", line 336, in __init__
    raise ValueError(f"Unknown scheme for proxy URL {url!r}")
ValueError: Unknown scheme for proxy URL URL('socks://127.0.0.1:2334/')

### Expected behavior / 期待表现

希望明白哪里出错使得官方提供的文件运行不成功

**Comment by zRzRzRzRzRzRzR** [comment]
你用了代理吧，这个代理需要关掉
