### ISSUE TITLE
Getting requirements to build wheel did not run successfully.

### ISSUE THREAD

**Issue by therobot1** [THUDM/ChatGLM3#1259]
### System Info / 系統信息

运行以下命令时：pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
出现这个问题：
 × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "C:\Users\11\anaconda3\envs\windows_chatglm3-6b\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\11\anaconda3\envs\windows_chatglm3-6b\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\11\anaconda3\envs\windows_chatglm3-6b\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\11\AppData\Local\Temp\pip-build-env-8pwdabyr\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\11\AppData\Local\Temp\pip-build-env-8pwdabyr\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\11\AppData\Local\Temp\pip-build-env-8pwdabyr\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 11, in <module>
        File "C:\Users\11\AppData\Local\Temp\pip-build-env-8pwdabyr\overlay\Lib\site-packages\torch\__init__.py", line 141, in <module>
          raise err
      OSError: [WinError 126] 找不到指定的模块。 Error loading "C:\Users\11\AppData\Local\Temp\pip-build-env-8pwdabyr\overlay\Lib\site-packages\torch\lib\shm.dll" or one of its dependencies.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple

### Expected behavior / 期待表现

解决这个问题

**Comment by zRzRzRzRzRzRzR** [comment]
哪个依赖无法安装
