### ISSUE TITLE
启动cli_demo.py报错

### ISSUE THREAD

**Issue by dabing9** [THUDM/ChatGLM3#1315]
### System Info / 系統信息

cuda:24.4.0
transformers: 4.40.0
python: 3.10.14
os:Linux autodl-container-02e24e8ca2-47f886e1 5.15.0-94-generic #104-Ubuntu SMP Tue Jan 9 15:25:40 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

启动cli_demo.py 出现以下错误：
(pytorch) root@autodl-container-02e24e8ca2-47f886e1:~/autodl-tmp/THUDM/ChatGLM3# python basic_demo/cli_demo.py 
Setting eos_token is not supported, use the default one.
Setting pad_token is not supported, use the default one.
Setting unk_token is not supported, use the default one.
Loading checkpoint shards:   0%|                                                                                                                                 | 0/7 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/root/autodl-tmp/THUDM/ChatGLM3/basic_demo/cli_demo.py", line 9, in <module>
    model = AutoModel.from_pretrained(MODEL_PATH, trust_remote_code=True, device_map="auto").eval()
  File "/root/autodl-tmp/Anaconda3/envs/pytorch/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 558, in from_pretrained
    return model_class.from_pretrained(
  File "/root/autodl-tmp/Anaconda3/envs/pytorch/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3677, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/root/autodl-tmp/Anaconda3/envs/pytorch/lib/python3.10/site-packages/transformers/modeling_utils.py", line 4084, in _load_pretrained_model
    state_dict = load_state_dict(shard_file, is_quantized=is_quantized)
  File "/root/autodl-tmp/Anaconda3/envs/pytorch/lib/python3.10/site-packages/transformers/modeling_utils.py", line 507, in load_state_dict
    with safe_open(checkpoint_file, framework="pt") as f:
safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer

### Expected behavior / 期待表现

能正常启动

**Comment by Lzhjk1** [comment]
我猜是单纯模型文件损坏了？检查一下 Hash，有跟 HuggingFace 上不一样的文件的话重新下一个。

**Comment by dabing9** [comment]
嗯，应该是文件有损坏，但是检测的Hash是没问题的， 从Modelscope 下载的启动有问题，然后又从SwanHub 下载的文件没问题了
