### ISSUE TITLE
为什么报错了？

### ISSUE THREAD

**Issue by homo11451419** [THUDM/ChatGLM3#164]
代码：
```python
from transformers import AutoModel, AutoTokenizer
import gradio as gr
import mdtex2html
from utils import load_model_on_gpus

tokenizer = AutoTokenizer.from_pretrained("D:\glm3\ChatGLM3\chatglm3-6b-32k", trust_remote_code=True)
model = AutoModel.from_pretrained("D:\glm3\ChatGLM3\chatglm3-6b-32k", trust_remote_code=True).cuda()
# 多显卡支持，使用下面两行代替上面一行，将num_gpus改为你实际的显卡数量
# from utils import load_model_on_gpus
# model = load_model_on_gpus("THUDM/chatglm3-6b", num_gpus=2)
model = model.eval()

"""Override Chatbot.postprocess"""


def postprocess(self, y):
    if y is None:
        return []
    for i, (message, response) in enumerate(y):
        y[i] = (
            None if message is None else mdtex2html.convert((message)),
            None if response is None else mdtex2html.convert(response),
        )
    return y


gr.Chatbot.postprocess = postprocess


def parse_text(text):
    """copy from https://github.com/GaiZhenbiao/ChuanhuChatGPT/"""
    lines = text.split("\n")
    lines = [line for line in lines if line != ""]
    count = 0
    for i, line in enumerate(lines):
        if "```" in line:
            count += 1
            items = line.split('`')
            if count % 2 == 1:
                lines[i] = f'<pre><code class="language-{items[-1]}">'
            else:
                lines[i] = f'<br></code></pre>'
        else:
            if i > 0:
                if count % 2 == 1:
                    line = line.replace("`", "\`")
                    line = line.replace("<", "&lt;")
                    line = line.replace(">", "&gt;")
                    line = line.replace(" ", "&nbsp;")
                    line = line.replace("*", "&ast;")
                    line = line.replace("_", "&lowbar;")
                    line = line.replace("-", "&#45;")
                    line = line.replace(".", "&#46;")
                    line = line.replace("!", "&#33;")
                    line = line.replace("(", "&#40;")
                    line = line.replace(")", "&#41;")
                    line = line.replace("$", "&#36;")
                lines[i] = "<br>"+line
    text = "".join(lines)
    return text


def predict(input, chatbot, max_length, top_p, temperature, history, past_key_values):
    chatbot.append((parse_text(input), ""))
    for response, history, past_key_values in model.stream_chat(tokenizer, input, history, past_key_values=past_key_values,
                                                                return_past_key_values=True,
                                                                max_length=max_length, top_p=top_p,
                                                                temperature=temperature):
        chatbot[-1] = (parse_text(input), parse_text(response))

        yield chatbot, history, past_key_values


def reset_user_input():
    return gr.update(value='')


def reset_state():
    return [], [], None


with gr.Blocks() as demo:
    gr.HTML("""<h1 align="center">ChatGLM3-6B</h1>""")

    chatbot = gr.Chatbot()
    with gr.Row():
        with gr.Column(scale=4):
            with gr.Column(scale=12):
                user_input = gr.Textbox(show_label=False, placeholder="Input...", lines=10).style(
                    container=False)
            with gr.Column(min_width=32, scale=1):
                submitBtn = gr.Button("Submit", variant="primary")
        with gr.Column(scale=1):
            emptyBtn = gr.Button("Clear History")
            max_length = gr.Slider(0, 32768, value=8192, step=1.0, label="Maximum length", interactive=True)
            top_p = gr.Slider(0, 1, value=0.8, step=0.01, label="Top P", interactive=True)
            temperature = gr.Slider(0, 1, value=0.6, step=0.01, label="Temperature", interactive=True)

    history = gr.State([])
    past_key_values = gr.State(None)

    submitBtn.click(predict, [user_input, chatbot, max_length, top_p, temperature, history, past_key_values],
                    [chatbot, history, past_key_values], show_progress=True)
    submitBtn.click(reset_user_input, [], [user_input])

    emptyBtn.click(reset_state, outputs=[chatbot, history, past_key_values], show_progress=True)

demo.queue().launch(share=False, inbrowser=True)


```
报错：
```python
Traceback (most recent call last):
  File "D:\glm3\ChatGLM3\web_demo.py", line 6, in <module>
    tokenizer = AutoTokenizer.from_pretrained("D:\glm3\ChatGLM3\chatglm3-6b-32k", trust_remote_code=True)
  File "D:\Programs Files\Python\Python311\Lib\site-packages\transformers\models\auto\tokenization_auto.py", line 678, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "D:\Programs Files\Python\Python311\Lib\site-packages\transformers\tokenization_utils_base.py", line 1825, in from_pretrained
    return cls._from_pretrained(
  File "D:\Programs Files\Python\Python311\Lib\site-packages\transformers\tokenization_utils_base.py", line 1988, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "C:\Users\用户名/.cache\huggingface\modules\transformers_modules\chatglm3-6b-32k\tokenization_chatglm.py", line 87, in __init__
    self.tokenizer = SPTokenizer(vocab_file)
  File "C:\Users\\用户名/.cache\huggingface\modules\transformers_modules\chatglm3-6b-32k\tokenization_chatglm.py", line 14, in __init__
    assert os.path.isfile(model_path), model_path
  File "<frozen genericpath>", line 30, in isfile
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

**Comment by jeremysong88** [comment]
@homo11451419 Windows 环境请修改成如下的方式：
```python
tokenizer = AutoTokenizer.from_pretrained("D:\\glm3\\ChatGLM3\\chatglm3-6b-32k", trust_remote_code=True)
model = AutoModel.from_pretrained("D:\\glm3\\ChatGLM3\\chatglm3-6b-32k", trust_remote_code=True).cuda()
```
注意路径分隔符。

**Comment by humphreyde** [comment]
我将路径改为："D:\\xxx\\xxx\\chatglm-6b"，还是报错：path should be string, bytes, os.PathLike or integer, not NoneType, 请问博主知道什么原因吗？

**Comment by humphreyde** [comment]
@jeremysong88 我将路径改为："D:\xxx\xxx\chatglm-6b"，还是报错：path should be string, bytes, os.PathLike or integer, not NoneType, 请问博主知道什么原因吗？

**Comment by humphreyde** [comment]
@jeremysong88 @zhangch9 @homo11451419 我按照建议将路径改为："D:\\xxx\\xxx\\chatglm-6b"，还是报错：path should be string, bytes, os.PathLike or integer, not NoneType, 请问博主知道什么原因吗？

**Comment by humphreyde** [comment]
> @jeremysong88 @zhangch9 @homo11451419 我按照建议将路径改为："D:\\xxx\\xxx\\chatglm-6b"，还是报错：path should be string, bytes, os.PathLike or integer, not NoneType, 请问博主知道什么原因吗？

找到原因了

**Comment by syit-yx** [comment]
> > @jeremysong88 @zhangch9 @homo11451419 我按照建议将路径改为："D:\xxx\xxx\chatglm-6b"，还是报错：path should be string, bytes, os.PathLike or integer, not NoneType, 请问博主知道什么原因吗？
> 
> 找到原因了

你好，能请教一下是怎么解决的吗，我也遇到相同的问题了
