### ISSUE TITLE
ChatGLM3-6B在3060 12G双卡环境对话报错"ValueError: not enough values to unpack"

### ISSUE THREAD

**Issue by 0000sir** [THUDM/ChatGLM3#170]
3060 12G双显卡，在修改代码后，运行cli_demo.py对话时提示 "ValueError: not enough values to unpack"
```
tokenizer = AutoTokenizer.from_pretrained("/pretrained/chatglm3-6b", trust_remote_code=True)
# model = AutoModel.from_pretrained("/pretrained/chatglm3-6b", trust_remote_code=True).cuda()
# 多显卡支持，使用下面两行代替上面一行，将num_gpus改为你实际的显卡数量
from utils import load_model_on_gpus
model = load_model_on_gpus("/pretrained/chatglm3-6b", num_gpus=2)
model = model.eval()
```
以下是错误内容：
```
ChatGLM：Traceback (most recent call last):
  File "/src/ChatGLM3/cli_demo.py", line 61, in <module>
    main()
  File "/src/ChatGLM3/cli_demo.py", line 48, in main
    for response, history, past_key_values in model.stream_chat(tokenizer, query, history=history,
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm3-6b/modeling_chatglm.py", line 1077, in stream_chat
    response, new_history = self.process_response(response, history)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm3-6b/modeling_chatglm.py", line 1003, in process_response
    metadata, content = response.split("\n", maxsplit=1)
ValueError: not enough values to unpack (expected 2, got 1)
```
测试在Tesla P100上双卡运行没有问题

3060驱动版本 545.23.06
P100区动版本 530.30.02

报错的第48行是这个循环的开始，应该是model.stream_chat调用失败
```
for response, history, past_key_values in model.stream_chat(tokenizer, query, history=history,
                                                                    past_key_values=past_key_values,
                                                                    return_past_key_values=True):
            if stop_stream:
                stop_stream = False
                break
            else:
                print(response[current_length:], end="", flush=True)
                current_length = len(response)
```

请问这可能是什么原因，如何修复

**Comment by Btlmd** [comment]
这很可能是模型生成了工具调用或代码执行等包含 metadata 的对话内容。目前 tokenizer 中对 `process_response` 的实现可能不能正确处理流式生成的、包含 metadata 的内容。

也许可以考虑运行 [综合 Demo](https://github.com/THUDM/ChatGLM3/blob/main/composite_demo/README.md) ？

**Comment by 0000sir** [comment]
综合demo不退出了，但是仍然没法正常对话，输出是混乱的，我往前翻了issue，有一个相同的问题 #71 

![屏幕快照 2023-11-06 上午9 30 13](https://github.com/THUDM/ChatGLM3/assets/9480755/9b6b3937-2b2a-4d62-a6fb-19f3204c61dd)

之前运行cli_demo.py的时候也出现过一次
![屏幕快照 2023-11-06 上午9 33 44](https://github.com/THUDM/ChatGLM3/assets/9480755/daffa09d-7910-404f-a0d2-23872d7062b9)

**Comment by hiarcs** [comment]
chatglm3-6b-base也有同样的问题，发生同样的位置。调整输入后故障可能消失，而且有时model.chat返回的0号元素会变成一个json对象而不是字符串。

**Comment by Btlmd** [comment]
对于这个出现乱码的情况，想确认一下您用的是 `chatglm3-6b` 还是 `chatglm3-6b-base` 。我在 `chatglm3-6b` 上未能复现这个问题； 而 `chatglm3-6b-base`  是不支持对话的基座模型

**Comment by vcvcvnvcvcvn** [comment]
1003行
在模型的缓存文件中找到modeling_chatglm.py，定位到1003行，
![屏幕截图 2023-11-08 152050](https://github.com/THUDM/ChatGLM3/assets/52404040/4c2834a6-9c9c-49a9-9a0f-f69a70b99e2b)，添加一个判断可以暂时解决这个问题

**Comment by 0000sir** [comment]
> 对于这个出现乱码的情况，想确认一下您用的是 `chatglm3-6b` 还是 `chatglm3-6b-base` 。我在 `chatglm3-6b` 上未能复现这个问题； 而 `chatglm3-6b-base` 是不支持对话的基座模型

确实是chatglm3-6b，还测试了chatglm3-6b-32k，一样的问题，我先试一下上面 @vcvcvnvcvcvn 提到的方法

**Comment by vcvcvnvcvcvn** [comment]
@0000sir 嗯嗯，我的做法只能解决"ValueError: not enough values to unpack"的问题，关于乱码是什么情况就不知道了

**Comment by paul-yangmy** [comment]
> > 对于这个出现乱码的情况，想确认一下您用的是 `chatglm3-6b` 还是 `chatglm3-6b-base` 。我在 `chatglm3-6b` 上未能复现这个问题； 而 `chatglm3-6b-base` 是不支持对话的基座模型
> 
> 确实是chatglm3-6b，还测试了chatglm3-6b-32k，一样的现象，我先试一下上面 @vcvcvnvcvcvn 提到的方法

使用后倒是解决"ValueError: not enough values to unpack"的问题了，但有时候会出现TypeError: unhashable type: 'slice'
![image](https://github.com/THUDM/ChatGLM3/assets/44519600/470f13d4-c4b4-45d5-a8dc-cf0d98df822a)

**Comment by 0000sir** [comment]
> @0000sir 嗯嗯，我的做法只能解决"ValueError: not enough values to unpack"的问题，关于乱码是什么情况就不知道了

确实，乱码问题仍然存在，我试试换个cuda版本看看

**Comment by 0000sir** [comment]
换 nvidia/cuda:12.1.0-runtime-ubuntu22.04 仍然是乱码

**Comment by zRzRzRzRzRzRzR** [comment]
检查一下lora方式对不对？glm3的微调格式与其他不同

**Comment by zRzRzRzRzRzRzR** [comment]
该问题是一个bad case，目前已经移到Discussion，我们将继续收集这一类问题并解决
