### ISSUE TITLE
AttributeError: 'ChatGLM3' object has no attribute 'prompt'

### ISSUE THREAD

**Issue by jhj033** [THUDM/ChatGLM3#197]
When I try to use langchain_demo/main.py，I got an error like this:
(glm) ubuntu@pai-worker1:~/code/ChatGLM3$ CUDA_VISIBLE_DEVICES=1 python langchain_demo/main.py 
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:18<00:00,  2.63s/it]

> Entering new AgentExecutor chain...
======
Traceback (most recent call last):
  File "/share/warehouse/code/ChatGLM3/langchain_demo/main.py", line 35, in <module>
    run_tool(["arxiv"], llm, [
  File "/share/warehouse/code/ChatGLM3/langchain_demo/main.py", line 26, in run_tool
    agent.run(prompt)
  File "/share/warehouse/anaconda3/envs/glm/lib/python3.10/site-packages/langchain/chains/base.py", line 505, in run
    return self(args[0], callbacks=callbacks, tags=tags, metadata=metadata)[
  File "/share/warehouse/anaconda3/envs/glm/lib/python3.10/site-packages/langchain/chains/base.py", line 310, in __call__
    raise e
  File "/share/warehouse/anaconda3/envs/glm/lib/python3.10/site-packages/langchain/chains/base.py", line 304, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/share/warehouse/anaconda3/envs/glm/lib/python3.10/site-packages/langchain/agents/agent.py", line 1146, in _call
    next_step_output = self._take_next_step(
  File "/share/warehouse/anaconda3/envs/glm/lib/python3.10/site-packages/langchain/agents/agent.py", line 933, in _take_next_step
    output = self.agent.plan(
  File "/share/warehouse/anaconda3/envs/glm/lib/python3.10/site-packages/langchain/agents/agent.py", line 546, in plan
    full_output = self.llm_chain.predict(callbacks=callbacks, **full_inputs)
  File "/share/warehouse/anaconda3/envs/glm/lib/python3.10/site-packages/langchain/chains/llm.py", line 298, in predict
    return self(kwargs, callbacks=callbacks)[self.output_key]
  File "/share/warehouse/anaconda3/envs/glm/lib/python3.10/site-packages/langchain/chains/base.py", line 310, in __call__
    raise e
  File "/share/warehouse/anaconda3/envs/glm/lib/python3.10/site-packages/langchain/chains/base.py", line 304, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/share/warehouse/anaconda3/envs/glm/lib/python3.10/site-packages/langchain/chains/llm.py", line 108, in _call
    response = self.generate([inputs], run_manager=run_manager)
  File "/share/warehouse/anaconda3/envs/glm/lib/python3.10/site-packages/langchain/chains/llm.py", line 120, in generate
    return self.llm.generate_prompt(
  File "/share/warehouse/anaconda3/envs/glm/lib/python3.10/site-packages/langchain/llms/base.py", line 507, in generate_prompt
    return self.generate(prompt_strings, stop=stop, callbacks=callbacks, **kwargs)
  File "/share/warehouse/anaconda3/envs/glm/lib/python3.10/site-packages/langchain/llms/base.py", line 656, in generate
    output = self._generate_helper(
  File "/share/warehouse/anaconda3/envs/glm/lib/python3.10/site-packages/langchain/llms/base.py", line 544, in _generate_helper
    raise e
  File "/share/warehouse/anaconda3/envs/glm/lib/python3.10/site-packages/langchain/llms/base.py", line 531, in _generate_helper
    self._generate(
  File "/share/warehouse/anaconda3/envs/glm/lib/python3.10/site-packages/langchain/llms/base.py", line 1055, in _generate
    else self._call(prompt, stop=stop, **kwargs)
  File "/share/warehouse/code/ChatGLM3/langchain_demo/ChatGLM3.py", line 103, in _call
    print(self.prompt)
AttributeError: 'ChatGLM3' object has no attribute 'prompt'
I'm sorry to say that I am a new llm player, please help me, Thanks a lot!

**Comment by jhj033** [comment]
Problem solved in another issue: https://github.com/THUDM/ChatGLM3/issues/133
