### ISSUE TITLE
显示报错NameError: name 'round_up' is not defined

### ISSUE THREAD

**Issue by blmz** [THUDM/ChatGLM3#221]
运行信息如下：
`Traceback (most recent call last):
  File "D:\ChatGLM3_Package\ChatGLM3\techshrimp\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "D:\ChatGLM3_Package\ChatGLM3\main.py", line 11, in <module>
    import demo_chat, demo_ci, demo_tool
  File "D:\ChatGLM3_Package\ChatGLM3\demo_chat.py", line 9, in <module>
    client = get_client()
  File "D:\ChatGLM3_Package\ChatGLM3\techshrimp\lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 212, in wrapper
    return cached_func(*args, **kwargs)
  File "D:\ChatGLM3_Package\ChatGLM3\techshrimp\lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 241, in __call__
    return self._get_or_create_cached_value(args, kwargs)
  File "D:\ChatGLM3_Package\ChatGLM3\techshrimp\lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 267, in _get_or_create_cached_value
    return self._handle_cache_miss(cache, value_key, func_args, func_kwargs)
  File "D:\ChatGLM3_Package\ChatGLM3\techshrimp\lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 321, in _handle_cache_miss
    computed_value = self._info.func(*func_args, **func_kwargs)
  File "D:\ChatGLM3_Package\ChatGLM3\client.py", line 21, in get_client
    client = HFClient(MODEL_PATH)
  File "D:\ChatGLM3_Package\ChatGLM3\client.py", line 102, in __init__
    self.model = self.model.half().quantize(4).cuda()
  File "C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\THUDM_chatglm3-6b\modeling_chatglm.py", line 1205, in quantize
    self.transformer.encoder = quantize(self.transformer.encoder, bits, empty_init=empty_init, device=device,
  File "C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\THUDM_chatglm3-6b\quantization.py", line 155, in quantize
    layer.self_attention.query_key_value = QuantizedLinear(
  File "C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\THUDM_chatglm3-6b\quantization.py", line 139, in __init__
    self.weight = compress_int4_weight(self.weight)
  File "C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\THUDM_chatglm3-6b\quantization.py", line 76, in compress_int4_weight
    blockDim = (min(round_up(m, 32), 1024), 1, 1)
NameError: name 'round_up' is not defined`

**Comment by zRzRzRzRzRzRzR** [comment]
能提供最小复现吗

**Comment by MyPoet** [comment]
我遇到了同样的问题。装一下cpm_kernels库之后就没问题了。
pip install cpm_kernels

**Comment by duolabmeng6** [comment]
> 我遇到了同样的问题。装一下cpm_kernels库之后就没问题了。 pip install cpm_kernels

然后又提示了 
```
RuntimeError: Library cudart is not initialized
```

**Comment by hxcjack** [comment]
我也碰到过同样的问题，尝试过pip install cpm_kernels，也尝试过把try 下面的import注释掉，还是一样报错，后面检查了cpm_kernels.kernels.base文件，是有round_up这个方面的，就单独引入这个方面，from cpm_kernels.kernels.base import round_up，这回没报错了，希望对你有用。
