### ISSUE TITLE
使用综合demo报错addmm_impl_cpu_" not implemented for 'Half'

### ISSUE THREAD

**Issue by wiizz3** [THUDM/ChatGLM3#223]
Traceback (most recent call last):
  File "F:\anaconda\envs\chatglm3-demo\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "D:\GLM3\ChatGLM3-main\composite_demo\main.py", line 54, in <module>
    demo_ci.main(top_p, temperature, prompt_text)
  File "D:\GLM3\ChatGLM3-main\composite_demo\demo_ci.py", line 249, in main
    for response in client.generate_stream(
  File "D:\GLM3\ChatGLM3-main\composite_demo\client.py", line 134, in generate_stream
    for new_text, _ in stream_chat(self.model,
  File "D:\GLM3\ChatGLM3-main\composite_demo\client.py", line 71, in stream_chat
    for outputs in self.stream_generate(**inputs, past_key_values=past_key_values,
  File "F:\anaconda\envs\chatglm3-demo\lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\THUDM\chatglm3-6b\d3fe58f8a2c50bab217780ba8bd3ff76833d2d0c\modeling_chatglm.py", line 1156, in stream_generate
    outputs = self(
  File "F:\anaconda\envs\chatglm3-demo\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "F:\anaconda\envs\chatglm3-demo\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\THUDM\chatglm3-6b\d3fe58f8a2c50bab217780ba8bd3ff76833d2d0c\modeling_chatglm.py", line 937, in forward
    transformer_outputs = self.transformer(
  File "F:\anaconda\envs\chatglm3-demo\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "F:\anaconda\envs\chatglm3-demo\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\THUDM\chatglm3-6b\d3fe58f8a2c50bab217780ba8bd3ff76833d2d0c\modeling_chatglm.py", line 830, in forward
    hidden_states, presents, all_hidden_states, all_self_attentions = self.encoder(
  File "F:\anaconda\envs\chatglm3-demo\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "F:\anaconda\envs\chatglm3-demo\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\THUDM\chatglm3-6b\d3fe58f8a2c50bab217780ba8bd3ff76833d2d0c\modeling_chatglm.py", line 640, in forward
    layer_ret = layer(
  File "F:\anaconda\envs\chatglm3-demo\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "F:\anaconda\envs\chatglm3-demo\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\THUDM\chatglm3-6b\d3fe58f8a2c50bab217780ba8bd3ff76833d2d0c\modeling_chatglm.py", line 544, in forward
    attention_output, kv_cache = self.self_attention(
  File "F:\anaconda\envs\chatglm3-demo\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "F:\anaconda\envs\chatglm3-demo\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\THUDM\chatglm3-6b\d3fe58f8a2c50bab217780ba8bd3ff76833d2d0c\modeling_chatglm.py", line 376, in forward
    mixed_x_layer = self.query_key_value(hidden_states)
  File "F:\anaconda\envs\chatglm3-demo\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "F:\anaconda\envs\chatglm3-demo\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "F:\anaconda\envs\chatglm3-demo\lib\site-packages\torch\nn\modules\linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: "addmm_impl_cpu_" not implemented for 'Half'
按照文档的方法运行完说话就报错这个，但是我文件里面没有使用half这个参数啊
有没有大佬给点解决办法:(

**Comment by sd827999094** [comment]
我也报了这个错误

**Comment by zzk525** [comment]
我也报这个错误兄弟解决了没？

**Comment by garrgal** [comment]
我这样可行，因为代码自动调用了cpu，而不是gpu
修改composite_demo\client.py第117行
self.model = AutoModel.from_pretrained(model_path, trust_remote_code=True)为self.model = AutoModel.from_pretrained(model_path, trust_remote_code=True).cuda()
