### ISSUE TITLE
根据示例在mac m1中进行P-Tuning单轮微调时，返回错误“RuntimeError: Placeholder storage has not been allocated on MPS device!”

### ISSUE THREAD

**Issue by liyifango** [THUDM/ChatGLM3#237]
### System Info / 系統信息

* mac m1 pro 
* macos 14.1

* torch              2.2.0.dev20231108
* torchaudio         2.2.0.dev20231108
* torchvision        0.17.0.dev20231108
* transformers       4.30.2
* Python 3.10.13
* accelerate         0.24.1
* sentencepiece      0.1.99
* astunparse         1.6.3
* deepspeed          0.12.2

### Who can help? / 谁可以帮助到您？

@Btlmd 您好 我在使用finetune_demo中./scripts/finetune_pt.sh脚本尝试微调时，出现运行时错误：
```text
[INFO|trainer.py:1793] 2023-11-09 12:47:29,784 >>   Number of trainable parameters = 1,835,008
  0%|          | 0/1000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/Users/xxx/Documents/workspaces/python/chatglm3/finetune_demo/finetune.py", line 165, in <module>
    main()
  File "/Users/xxx/Documents/workspaces/python/chatglm3/finetune_demo/finetune.py", line 160, in main
    trainer.train(resume_from_checkpoint=checkpoint)
  File "/Users/xxx/micromamba/envs/pytorch-pre/lib/python3.10/site-packages/transformers/trainer.py", line 1645, in train
    return inner_training_loop(
  File "/Users/xxx/micromamba/envs/pytorch-pre/lib/python3.10/site-packages/transformers/trainer.py", line 1938, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/Users/xxx/micromamba/envs/pytorch-pre/lib/python3.10/site-packages/transformers/trainer.py", line 2759, in training_step
    loss = self.compute_loss(model, inputs)
  File "/Users/xxx/micromamba/envs/pytorch-pre/lib/python3.10/site-packages/transformers/trainer.py", line 2784, in compute_loss
    outputs = model(**inputs)
  File "/Users/xxx/micromamba/envs/pytorch-pre/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1510, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/xxx/micromamba/envs/pytorch-pre/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1519, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/xxx/.cache/huggingface/modules/transformers_modules/chatglm3-6b/modeling_chatglm.py", line 937, in forward
    transformer_outputs = self.transformer(
  File "/Users/xxx/micromamba/envs/pytorch-pre/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1510, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/xxx/micromamba/envs/pytorch-pre/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1519, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/xxx/.cache/huggingface/modules/transformers_modules/chatglm3-6b/modeling_chatglm.py", line 807, in forward
    inputs_embeds = self.embedding(input_ids)
  File "/Users/xxx/micromamba/envs/pytorch-pre/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1510, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/xxx/micromamba/envs/pytorch-pre/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1519, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/xxx/.cache/huggingface/modules/transformers_modules/chatglm3-6b/modeling_chatglm.py", line 723, in forward
    words_embeddings = self.word_embeddings(input_ids)
  File "/Users/xxx/micromamba/envs/pytorch-pre/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1510, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/xxx/micromamba/envs/pytorch-pre/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1560, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/Users/xxx/micromamba/envs/pytorch-pre/lib/python3.10/site-packages/torch/nn/modules/sparse.py", line 162, in forward
    return F.embedding(
  File "/Users/xxx/micromamba/envs/pytorch-pre/lib/python3.10/site-packages/torch/nn/functional.py", line 2238, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Placeholder storage has not been allocated on MPS device!
  0%|          | 0/1000 [00:00<?, ?it/s]
[2023-11-09 12:47:30,823] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 4403) of binary: /Users/xxx/micromamba/envs/pytorch-pre/bin/python3.10
Traceback (most recent call last):
  File "/Users/xxx/micromamba/envs/pytorch-pre/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/Users/xxx/micromamba/envs/pytorch-pre/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 351, in wrapper
    return f(*args, **kwargs)
  File "/Users/xxx/micromamba/envs/pytorch-pre/lib/python3.10/site-packages/torch/distributed/run.py", line 812, in main
    run(args)
  File "/Users/xxx/micromamba/envs/pytorch-pre/lib/python3.10/site-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/Users/xxx/micromamba/envs/pytorch-pre/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/Users/xxx/micromamba/envs/pytorch-pre/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
finetune.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-11-09_12:47:30
  host      : 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 4403)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

不知道应该如何解决，麻烦您协助指导下。谢谢

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

根据https://github.com/THUDM/ChatGLM3/tree/main/finetune_demo#%E8%BE%93%E5%85%A5%E8%BE%93%E5%87%BA%E6%A0%BC%E5%BC%8F中的步骤下载了训练数据并进行转换，然后运行./scripts/finetune_pt.sh微调脚本时出现上述错误

### Expected behavior / 期待表现

正常对模型进行微调

**Comment by QvQQ** [comment]
same here

**Comment by QvQQ** [comment]
在fintune的bash脚本中加上--use_mps_device 1即可。
<img width="566" alt="image" src="https://github.com/THUDM/ChatGLM3/assets/35735975/2479b283-a687-4753-8dbc-f5f49638f000">

https://discuss.huggingface.co/t/runtimeerror-placeholder-storage-has-not-been-allocated-on-mps-device/42999

**Comment by liyifango** [comment]
> 在fintune的bash脚本中加上--use_mps_device 1即可。 <img alt="image" width="566" src="https://user-images.githubusercontent.com/35735975/282277754-2479b283-a687-4753-8dbc-f5f49638f000.png">
> 
> https://discuss.huggingface.co/t/runtimeerror-placeholder-storage-has-not-been-allocated-on-mps-device/42999

给力 解决了 多谢多谢 :beers:
