### ISSUE TITLE
微调报错

### ISSUE THREAD

**Issue by makeukus** [THUDM/ChatGLM3#268]
### System Info / 系統信息

Loading checkpoint shards加载完报错，提示
Some weights of ChatGLMForConditionalGeneration were not initialized from the model checkpoint at models/THUDM_chatglm3-6b/ and are newly initialized: ['transformer.embedding.word_embeddings.weight', 'transformer.encoder.final_layernorm.weight', 'transformer.prefix_encoder.embedding.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

`[INFO|modeling_utils.py:3118] 2023-11-12 01:02:57,734 >> loading weights file models/THUDM_chatglm3-6b/pytorch_model.bin.index.json
[INFO|configuration_utils.py:791] 2023-11-12 01:02:57,734 >> Generate config GenerationConfig {
  "eos_token_id": 2,
  "pad_token_id": 0
}

Loading checkpoint shards: 100%|▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒| 7/7 [00:04<00:00,  1.40it/s]
[INFO|modeling_utils.py:3950] 2023-11-12 01:03:02,767 >> All model checkpoint weights were used when initializing ChatGLMForConditionalGeneration.

[WARNING|modeling_utils.py:3952] 2023-11-12 01:03:02,767 >> Some weights of ChatGLMForConditionalGeneration were not initialized from the model checkpoint at models/THUDM_chatglm3-6b/ and are newly initialized: ['transformer.embedding.word_embeddings.weight', 'transformer.encoder.final_layernorm.weight', 'transformer.prefix_encoder.embedding.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
[INFO|modeling_utils.py:3525] 2023-11-12 01:03:02,769 >> Generation config file not found, using a generation config created from the model config.
Traceback (most recent call last):
  File "D:\BaiduNetdiskDownload\ChatGLM3\ChatGLM3\finetune_demo\finetune.py", line 167, in <module>
    main()
  File "D:\BaiduNetdiskDownload\ChatGLM3\ChatGLM3\finetune_demo\finetune.py", line 118, in main
    train_data = [json.loads(line) for line in f]
  File "D:\BaiduNetdiskDownload\ChatGLM3\ChatGLM3\finetune_demo\finetune.py", line 118, in <listcomp>
    train_data = [json.loads(line) for line in f]
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 12: invalid start byte
[2023-11-12 01:03:05,404] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 326752) of binary: C:\Users\Administrator\AppData\Local\Programs\Python\Python310\python.exe
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\Scripts\torchrun.exe\__main__.py", line 7, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\distributed\elastic\multiprocessing\errors\__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\distributed\run.py", line 806, in main
    run(args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\distributed\run.py", line 797, in run
    elastic_launch(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\distributed\launcher\api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\distributed\launcher\api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
finetune.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>`

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

https://github.com/THUDM/ChatGLM3/tree/main/finetune_demo

./scripts/format_advertise_gen.py --path "AdvertiseGen/train.json"  这一步正常
./scripts/finetune_pt.sh 这一步就报错了

### Expected behavior / 期待表现

一键环境包

**Comment by Btlmd** [comment]
从报错看来，可能是输入数据的编码不正确？

另外，微调脚本仅在 Linux 环境下测试过，在 Windows 上不确定能不能 work

**Comment by makeukus** [comment]
> 从报错看来，可能是输入数据的编码不正确？
> 
> 另外，微调脚本仅在 Linux 环境下测试过，在 Windows 上不确定能不能 work

那应该就是这个原因了，我是在Win上跑的

**Comment by ghx2757** [comment]
遇到了同样的问题，win上有什么办法修改一下吗？搓手手

**Comment by ghx2757** [comment]
@makeukus  请问你怎么解决的啊？我尝试了一些方法目前并没有解决掉

**Comment by makeukus** [comment]
> @makeukus 请问你怎么解决的啊？我尝试了一些方法目前并没有解决掉

没解决，准备直接在Linux 试了

**Comment by ghx2757** [comment]
好的，感谢你的回复，我再搞一搞

**Comment by ghx2757** [comment]
各种方法搞半天，是数据集的问题.....，解决了。

**Comment by mouyiyang** [comment]
> 各种方法搞半天，是数据集的问题.....，解决了
请问是什么原因，怎么改呢？我也是windows遇到同样的报错，感谢指点

**Comment by ghx2757** [comment]
https://github.com/THUDM/ChatGLM3/issues/268#issuecomment-1815954938
如果是自建数据集好好看阿奎那是不是哪个样本格式不对。

**Comment by jingyaogong** [comment]
按照finetune_pt.sh直接分配NUM_GPUS=2就可以运行了

```
#! /usr/bin/env bash

set -ex

PRE_SEQ_LEN=128
LR=1e-2
NUM_GPUS=2
MAX_SOURCE_LEN=1024
MAX_TARGET_LEN=256
DEV_BATCH_SIZE=1
GRAD_ACCUMULARION_STEPS=64
MAX_STEP=100
SAVE_INTERVAL=500

DATASTR=`date +%Y%m%d-%H%M%S`
RUN_NAME=advertise_gen_pt

BASE_MODEL_PATH='XXXXXXX'
DATASET_PATH=scripts/formatted_data/self.jsonl
OUTPUT_DIR=output/${RUN_NAME}-${DATASTR}-${PRE_SEQ_LEN}-${LR}

mkdir -p $OUTPUT_DIR

torchrun --standalone --nnodes=1 --nproc_per_node=$NUM_GPUS finetune.py \
    --train_format input-output \
    --train_file $DATASET_PATH \
    --preprocessing_num_workers 1 \
    --model_name_or_path $BASE_MODEL_PATH \
    --output_dir $OUTPUT_DIR \
    --max_source_length $MAX_SOURCE_LEN \
    --max_target_length $MAX_TARGET_LEN \
    --per_device_train_batch_size $DEV_BATCH_SIZE \
    --gradient_accumulation_steps $GRAD_ACCUMULARION_STEPS \
    --max_steps $MAX_STEP \
    --logging_steps 1 \
    --save_steps $SAVE_INTERVAL \
    --learning_rate $LR \
    --quantization_bit 8 \
    --use_mps_device 1 \
    --pre_seq_len $PRE_SEQ_LEN 2>&1 | tee ${OUTPUT_DIR}/train.log
```
