### ISSUE TITLE
调用openai_api.py的接口报错TypeError: not all arguments converted during string formatting

### ISSUE THREAD

**Issue by zhanghaotian123** [THUDM/ChatGLM3#286]
### System Info / 系統信息

{'messages': [ChatMessage(role='system', content="You are ChatGLM3, a large language model trained by Zhipu.AI. Follow the user's instructions carefully. Respond using markdown.", name=None, function_call=None), ChatMessage(role='user', content='你好，给我讲一个故事，大概100字', name=None, function_call=None)], 'temperature': 0.8, 'top_p': 0.8, 'max_tokens': 100, 'echo': False, 'stream': False, 'repetition_penalty': 1.1, 'functions': None}
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\zht\.conda\envs\chatglm\lib\logging\__init__.py", line 1100, in emit
    msg = self.format(record)
  File "C:\Users\zht\.conda\envs\chatglm\lib\logging\__init__.py", line 943, in format
    return fmt.format(record)
  File "C:\Users\zht\.conda\envs\chatglm\lib\logging\__init__.py", line 678, in format
    record.message = record.getMessage()
  File "C:\Users\zht\.conda\envs\chatglm\lib\logging\__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "C:\work\ChatGLM3-main\openai_api_demo\openai_api.py", line 242, in <module>
    uvicorn.run(app, host='0.0.0.0', port=8000, workers=1)
  File "C:\Users\zht\.conda\envs\chatglm\lib\site-packages\uvicorn\main.py", line 587, in run
    server.run()
  File "C:\Users\zht\.conda\envs\chatglm\lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\zht\.conda\envs\chatglm\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\zht\.conda\envs\chatglm\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\zht\.conda\envs\chatglm\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\zht\.conda\envs\chatglm\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\zht\.conda\envs\chatglm\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "C:\Users\zht\.conda\envs\chatglm\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\zht\.conda\envs\chatglm\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\zht\.conda\envs\chatglm\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\zht\.conda\envs\chatglm\lib\site-packages\fastapi\applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\zht\.conda\envs\chatglm\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\zht\.conda\envs\chatglm\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\zht\.conda\envs\chatglm\lib\site-packages\starlette\middleware\cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\zht\.conda\envs\chatglm\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\zht\.conda\envs\chatglm\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\zht\.conda\envs\chatglm\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\zht\.conda\envs\chatglm\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\Users\zht\.conda\envs\chatglm\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "C:\Users\zht\.conda\envs\chatglm\lib\site-packages\fastapi\routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\zht\.conda\envs\chatglm\lib\site-packages\fastapi\routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "C:\work\ChatGLM3-main\openai_api_demo\openai_api.py", line 143, in create_chat_completion
    response = generate_chatglm3(model, tokenizer, gen_params)
  File "C:\work\ChatGLM3-main\openai_api_demo\utils.py", line 229, in generate_chatglm3
    for response in generate_stream_chatglm3(model, tokenizer, params):
  File "C:\Users\zht\.conda\envs\chatglm\lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "C:\work\ChatGLM3-main\openai_api_demo\utils.py", line 149, in generate_stream_chatglm3
    for total_ids in model.stream_generate(**inputs, eos_token_id=eos_token_id, **gen_kwargs):
  File "C:\Users\zht\.conda\envs\chatglm\lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "C:\Users\zht/.cache\huggingface\modules\transformers_modules\chatglm3-6b\modeling_chatglm.py", line 1118, in stream_generate
    logger.warn(
Message: 'Both `max_new_tokens` (=100) and `max_length`(=154) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)'
Arguments: (<class 'UserWarning'>,)

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1

### Expected behavior / 期待表现

目前接口有返回消息，就是一直提示以上错误警告信息

**Comment by zRzRzRzRzRzRzR** [comment]
更新到最新代码，OpenAI的接口修改了

**Comment by zRzRzRzRzRzRzR** [comment]
不应该还有max_length 检查你传入的内容还有没有这个无用参数

**Comment by auroralzone** [comment]
同问+1

**Comment by zRzRzRzRzRzRzR** [comment]
新代码已经解决这个问题，记得在调用的时候将openai的库更新到1.2.0之后，如果还有问题，请重新提出issue，感谢
