### ISSUE TITLE
报错看不懂

### ISSUE THREAD

**Issue by lingyezhixing** [THUDM/ChatGLM3#321]
### System Info / 系統信息

windows11
python3.10.10
cuda12.0
transformers4.30.2

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

曾尝试使用venv创建环境（因为虽然装了conda但不会用），composite_demo里的requirements也安装过了，不管是否启用虚拟环境报错都一样：
D:\ChatGLM3-6B\composite_demo>streamlit run main.py export MODEL_PATH=D:\ChatGLM3-6B\chatglm3-6b

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://172.23.164.26:8501

2023-11-16 00:17:01.047 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\31940\AppData\Local\Programs\Python\Python310\lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 264, in _get_or_create_cached_value
    cached_result = cache.read_result(value_key)
  File "C:\Users\31940\AppData\Local\Programs\Python\Python310\lib\site-packages\streamlit\runtime\caching\cache_resource_api.py", line 500, in read_result
    raise CacheKeyNotFoundError()
streamlit.runtime.caching.cache_errors.CacheKeyNotFoundError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\31940\AppData\Local\Programs\Python\Python310\lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 312, in _handle_cache_miss
    cached_result = cache.read_result(value_key)
  File "C:\Users\31940\AppData\Local\Programs\Python\Python310\lib\site-packages\streamlit\runtime\caching\cache_resource_api.py", line 500, in read_result
    raise CacheKeyNotFoundError()
streamlit.runtime.caching.cache_errors.CacheKeyNotFoundError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\31940\AppData\Local\Programs\Python\Python310\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "D:\ChatGLM3-6B\composite_demo\main.py", line 11, in <module>
    import demo_chat, demo_ci, demo_tool
  File "D:\ChatGLM3-6B\composite_demo\demo_chat.py", line 9, in <module>
    client = get_client()
  File "C:\Users\31940\AppData\Local\Programs\Python\Python310\lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 212, in wrapper
    return cached_func(*args, **kwargs)
  File "C:\Users\31940\AppData\Local\Programs\Python\Python310\lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 241, in __call__
    return self._get_or_create_cached_value(args, kwargs)
  File "C:\Users\31940\AppData\Local\Programs\Python\Python310\lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 267, in _get_or_create_cached_value
    return self._handle_cache_miss(cache, value_key, func_args, func_kwargs)
  File "C:\Users\31940\AppData\Local\Programs\Python\Python310\lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 321, in _handle_cache_miss
    computed_value = self._info.func(*func_args, **func_kwargs)
  File "D:\ChatGLM3-6B\composite_demo\client.py", line 22, in get_client
    client = HFClient(MODEL_PATH, TOKENIZER_PATH, PT_PATH)
  File "D:\ChatGLM3-6B\composite_demo\client.py", line 88, in __init__
    self.tokenizer = AutoTokenizer.from_pretrained(tokenizer_path, trust_remote_code=True)
  File "C:\Users\31940\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 676, in from_pretrained
    tokenizer_class = get_class_from_dynamic_module(class_ref, pretrained_model_name_or_path, **kwargs)
  File "C:\Users\31940\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\dynamic_module_utils.py", line 443, in get_class_from_dynamic_module
    return get_class_in_module(class_name, final_module.replace(".py", ""))
  File "C:\Users\31940\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\dynamic_module_utils.py", line 164, in get_class_in_module
    module = importlib.import_module(module_path)
  File "C:\Users\31940\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'transformers_modules.'

应该不会是必须用conda把？

### Expected behavior / 期待表现

正常运行，最好是用venv

**Comment by zRzRzRzRzRzRzR** [comment]
大概率是你虚拟环境没有配对

**Comment by Radium777** [comment]
windows装的conda就打开conda命令行，输入conda create -n 环境名 python=3.11.5，然后用pycharm打开chatglm3这个项目，选择解释器用conda刚创建的这个环境，在pycharm的命令行里正常用pip安装就行
