### ISSUE TITLE
使用openai_api_demo里的openai_api.py报错

### ISSUE THREAD

**Issue by phpdancer** [THUDM/ChatGLM3#324]
### System Info / 系統信息

代码：最新
transformers: 4.30.2
torch: 2.0.1

报错信息如下：
--- Logging error ---
Traceback (most recent call last):
  File "/data/anaconda3/envs/py10_chatglm3/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/data/anaconda3/envs/py10_chatglm3/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/data/anaconda3/envs/py10_chatglm3/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/data/anaconda3/envs/py10_chatglm3/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/data/LLM/ChatGLM3/openai_api_demo/api.py", line 281, in <module>
    uvicorn.run(app, host='0.0.0.0', port=8002, workers=1)
  File "/data/anaconda3/envs/py10_chatglm3/lib/python3.10/site-packages/uvicorn/main.py", line 587, in run
    server.run()
  File "/data/anaconda3/envs/py10_chatglm3/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/data/anaconda3/envs/py10_chatglm3/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/data/anaconda3/envs/py10_chatglm3/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/data/anaconda3/envs/py10_chatglm3/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/data/anaconda3/envs/py10_chatglm3/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/data/anaconda3/envs/py10_chatglm3/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/data/anaconda3/envs/py10_chatglm3/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/data/anaconda3/envs/py10_chatglm3/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/data/anaconda3/envs/py10_chatglm3/lib/python3.10/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/data/anaconda3/envs/py10_chatglm3/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/data/anaconda3/envs/py10_chatglm3/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/data/anaconda3/envs/py10_chatglm3/lib/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/data/anaconda3/envs/py10_chatglm3/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/data/anaconda3/envs/py10_chatglm3/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/data/anaconda3/envs/py10_chatglm3/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/data/anaconda3/envs/py10_chatglm3/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/data/anaconda3/envs/py10_chatglm3/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/data/anaconda3/envs/py10_chatglm3/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/data/anaconda3/envs/py10_chatglm3/lib/python3.10/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "/data/LLM/ChatGLM3/openai_api_demo/api.py", line 153, in create_chat_completion
    response = generate_chatglm3(model, tokenizer, gen_params)
  File "/data/LLM/ChatGLM3/openai_api_demo/utils.py", line 231, in generate_chatglm3
    for response in generate_stream_chatglm3(model, tokenizer, params):
  File "/data/anaconda3/envs/py10_chatglm3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/data/LLM/ChatGLM3/openai_api_demo/utils.py", line 151, in generate_stream_chatglm3
    for total_ids in model.stream_generate(**inputs, eos_token_id=eos_token_id, **gen_kwargs):
  File "/data/anaconda3/envs/py10_chatglm3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm3-6b/modeling_chatglm.py", line 1118, in stream_generate
    logger.warn(
Message: 'Both `max_new_tokens` (=512) and `max_length`(=521) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)'
Arguments: (<class 'UserWarning'>,)

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

python openai_api.py

### Expected behavior / 期待表现

返回是正常的，但是有报错日志，不知道是不是跟transformer的版本有关

**Comment by Stubblef** [comment]
把utils.py里gen_kwargs的max_lengrh注释掉

**Comment by cm04918** [comment]
> 把utils.py里gen_kwargs的max_length注释掉

谢谢，我也是这个问题。虽然能用，有点强迫。现在好了！

**Comment by bh4rep** [comment]
openai_api  好像没有处理理客户端提交的api-Key ?

**Comment by zRzRzRzRzRzRzR** [comment]
bug已修复，可以看最新代码

**Comment by bh4rep** [comment]
谢谢
能否让openai_api 支持一下https ?



13905156213
 
发件人： zR
发送时间： 2023-11-17 13:11
收件人： THUDM/ChatGLM3
抄送： bh4rep; Comment
主题： Re: [THUDM/ChatGLM3] 使用openai_api_demo里的openai_api.py报错 (Issue #324)
bug已修复，可以看最新代码
―

**Comment by zRzRzRzRzRzRzR** [comment]
mark，我们之后有空做一下，目前只是先支持这个格式，确保各位开发者和中间件开发者能正常使用我们的模型
