### ISSUE TITLE
ModuleNotFoundError: No module named 'transformers.generation'

### ISSUE THREAD

**Issue by andylau004** [THUDM/ChatGLM3#349]
### System Info / 系統信息

(base) aa@bxy-a6000:~/.cache/huggingface/modules$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy

系统信息如上。

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

(torch) aa@bxy-a6000:~/ChatGLM3/basic_demo$ /home/aa/anaconda3/bin/python3 web_demo.py

Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Traceback (most recent call last):
  File "/home/aa/ChatGLM3/basic_demo/web_demo.py", line 17, in <module>
    model = AutoModel.from_pretrained(model_path, trust_remote_code=True).cuda()
  File "/home/aa/anaconda3/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 455, in from_pretrained
    model_class = get_class_from_dynamic_module(
  File "/home/aa/anaconda3/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 374, in get_class_from_dynamic_module
    return get_class_in_module(class_name, final_module.replace(".py", ""))
  File "/home/aa/anaconda3/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 147, in get_class_in_module
    module = importlib.import_module(module_path)
  File "/home/aa/anaconda3/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/aa/.cache/huggingface/modules/transformers_modules/local/modeling_chatglm.py", line 26, in <module>
    from transformers.generation.logits_process import LogitsProcessor
ModuleNotFoundError: No module named 'transformers.generation'

### Expected behavior / 期待表现

哪位遇到过啊
需要修改什么？
或是什么配置错误导致？
请教了。

**Comment by zRzRzRzRzRzRzR** [comment]
版本对吗

**Comment by andylau004** [comment]
@zRzRzRzRzRzRzR 搞定啦。
3Q . 

python 虚拟环境问题。

**Comment by Palpitate-xus** [comment]
> @zRzRzRzRzRzRzR 搞定啦。 3Q .
> 
> python 虚拟环境问题。

请问您是如何解决的，我也遇到这个问题了
