### ISSUE TITLE
在运行./scripts/finetune_pt_multiturn.sh的时候报错了。TypeError: ChatGLMPreTrainedModel._set_gradient_checkpointing() got an unexpected keyword argument 'enable'

### ISSUE THREAD

**Issue by CapenZen** [THUDM/ChatGLM3#380]
<<<<<<<<<<<<< Sanity Check
[INFO|trainer.py:544] 2023-11-20 20:46:12,587 >> max_steps is given, it will override any value given in num_train_epochs
Traceback (most recent call last):
  File "/home/capen/ChatGLM3-main/finetune_demo/finetune.py", line 165, in <module>
    main()
  File "/home/capen/ChatGLM3-main/finetune_demo/finetune.py", line 158, in main
    model.gradient_checkpointing_enable()
  File "/home/capen/下载/ENTER/envs/chat/lib/python3.10/site-packages/transformers/modeling_utils.py", line 1872, in gradient_checkpointing_enable
    self._set_gradient_checkpointing(enable=True, gradient_checkpointing_func=gradient_checkpointing_func)
TypeError: ChatGLMPreTrainedModel._set_gradient_checkpointing() got an unexpected keyword argument 'enable'
[2023-11-20 20:46:12,896] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 14845) of binary: /home/capen/下载/ENTER/envs/chat/bin/python
Traceback (most recent call last):
  File "/home/capen/下载/ENTER/envs/chat/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/capen/下载/ENTER/envs/chat/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/capen/下载/ENTER/envs/chat/lib/python3.10/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/home/capen/下载/ENTER/envs/chat/lib/python3.10/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/home/capen/下载/ENTER/envs/chat/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/capen/下载/ENTER/envs/chat/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
finetune.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-11-20_20:46:12
  host      : capen
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 14845)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by zRzRzRzRzRzRzR** [comment]
三个问题先排查一下：
1. 路径有中文（不太可能是这个问题，但是可以排查一下）
2. pytorch安装可鞥出现问题（根据你的系统信息去网上查一下对应的pytorch问题），确定你是多卡微调
3, 如果都不是，提供一下你的系统环境信息（含硬件），我们看一下

**Comment by zRzRzRzRzRzRzR** [comment]
微调相关问题移动到 #253 进行讨论，这方面社区经验可能比我们更多，目前没有复现出你的问题
