### ISSUE TITLE
缺少 jupyter_client 模块

### ISSUE THREAD

**Issue by ikingye** [THUDM/ChatGLM3#39]
安装依赖 pip install -r requirements.txt

然后 streamlit run main.py

然后报错下面信息：
```
2023-10-29 00:31:32.581 Uncaught app exception
Traceback (most recent call last):
  File "/home/xxx/.local/share/virtualenvs/ChatGLM3-uTamXjui/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "/home/xxx/code/github/ChatGLM3/composite_demo/main.py", line 11, in <module>
    import demo_chat, demo_ci, demo_tool
  File "/home/xxx/code/github/ChatGLM3/composite_demo/demo_ci.py", line 9, in <module>
    import jupyter_client
ModuleNotFoundError: No module named 'jupyter_client'
```

安装 pip install jupyter_client
之后正常

**Comment by Btlmd** [comment]
感谢反馈
但是 requirements.txt 中含有 `jupyter_client` : https://github.com/THUDM/ChatGLM3/blob/main/composite_demo/requirements.txt#L4
