### ISSUE TITLE
各种Bad Case请检查 Discussion中的内容

### ISSUE THREAD

**Issue by zRzRzRzRzRzRzR** [THUDM/ChatGLM3#394]
以下问题不要在issue中提出，因为：
1. 这个问题是模型的上的功能缺失或者bad case
2. 官方暂时不能解决这个问题

如果你遇到以下问题，请你在Discussion中提出具体的 bad case，这些问题在本代模型难以解决，更多的bad case将能帮助我们优化出更好的模型。

#393 模型运行的 CUDA error: device-side assert相关问题
#212 工具调用混乱，一些场景被训练为调用工具
#335 多轮对话无法实现正常工具调用
#306 在持续进行对话时候GPU 内存占用飙升
#310 多卡推理不正常,乱码相关问题
#225 中英文混合输出，输出会带英语单词

上述问题在Issue提出可能会被直接关闭。请注意！

**Comment by youyouge** [comment]
几个问题想请教一下，
第一：为什么训练出来的模型是问答式的，是因为数据量太少吗，格式和官方给的测试数据集格式一样都是类型#描述*类型#描述，训练使用的是./scripts/finetune_pt.sh  参数只改了sourse和target还有step三个数值。
第二：为什么训练完的模型，使用“cd ../composite_demo
MODEL_PATH="THUDM/chatglm3-6b" PT_PATH="path to p-tuning checkpoint" streamlit run main.py”启动UI界面,使用API启动，最终运行的还是原来的chatglm3-6b，不是微调后的模型
第三：数据集的格式“类型#描述*类型#描述”，后面只描述一个或多个描述词或者类型词，可以得到回复吗，是经过ChatGLM3-6B思考后的回复还是数据集的内容完全一模一样的回复还是会参考数据集答案的格式来回复。。。。

**Comment by kokomidaisiki** [comment]
关于懒人包的使用，b站视频来的，抱歉因为技术不行不知道哪里出了问题
![mmexport1703184293371](https://github.com/THUDM/ChatGLM3/assets/154550418/590f40ca-ffb9-4f69-86d0-8d91a2b3a134)

**Comment by whisky-12** [comment]
请问openai_api.py是否会更细关于处理向量的 v1/embedding的接口？

**Comment by lostmaniac** [comment]
> 请问openai_api.py是否会更细关于处理向量的 v1/embedding的接口？

直接合并一下别的项目的代码就行了.

**Comment by zRzRzRzRzRzRzR** [comment]
openai demo 已经更新 支持了embedded

**Comment by CNCSMonster** [comment]
Discussion是说在这里的comment吗? <---像这样?

**Comment by zRzRzRzRzRzRzR** [comment]
是在 github disscussion对应的标题讨论

**Comment by langshuocheng** [comment]
ASK： 

- ChatGLM3是使用BBPE实现分词么？

**Comment by itlittlekou** [comment]
你好，我在用lora微调过程中，一直卡在
Total optimization steps = 3,000
  Number of trainable parameters = 1,949,696
  0% 0/3000 [00:00<?, ?it/s]
  这个地方不动了是什么原因呀，请教各位大佬指教

**Comment by itlittlekou** [comment]
你好，在lora微调过程中出现了RuntimeError: "addmm_impl_cpu_" not implemented for 'Half'，这个问题，我提升了pytorch的版本之后，就一直卡在
otal optimization steps = 3,000
Number of trainable parameters = 1,949,696
0% 0/3000 [00:00<?, ?it/s]
这个地方不动了是什么原因呀，请教各位大佬指教

**Comment by LiangYong1216** [comment]
这个错误通常发生在使用PyTorch框架进行深度学习模型训练时，特别是在尝试使用半精度浮点数（‘Half’，即16位浮点数）进行矩阵乘加操作（addmm）时。半精度浮点数是一种用于加速计算和减少内存占用的技术，但它并不支持所有的操作。
为了解决这个问题，你可以考虑以下几种方法：
使用全精度浮点数（‘Float’）： 将模型和数据类型转换为全精度浮点数，通常是32位浮点数（torch.float32 或 torch.FloatTensor）。这样可以确保所有的操作都是支持的，但是会增加内存使用和计算时间。

# 例如，将一个张量从半精度转换为全精度
tensor = tensor.to(dtype=torch.float32)

**Comment by RexxyWong** [comment]
如果出現以下問題要如何解決，我是使用官方我代碼和DATASET試行

RuntimeError: element 0 of tensors does not require grad and does not have a 
grad_fn
  0%|                                                  | 0/3000 [00:01<?, ?it/s]

**Comment by lei124215** [comment]
> 你好，在lora微调过程中出现了RuntimeError: "addmm_impl_cpu_" not implemented for 'Half'，这个问题，我提升了pytorch的版本之后，就一直卡在 otal optimization steps = 3,000 Number of trainable parameters = 1,949,696 0% 0/3000 [00:00<?, ?it/s] 这个地方不动了是什么原因呀，请教各位大佬指教

您好，请问问题解决了吗，我也遇到了相同的问题

**Comment by NENCAO** [comment]
我在使用glm3的时候  embeddings接口一直报如图的错误是为什么呢
![QQ截图20240330160435](https://github.com/THUDM/ChatGLM3/assets/13777693/ac6d939f-6dd9-4356-a1fd-f43718f69cd7)

**Comment by GPTisallyouneed** [comment]
请问各位大佬，uvicorn实现api_server时，为什么workers大于1的时候会报错：模型未定义。难道不能实现多进程吗，该怎么解决这个问题？

**Comment by FanZhang91** [comment]
用main分支代码做finetune, 用inference_hf代码做预测在解析responce中的output时会报错？而且finetune保存的模型，无法直接用composite_demo的形式直接调用？请问如何解决这两个问题？

**Comment by NLP-1217** [comment]
有个训练中的问题请教。

我在微调LORA代码上修改为自己的数据。训练过程中报错如下：

Traceback (most recent call last) ──────────────────────╮
│ /root/autodl-tmp/ChatGLM3/finetune_demo/finetune_hf.py:526 in main           │
│                                                                              │
│   523 │   │   │   return_tensors='pt',                                       │
│   524 │   │   ),                                                             │
│   525 │   │   train_dataset=train_dataset,                                   │
│ ❱ 526 │   │   eval_dataset=val_dataset.select(list(range(50))),              │
│   527 │   │   # tokenizer=tokenizer, # to avoid the wrong of the tokenizer   │
│   528 │   │   compute_metrics=functools.partial(compute_metrics, tokenizer=t │
│   529 │   )                                                                  │
│                                                                              │
│ /root/miniconda3/lib/python3.10/site-packages/datasets/arrow_dataset.py:558  │
│ in wrapper                                                                   │
│                                                                              │
│    555 │   │   │   "output_all_columns": self._output_all_columns,           │
│    556 │   │   }                                                             │
│    557 │   │   # apply actual function                                       │
│ ❱  558 │   │   out: Union["Dataset", "DatasetDict"] = func(self, *args, **kw │
│    559 │   │   datasets: List["Dataset"] = list(out.values()) if isinstance( │
│    560 │   │   # re-apply format to the output                               │
│    561 │   │   for dataset in datasets:                                      │
│                                                                              │
│ /root/miniconda3/lib/python3.10/site-packages/datasets/fingerprint.py:482 in │
│ wrapper                                                                      │
│                                                                              │
│   479 │   │   │                                                              │
│   480 │   │   │   # Call actual function                                     │
│   481 │   │   │                                                              │
│ ❱ 482 │   │   │   out = func(dataset, *args, **kwargs)                       │
│   483 │   │   │                                                              │
│   484 │   │   │   # Update fingerprint of in-place transforms + update in-pl │
│   485                                                                        │
│                                                                              │
│ /root/miniconda3/lib/python3.10/site-packages/datasets/arrow_dataset.py:3829 │
│ in select                                                                    │
│                                                                              │
│   3826 │   │   │   │   counter_from_start = itertools.count(start=start)     │
│   3827 │   │   │   │   if all(i == j for i, j in zip(indices, counter_from_s │
│   3828 │   │   │   │   │   length = next(counter_from_start) - start         │
│ ❱ 3829 │   │   │   │   │   return self._select_contiguous(start, length, new │
│   3830 │   │                                                                 │
│   3831 │   │   # If not contiguous, we need to create a new indices mapping  │
│   3832 │   │   return self._select_with_indices_mapping(                     │
│                                                                              │
│ /root/miniconda3/lib/python3.10/site-packages/datasets/arrow_dataset.py:558  │
│ in wrapper                                                                   │
│                                                                              │
│    555 │   │   │   "output_all_columns": self._output_all_columns,           │
│    556 │   │   }                                                             │
│    557 │   │   # apply actual function                                       │
│ ❱  558 │   │   out: Union["Dataset", "DatasetDict"] = func(self, *args, **kw │
│    559 │   │   datasets: List["Dataset"] = list(out.values()) if isinstance( │
│    560 │   │   # re-apply format to the output                               │
│    561 │   │   for dataset in datasets:                                      │
│                                                                              │
│ /root/miniconda3/lib/python3.10/site-packages/datasets/fingerprint.py:482 in │
│ wrapper                                                                      │
│                                                                              │
│   479 │   │   │                                                              │
│   480 │   │   │   # Call actual function                                     │
│   481 │   │   │                                                              │
│ ❱ 482 │   │   │   out = func(dataset, *args, **kwargs)                       │
│   483 │   │   │                                                              │
│   484 │   │   │   # Update fingerprint of in-place transforms + update in-pl │
│   485                                                                        │
│                                                                              │
│ /root/miniconda3/lib/python3.10/site-packages/datasets/arrow_dataset.py:3879 │
│ in _select_contiguous                                                        │
│                                                                              │
│   3876 │   │   │   return self                                               │
│   3877 │   │                                                                 │
│   3878 │   │   _check_valid_indices_value(start, len(self))                  │
│ ❱ 3879 │   │   _check_valid_indices_value(start + length - 1, len(self))     │
│   3880 │   │   if self._indices is None or length == 0:                      │
│   3881 │   │   │   return Dataset(                                           │
│   3882 │   │   │   │   self.data.slice(start, length),                       │
│                                                                              │
│ /root/miniconda3/lib/python3.10/site-packages/datasets/arrow_dataset.py:650  │
│ in _check_valid_indices_value                                                │
│                                                                              │
│    647                                                                       │
│    648 def _check_valid_indices_value(index, size):                          │
│    649 │   if (index < 0 and index + size < 0) or (index >= size):           │
│ ❱  650 │   │   raise IndexError(f"Index {index} out of range for dataset of  │
│    651                                                                       │
│    652                                                                       │
│    653 class NonExistentDatasetError(Exception):                             │
╰──────────────────────────────────────────────────────────────────────────────╯
IndexError: Index 49 out of range for dataset of size 33.

<img width="413" alt="截屏2024-04-15 15 22 43" src="https://github.com/THUDM/ChatGLM3/assets/37143910/2c631702-2809-4f78-896f-afe582c8a97f">

发现训练集的num_row和训练数据集数量一致。
测试集和验证集原本数据量为545，不知道为什么成为33？

还想问一下问题怎么调整呢？

**Comment by Bule-dog** [comment]
为什么我在微调时48G显存都会爆了
![QQ截图20240417123028](https://github.com/THUDM/ChatGLM3/assets/72481555/2f25adde-7490-40b2-a054-f73437fadaf5)

**Comment by zainCSU** [comment]
![d119bab636a2dcc61284d5662cebfac](https://github.com/THUDM/ChatGLM3/assets/161547938/ab7fc97c-4735-4987-8e58-ba0b706ba0c5)
请问使用双卡报错这个有什么办法解决吗

**Comment by Mouasea** [comment]
请问下chat-glm3-6B的模型参数：Hidden Size、Num Layers、Num Attention Heads、Vocab Size是多少呀？没有在社区中看到有公布这个信息

**Comment by jwc19890114** [comment]
在本地安装之后，使用streamlit和graido都可以进入界面，但是提问没有反应，这是什么情况啊

**Comment by michaelwind1315** [comment]
启动composite_demo之后提问响应极慢，看起来没有启用GPU加速，需要怎么修改启动GPU加速呢？

**Comment by thomasyyang** [comment]
**第一次尝试 github 中微调示例，未执行成功，报以下错误，请问如何解决？：**

**「执行命令」：**CUDA_VISIBLE_DEVICES=0 NCCL_P2P_DISABLE="1" NCCL_IB_DISABLE="1" python finetune_hf.py  data/AdvertiseGen_fix  /home/notebook/toG_RMM/MHRED/chatglm3-6b  configs/lora.yaml

**「输出信息」：**
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/opt/notebook/toG_RMM/MHRED/ChatGLM3-main/finetune_demo/finetune_hf.py", line 11, in <module>
    import torch
  File "/home/conda/envs/python3.10.6/lib/python3.10/site-packages/torch/__init__.py", line 1382, in <module>
    from .functional import *  # noqa: F403
  File "/home/conda/envs/python3.10.6/lib/python3.10/site-packages/torch/functional.py", line 7, in <module>
    import torch.nn.functional as F
  File "/home/conda/envs/python3.10.6/lib/python3.10/site-packages/torch/nn/__init__.py", line 1, in <module>
    from .modules import *  # noqa: F403
  File "/home/conda/envs/python3.10.6/lib/python3.10/site-packages/torch/nn/modules/__init__.py", line 35, in <module>
    from .transformer import TransformerEncoder, TransformerDecoder, \
  File "/home/conda/envs/python3.10.6/lib/python3.10/site-packages/torch/nn/modules/transformer.py", line 20, in <module>
    device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
/home/conda/envs/python3.10.6/lib/python3.10/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:84.)
  device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /opt/notebook/toG_RMM/MHRED/ChatGLM3-main/finetune_demo/ │
│ finetune_hf.py:458 in main                                                                       │
│                                                                                                  │
│   455 │   │   ),                                                                                 │
│   456                                                                                            │
│   457 ):                                                                                         │
│ ❱ 458 │   ft_config = FinetuningConfig.from_file(config_file)                                    │
│   459 │   tokenizer, model = load_tokenizer_and_model(model_dir, peft_config=ft_config.peft_co   │
│   460 │   data_manager = DataManager(data_dir, ft_config.data_config)                            │
│   461                                                                                            │
│                                                                                                  │
│ /opt/notebook/toG_RMM/MHRED/ChatGLM3-main/finetune_demo/ │
│ finetune_hf.py:209 in from_file                                                                  │
│                                                                                                  │
│   206 │   def from_file(cls, path: Union[str, Path]) -> 'FinetuningConfig':                      │
│   207 │   │   path = _resolve_path(path)                                                         │
│   208 │   │   kwargs = _get_yaml_parser().load(path)                                             │
│ ❱ 209 │   │   return cls.from_dict(**kwargs)                                                     │
│   210                                                                                            │
│   211                                                                                            │
│   212 def _load_datasets(                                                                        │
│                                                                                                  │
│ /opt/notebook/toG_RMM/MHRED/ChatGLM3-main/finetune_demo/ │
│ finetune_hf.py:194 in from_dict                                                                  │
│                                                                                                  │
│   191 │   │   │   │   training_args['generation_config'] = GenerationConfig(                     │
│   192 │   │   │   │   │   **gen_config                                                           │
│   193 │   │   │   │   )                                                                          │
│ ❱ 194 │   │   │   kwargs['training_args'] = Seq2SeqTrainingArguments(**training_args)            │
│   195 │   │                                                                                      │
│   196 │   │   data_config = kwargs.get('data_config')                                            │
│   197 │   │   if not isinstance(data_config, DataConfig):                                        │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: Seq2SeqTrainingArguments.__init__() got an unexpected keyword argument 'use_cpu'

**Comment by xiherespect** [comment]
### 交互就会报错 UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)

root@dsw-430842-7cc9db4b4d-gl5v6:/mnt/workspace/webcodes/ChatGLM3/basic_demo# python cli_demo.py
Setting eos_token is not supported, use the default one.
Setting pad_token is not supported, use the default one.
Setting unk_token is not supported, use the default one.
Loading checkpoint shards: 100%|█████████████████████████████████████████████| 7/7 [00:03<00:00,  1.89it/s]
欢迎使用 ChatGLM3-6B 模型，输入内容即可进行对话，clear 清空对话历史，stop 终止程序

用户： 你好

ChatGLM：2024-08-21 02:36:40.210853: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-08-21 02:36:41.289374: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/mnt/workspace/webcodes/ChatGLM3/basic_demo/cli_demo.py", line 57, in <module>
    main()
  File "/mnt/workspace/webcodes/ChatGLM3/basic_demo/cli_demo.py", line 43, in main
    for response, history, past_key_values in model.stream_chat(tokenizer, query, history=history, top_p=1,
  File "/usr/local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm3-6b/modeling_chatglm.py", line 1082, in stream_chat
    response = tokenizer.decode(outputs)
  File "/usr/local/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 3809, in decode
    token_ids = to_py_obj(token_ids)
  File "/usr/local/lib/python3.10/site-packages/transformers/utils/generic.py", line 272, in to_py_obj
    return [to_py_obj(o) for o in obj]
  File "/usr/local/lib/python3.10/site-packages/transformers/utils/generic.py", line 272, in <listcomp>
    return [to_py_obj(o) for o in obj]
  File "/usr/local/lib/python3.10/site-packages/transformers/utils/generic.py", line 277, in to_py_obj
    if test_func(obj):
  File "/usr/local/lib/python3.10/site-packages/transformers/utils/generic.py", line 211, in is_tf_tensor
    return False if not is_tf_available() else _is_tensorflow(x)
  File "/usr/local/lib/python3.10/site-packages/transformers/utils/generic.py", line 202, in _is_tensorflow
    import tensorflow as tf
  File "/usr/local/lib/python3.10/site-packages/tensorflow/__init__.py", line 45, in <module>
    from tensorflow._api.v2 import __internal__
  File "/usr/local/lib/python3.10/site-packages/tensorflow/_api/v2/__internal__/__init__.py", line 13, in <module>
    from tensorflow._api.v2.__internal__ import feature_column
  File "/usr/local/lib/python3.10/site-packages/tensorflow/_api/v2/__internal__/feature_column/__init__.py", line 8, in <module>
    from tensorflow.python.feature_column.feature_column_v2 import DenseColumn # line: 1777
  File "/usr/local/lib/python3.10/site-packages/tensorflow/python/feature_column/feature_column_v2.py", line 38, in <module>
    from tensorflow.python.feature_column import feature_column as fc_old
  File "/usr/local/lib/python3.10/site-packages/tensorflow/python/feature_column/feature_column.py", line 41, in <module>
    from tensorflow.python.layers import base
  File "/usr/local/lib/python3.10/site-packages/tensorflow/python/layers/base.py", line 16, in <module>
    from tensorflow.python.keras.legacy_tf_layers import base
  File "/usr/local/lib/python3.10/site-packages/tensorflow/python/keras/__init__.py", line 25, in <module>
    from tensorflow.python.keras import models
  File "/usr/local/lib/python3.10/site-packages/tensorflow/python/keras/models.py", line 25, in <module>
    from tensorflow.python.keras.engine import training_v1
  File "/usr/local/lib/python3.10/site-packages/tensorflow/python/keras/engine/training_v1.py", line 46, in <module>
    from tensorflow.python.keras.engine import training_arrays_v1
  File "/usr/local/lib/python3.10/site-packages/tensorflow/python/keras/engine/training_arrays_v1.py", line 37, in <module>
    from scipy.sparse import issparse  # pylint: disable=g-import-not-at-top
  File "/usr/local/lib/python3.10/site-packages/scipy/sparse/__init__.py", line 294, in <module>
    from ._base import *
  File "/usr/local/lib/python3.10/site-packages/scipy/sparse/_base.py", line 5, in <module>
    from scipy._lib._util import VisibleDeprecationWarning
  File "/usr/local/lib/python3.10/site-packages/scipy/_lib/_util.py", line 18, in <module>
    from scipy._lib._array_api import array_namespace
  File "/usr/local/lib/python3.10/site-packages/scipy/_lib/_array_api.py", line 15, in <module>
    from numpy.testing import assert_
  File "/usr/local/lib/python3.10/site-packages/numpy/testing/__init__.py", line 11, in <module>
    from ._private.utils import *
  File "/usr/local/lib/python3.10/site-packages/numpy/testing/_private/utils.py", line 1253, in <module>
    _SUPPORTS_SVE = check_support_sve()
  File "/usr/local/lib/python3.10/site-packages/numpy/testing/_private/utils.py", line 1247, in check_support_sve
    output = subprocess.run(cmd, capture_output=True, text=True)
  File "/usr/local/lib/python3.10/subprocess.py", line 505, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/local/lib/python3.10/subprocess.py", line 1154, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/local/lib/python3.10/subprocess.py", line 2059, in _communicate
    stdout = self._translate_newlines(stdout,
  File "/usr/local/lib/python3.10/subprocess.py", line 1031, in _translate_newlines
    data = data.decode(encoding, errors)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)

**Comment by GH-cz0827** [comment]
### 完全不能启动，操作系统是基于Mobaxterm的Linux远程主机  
模型是从modelscope克隆的，但删除了名称含safetensors的所有文件；检查了cli_demo.py中MODEL_PATH路径无误，直接运行python3 cli_demo.py会报错如下：
(glm) s_xyw@ychx:~/TanHC/GLMtest/ChatGLM3/basic_demo$ python3 cli_demo.py
Traceback (most recent call last):
  File "cli_demo.py", line 8, in <module>
    tokenizer = AutoTokenizer.from_pretrained(TOKENIZER_PATH, trust_remote_code=True)
  File "/home/s_xyw/.local/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py", line 847, in from_pretrained
    return tokenizer_class.from_pretrained(
  File "/home/s_xyw/.local/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2089, in from_pretrained
    return cls._from_pretrained(
  File "/home/s_xyw/.local/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2311, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/home/s_xyw/.cache/huggingface/modules/transformers_modules/chatglm3-6b/tokenization_chatglm.py", line 109, in __init__
    self.tokenizer = SPTokenizer(vocab_file)
  File "/home/s_xyw/.cache/huggingface/modules/transformers_modules/chatglm3-6b/tokenization_chatglm.py", line 18, in __init__
    self.sp_model = SentencePieceProcessor(model_file=model_path)
  File "/home/s_xyw/.local/lib/python3.8/site-packages/sentencepiece/__init__.py", line 468, in Init
    self.Load(model_file=model_file, model_proto=model_proto)
  File "/home/s_xyw/.local/lib/python3.8/site-packages/sentencepiece/__init__.py", line 961, in Load
    return self.LoadFromFile(model_file)
  File "/home/s_xyw/.local/lib/python3.8/site-packages/sentencepiece/__init__.py", line 316, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
RuntimeError: Internal: could not parse ModelProto from /home/s_xyw/TanHC/GLMtest/chatglm3-6b/tokenizer.model

是modelscope的tokenizer.model文件有问题吗？另外这个远程主机因为网络问题没法连接到huggingface，不能从hf克隆模型

**Comment by Hoyxxx** [comment]
python inference_hf.py ./output/checkpoint-3000 --prompt "listen to westbam alumb allergic on google music"
为什么调用训练后的模型没有效果，感觉还是原模型的回复

**Comment by GuoDragon** [comment]
请问在进行lora微调合并模型时，使用
CUDA_VISIBLE_DEVICES=0 llamafactory-cli export \
  --model_name_or_path ....../chatglm3-6b \
  --adapter_name_or_path ....../lora/sft \
  --template chatglm3 \
  --trust_remote_code \
  --finetuning_type lora \
  --export_dir ....../lora/merged_model \
  --export_size 1 \
  --export_device cpu \
  --export_legacy_format true
报错ValueError: Dict is not supported.该怎么办啊

**Comment by whisky-12** [comment]
需要贴出全部的详细报错信息，来定位报错 。

以上 ，辛苦了！！！






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2025年5月14日(星期三) 下午5:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [THUDM/ChatGLM3] 这些问题不要在Issue提出，在Discussion中提出 (Issue #394)












GuoDragon left a comment (THUDM/ChatGLM3#394)
 
请问在进行lora微调合并模型时，使用
 CUDA_VISIBLE_DEVICES=0 llamafactory-cli export 
 --model_name_or_path ....../chatglm3-6b 
 --adapter_name_or_path ....../lora/sft 
 --template chatglm3 
 --trust_remote_code 
 --finetuning_type lora 
 --export_dir ....../lora/merged_model 
 --export_size 1 
 --export_device cpu 
 --export_legacy_format true
 报错ValueError: Dict is not supported.该怎么办啊

**Comment by GuoDragon** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
