### ISSUE TITLE
请问 RuntimeError: "addmm_impl_cpu_" not implemented for 'Half'怎么解决

### ISSUE THREAD

**Issue by einsflash** [THUDM/ChatGLM3#40]
=== History:
[Conversation(role=<Role.USER: 2>, content='1', tool=None, image=None)]
2023-10-28 23:14:33.424 Uncaught app exception
Traceback (most recent call last):
  File "E:\ChatGLM3\venv\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "E:\ChatGLM3\composite_demo\main.py", line 50, in <module>
    demo_chat.main(top_p, temperature, system_prompt, prompt_text)
  File "E:\ChatGLM3\composite_demo\demo_chat.py", line 50, in main
    for response in client.generate_stream(
  File "E:\ChatGLM3\composite_demo\client.py", line 119, in generate_stream
    for new_text, _ in stream_chat(self.model,
  File "E:\ChatGLM3\composite_demo\client.py", line 69, in stream_chat
    for outputs in self.stream_generate(**inputs, past_key_values=past_key_values,
  File "E:\ChatGLM3\venv\lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "C:\Users\zhuya/.cache\huggingface\modules\transformers_modules\THUDM\chatglm3-6b\fc3235f807ef5527af598c05f04f2ffd17f48bab\modeling_chatglm.py", line 1156, in stream_generate
    outputs = self(
  File "E:\ChatGLM3\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\ChatGLM3\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\zhuya/.cache\huggingface\modules\transformers_modules\THUDM\chatglm3-6b\fc3235f807ef5527af598c05f04f2ffd17f48bab\modeling_chatglm.py", line 937, in forward
    transformer_outputs = self.transformer(
  File "E:\ChatGLM3\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\ChatGLM3\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\zhuya/.cache\huggingface\modules\transformers_modules\THUDM\chatglm3-6b\fc3235f807ef5527af598c05f04f2ffd17f48bab\modeling_chatglm.py", line 830, in forward
    hidden_states, presents, all_hidden_states, all_self_attentions = self.encoder(
  File "E:\ChatGLM3\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\ChatGLM3\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\zhuya/.cache\huggingface\modules\transformers_modules\THUDM\chatglm3-6b\fc3235f807ef5527af598c05f04f2ffd17f48bab\modeling_chatglm.py", line 640, in forward
    layer_ret = layer(
  File "E:\ChatGLM3\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\ChatGLM3\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\zhuya/.cache\huggingface\modules\transformers_modules\THUDM\chatglm3-6b\fc3235f807ef5527af598c05f04f2ffd17f48bab\modeling_chatglm.py", line 544, in forward
    attention_output, kv_cache = self.self_attention(
  File "E:\ChatGLM3\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\ChatGLM3\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\zhuya/.cache\huggingface\modules\transformers_modules\THUDM\chatglm3-6b\fc3235f807ef5527af598c05f04f2ffd17f48bab\modeling_chatglm.py", line 376, in forward
    mixed_x_layer = self.query_key_value(hidden_states)
  File "E:\ChatGLM3\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\ChatGLM3\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\ChatGLM3\venv\lib\site-packages\torch\nn\modules\linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: "addmm_impl_cpu_" not implemented for 'Half'

**Comment by einsflash** [comment]
没事了

**Comment by zephyrkz** [comment]
你怎么解决的呀

**Comment by scut-pzy** [comment]
我按照题主的方法试过没啥用啊，题主能具体命令也说一下吗

**Comment by einsflash** [comment]
我当时看的这个视频
https://b23.tv/LRDA0vR

**Comment by scut-pzy** [comment]
跑起来但是只要一提问，量化要19g显存，非量化23G现存，有什么头绪吗

**Comment by einsflash** [comment]
不清楚，我3070 8g能跑，不量化就是13g加上内存一起跑发件人: ***@***.*** ***@***.***> 代表 Panda Po ***@***.***>发送时间: 星期三, 十一月 1, 2023 3:12:50 下午收件人: THUDM/ChatGLM3 ***@***.***>抄送: einsflash ***@***.***>; State change ***@***.***>主题: Re: [THUDM/ChatGLM3] 请问 RuntimeError: "addmm_impl_cpu_" not implemented for 'Half'怎么解决 (Issue #40)
跑起来但是只要一提问，量化要19g显存，非量化23G现存，有什么头绪吗
