### ISSUE TITLE
多轮对话微调报错

### ISSUE THREAD

**Issue by gaizi001** [THUDM/ChatGLM3#405]
### System Info / 系統信息

无

### Who can help? / 谁可以帮助到您？

无

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

https://github.com/THUDM/ChatGLM3/blob/main/finetune_demo/README.md

我是根据官网这个多轮对话微调做的，自己整理了一些相同格式的数据，

finetune_pt_multiturn.sh只改了基础模型路径改成了本地加载，还有数据集路径。

然后根据官网文档操作提示显存爆了，我是两张T4的卡（可用显存共30G左右）

以下是报错日志

<<<<<<<<<<<<< Sanity Check
11/22/2023 16:24:25 - WARNING - accelerate.utils.other - Detected kernel version 3.10.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
Loading checkpoint shards: 100%|██████████| 7/7 [00:15<00:00,  2.21s/it]
[WARNING|modeling_utils.py:3297] 2023-11-22 16:24:26,695 >> Some weights of ChatGLMForConditionalGeneration were not initialized from the model checkpoint at /jcdata/workspace/ChatGLM3/model and are newly initialized: ['transformer.prefix_encoder.embedding.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/root/anaconda3/envs/chatglm3-demo/lib/python3.10/site-packages/transformers/optimization.py:411: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
[INFO|trainer.py:577] 2023-11-22 16:24:31,233 >> max_steps is given, it will override any value given in num_train_epochs
/root/anaconda3/envs/chatglm3-demo/lib/python3.10/site-packages/transformers/optimization.py:411: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
[INFO|trainer.py:1786] 2023-11-22 16:24:34,257 >> ***** Running training *****
[INFO|trainer.py:1787] 2023-11-22 16:24:34,257 >>   Num examples = 276
[INFO|trainer.py:1788] 2023-11-22 16:24:34,257 >>   Num Epochs = 375
[INFO|trainer.py:1789] 2023-11-22 16:24:34,257 >>   Instantaneous batch size per device = 1
[INFO|trainer.py:1790] 2023-11-22 16:24:34,257 >>   Total train batch size (w. parallel, distributed & accumulation) = 32
[INFO|trainer.py:1791] 2023-11-22 16:24:34,257 >>   Gradient Accumulation steps = 16
[INFO|trainer.py:1792] 2023-11-22 16:24:34,257 >>   Total optimization steps = 3,000
[INFO|trainer.py:1793] 2023-11-22 16:24:34,258 >>   Number of trainable parameters = 1,835,008
  0%|          | 0/3000 [00:00<?, ?it/s]11/22/2023 16:24:34 - WARNING - transformers_modules.model.modeling_chatglm - `use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`...
11/22/2023 16:24:34 - WARNING - transformers_modules.model.modeling_chatglm - `use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`...
/root/anaconda3/envs/chatglm3-demo/lib/python3.10/site-packages/torch/utils/checkpoint.py:429: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(
/root/anaconda3/envs/chatglm3-demo/lib/python3.10/site-packages/torch/utils/checkpoint.py:429: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(
Traceback (most recent call last):
  File "/jcdata/workspace/ChatGLM3/finetune_demo_yuqing/finetune.py", line 165, in <module>
    main()
  File "/jcdata/workspace/ChatGLM3/finetune_demo_yuqing/finetune.py", line 160, in main
    trainer.train(resume_from_checkpoint=checkpoint)
  File "/root/anaconda3/envs/chatglm3-demo/lib/python3.10/site-packages/transformers/trainer.py", line 1645, in train
    return inner_training_loop(
  File "/root/anaconda3/envs/chatglm3-demo/lib/python3.10/site-packages/transformers/trainer.py", line 1938, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/root/anaconda3/envs/chatglm3-demo/lib/python3.10/site-packages/transformers/trainer.py", line 2770, in training_step
Traceback (most recent call last):
  File "/jcdata/workspace/ChatGLM3/finetune_demo_yuqing/finetune.py", line 165, in <module>
    self.accelerator.backward(loss)
    main()  File "/root/anaconda3/envs/chatglm3-demo/lib/python3.10/site-packages/accelerate/accelerator.py", line 1989, in backward

  File "/jcdata/workspace/ChatGLM3/finetune_demo_yuqing/finetune.py", line 160, in main
    trainer.train(resume_from_checkpoint=checkpoint)
  File "/root/anaconda3/envs/chatglm3-demo/lib/python3.10/site-packages/transformers/trainer.py", line 1645, in train
    loss.backward(**kwargs)
  File "/root/anaconda3/envs/chatglm3-demo/lib/python3.10/site-packages/torch/_tensor.py", line 492, in backward
    return inner_training_loop(
  File "/root/anaconda3/envs/chatglm3-demo/lib/python3.10/site-packages/transformers/trainer.py", line 1938, in _inner_training_loop
    torch.autograd.backward(
  File "/root/anaconda3/envs/chatglm3-demo/lib/python3.10/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 508.00 MiB. GPU 0 has a total capacty of 14.62 GiB of which 295.38 MiB is free. Including non-PyTorch memory, this process has 14.32 GiB memory in use. Of the allocated memory 13.20 GiB is allocated by PyTorch, and 350.86 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
    tr_loss_step = self.training_step(model, inputs)
  File "/root/anaconda3/envs/chatglm3-demo/lib/python3.10/site-packages/transformers/trainer.py", line 2770, in training_step
    self.accelerator.backward(loss)
  File "/root/anaconda3/envs/chatglm3-demo/lib/python3.10/site-packages/accelerate/accelerator.py", line 1989, in backward
    loss.backward(**kwargs)
  File "/root/anaconda3/envs/chatglm3-demo/lib/python3.10/site-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/root/anaconda3/envs/chatglm3-demo/lib/python3.10/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 508.00 MiB. GPU 1 has a total capacty of 14.62 GiB of which 295.38 MiB is free. Including non-PyTorch memory, this process has 14.32 GiB memory in use. Of the allocated memory 13.20 GiB is allocated by PyTorch, and 350.86 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
  0%|          | 0/3000 [00:02<?, ?it/s]
[2023-11-22 16:24:40,417] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 5055 closing signal SIGTERM
[2023-11-22 16:24:40,631] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 5054) of binary: /root/anaconda3/envs/chatglm3-demo/bin/python
Traceback (most recent call last):
  File "/root/anaconda3/envs/chatglm3-demo/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/root/anaconda3/envs/chatglm3-demo/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/root/anaconda3/envs/chatglm3-demo/lib/python3.10/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/root/anaconda3/envs/chatglm3-demo/lib/python3.10/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/root/anaconda3/envs/chatglm3-demo/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/anaconda3/envs/chatglm3-demo/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
finetune.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-11-22_16:24:40
  host      : localhost.localdomain
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 5054)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

### Expected behavior / 期待表现

不知根据官网的参数需要多少显存可以进行微调，或者说我可以尝试调整哪些参数来调整，以此可以运行微调脚本

**Comment by gaizi001** [comment]
或者说最低需要多少显存可以进行微调啊？

**Comment by zRzRzRzRzRzRzR** [comment]
官网的参数是基于A100的，FP16的话T4你调不了应该，载入模型就饱和了？

**Comment by gaizi001** [comment]
@zRzRzRzRzRzRzR 是的，加载模型就gg了，那最低多少显存可以微调，我是两张T4的提示显存不够

**Comment by zRzRzRzRzRzRzR** [comment]
你试试
···
PRE_SEQ_LEN=128
NUM_GPUS=1
MAX_SOURCE_LEN=1024
MAX_TARGET_LEN=128
DEV_BATCH_SIZE=1
GRAD_ACCUMULARION_STEPS=1
MAX_STEP=1000
SAVE_INTERVAL=500
···
在不行就没办法了

**Comment by whiteless9** [comment]
> 官网的参数是基于A100的，调试的设备是8卡A100，FP16的话T4卡只有16G显存这套参数你调不了应该，载入模型后就没有多少显存了

请问下p-tuning是不是对应的学习率需要按照显卡数以及batchsize倍率降低呢？

**Comment by zRzRzRzRzRzRzR** [comment]
> > 官网的参数是基于A100的，调试的设备是8卡A100，FP16的话T4卡只有16G显存这套参数你调不了应该，载入模型后就没有多少显存了
> 
> 请问下p-tuning是不是对应的学习率需要按照显卡数以及batchsize倍率降低呢？

在使用多个 GPU 或进行分布式训练时等多个因素导致增加批次大小batch size事，常见的做法是随着批次大小的增加而增加学习率。如果批次大小增加了 N 倍，那么学习率也增加 N 倍。

**Comment by zRzRzRzRzRzRzR** [comment]
更多微调问题可以在 #253 中提出，本issue关闭，感谢支持
