### ISSUE TITLE
多GPU怎么推理？怎么设置在langchain demo中

### ISSUE THREAD

**Issue by ZhuJD-China** [THUDM/ChatGLM3#409]
### System Info / 系統信息

zjd@LeaperAi191:~/ChatGLM3/langchain_demo$ python3 main.py 
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:09<00:00,  1.33s/it]
Traceback (most recent call last):
  File "/4T-1/zjd/ChatGLM3/langchain_demo/main.py", line 35, in <module>
    llm.load_model(model_name_or_path=MODEL_PATH, num_gpus=2)
  File "/4T-1/zjd/ChatGLM3/langchain_demo/ChatGLM3.py", line 53, in load_model
    self.model = DataParallel(model, device_ids=list(range(num_gpus))).cuda()
  File "/4T-1/zjd/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 918, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/4T-1/zjd/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/4T-1/zjd/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/4T-1/zjd/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  [Previous line repeated 4 more times]
  File "/4T-1/zjd/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 833, in _apply
    param_applied = fn(param)
  File "/4T-1/zjd/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 918, in <lambda>
    return self._apply(lambda t: t.cuda(device))
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 108.00 MiB. GPU 0 has a total capacty of 7.79 GiB of which 49.38 MiB is free. Including non-PyTorch memory, this process has 7.74 GiB memory in use. Of the allocated memory 7.63 GiB is allocated by PyTorch, and 1.54 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

### Who can help? / 谁可以帮助到您？

inetune_demo: @Btlmd
langchain_demo: @yincf
composite_demo: @abmfy

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

inetune_demo: @Btlmd
langchain_demo: @yincf
composite_demo: @abmfy

### Expected behavior / 期待表现

give code

**Comment by zRzRzRzRzRzRzR** [comment]
多GPU推理有bug，请查看是否在 #310 中复现，该issue重复
