### ISSUE TITLE
在个人服务器的管理节点部署后，调用计算节点无法运行

### ISSUE THREAD

**Issue by liufu2019** [THUDM/ChatGLM3#433]
### System Info / 系統信息

管理节点完美运行，无软硬件问题。

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

计算节点运行时：
2023-11-24 11:32:04,435 - modelscope - INFO - PyTorch version 2.1.1 Found.
2023-11-24 11:32:04,436 - modelscope - INFO - Loading ast index from .cache/modelscope/ast_indexer
2023-11-24 11:32:05,232 - modelscope - INFO - Loading done! Current index file version is 1.9.5, with md5 a133871484718e020166e5ebbba22f38 and a total number of 945 components indexed
Traceback (most recent call last):
  File "/Anaconda3-2023.09-0-Linux-x86_64/lib/python3.11/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Anaconda3-2023.09-0-Linux-x86_64/lib/python3.11/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Anaconda3-2023.09-0-Linux-x86_64/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -2] Name or service not known

### Expected behavior / 期待表现

管理节点部署后，是否可以迁移至计算节点运行

**Comment by zRzRzRzRzRzRzR** [comment]
没看懂你的意思，正常来说，模型部署在计算服务器，前台服务器只是管理API，那么请求的计算服务器用API请求模型就行了，你在官方的哪个代码遇到了这个错误？
