### ISSUE TITLE
使用finetune_basemodel_demo/scripts/finetune_lora.sh微调报错

### ISSUE THREAD

**Issue by meimoheng** [THUDM/ChatGLM3#454]
### System Info / 系統信息

python==3.8.10
torch==2.0.0+cu117
cuda==11.7
GPU==4*3090

### Who can help? / 谁可以帮助到您？

@Btlmd

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### 0.使用脚本如下,只修改了路径
'''
#! /usr/bin/env bash

set -ex

LR=1e-4
NUM_GPUS=4
LORA_RANK=8
LORA_ALPHA=32
LORA_DROUPOUT=0.1

MAX_SOURCE_LEN=512
MAX_TARGET_LEN=128
DEV_BATCH_SIZE=1
GRAD_ACCUMULARION_STEPS=1
MAX_STEP=1000
SAVE_INTERVAL=1000
MAX_SEQ_LEN=512

RUN_NAME=text
BASE_MODEL_PATH=/root/autodl-tmp/chatglm3-6b-base
DATASET_PATH=/root/pretrain.jsonl
DATESTR=`date +%Y%m%d-%H%M%S`
OUTPUT_DIR=/root/autodl-tmp/output/${RUN_NAME}-${DATESTR}-${LR}
MASTER_PORT=$(shuf -n 1 -i 10000-65535)

mkdir -p $OUTPUT_DIR

torchrun --standalone --nnodes=1 --nproc_per_node=$NUM_GPUS /root/lora/finetune_basemodel_demo/finetune.py \
    --train_format input-output \
    --train_file $DATASET_PATH \
    --lora_rank $LORA_RANK \
    --lora_alpha $LORA_ALPHA \
    --lora_dropout $LORA_DROUPOUT \
    --max_seq_length $MAX_SEQ_LEN \
    --preprocessing_num_workers 1 \
    --model_name_or_path $BASE_MODEL_PATH \
    --output_dir $OUTPUT_DIR \
    --per_device_train_batch_size $DEV_BATCH_SIZE \
    --gradient_accumulation_steps $GRAD_ACCUMULARION_STEPS \
    --max_steps $MAX_STEP \
    --logging_steps 10 \
    --save_steps $SAVE_INTERVAL \
    --learning_rate $LR  2>&1 | tee ${OUTPUT_DIR}/train.log
'''
1.修改脚本路径直接运行脚本，报错‘TypeError: string indices must be integers’
'''
Traceback (most recent call last):
  File "/root/lora/finetune_basemodel_demo/finetune.py", line 165, in <module>
    main()
  File "/root/lora/finetune_basemodel_demo/finetune.py", line 116, in main
    sanity_check(train_dataset[0]['input_ids'], train_dataset[0]['labels'], tokenizer)
  File "/root/lora/finetune_basemodel_demo/preprocess_utils.py", line 35, in __getitem__
    a_ids = self.tokenizer.encode(text=data_item['context'], add_special_tokens=True, truncation=True,
TypeError: string indices must be integers
Train dataset size: 63747
Traceback (most recent call last):
  File "/root/lora/finetune_basemodel_demo/finetune.py", line 165, in <module>
    main()
  File "/root/lora/finetune_basemodel_demo/finetune.py", line 116, in main
    sanity_check(train_dataset[0]['input_ids'], train_dataset[0]['labels'], tokenizer)
  File "/root/lora/finetune_basemodel_demo/preprocess_utils.py", line 35, in __getitem__
    a_ids = self.tokenizer.encode(text=data_item['context'], add_special_tokens=True, truncation=True,
TypeError: string indices must be integers
'''
### 3.出现新错误
'''
raceback (most recent call last):
  File "/root/lora/finetune_basemodel_demo/finetune.py", line 165, in <module>
    main()
  File "/root/lora/finetune_basemodel_demo/finetune.py", line 159, in main
    trainer.train()
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/trainer.py", line 1645, in train
    return inner_training_loop(
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/trainer.py", line 1938, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/trainer.py", line 2759, in training_step
Traceback (most recent call last):
    loss = self.compute_loss(model, inputs)
  File "/root/lora/finetune_basemodel_demo/trainer.py", line 36, in compute_loss
  File "/root/lora/finetune_basemodel_demo/finetune.py", line 165, in <module>
    return model(**inputs).loss
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    main()
  File "/root/lora/finetune_basemodel_demo/finetune.py", line 159, in main
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1156, in forward
    trainer.train()
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/trainer.py", line 1645, in train
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1110, in _run_ddp_forward
    return inner_training_loop(
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/trainer.py", line 1938, in _inner_training_loop
    return module_to_run(*inputs[0], **kwargs[0])  # type: ignore[index]
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/peft/peft_model.py", line 918, in forward
    tr_loss_step = self.training_step(model, inputs)
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/trainer.py", line 2759, in training_step
    return self.base_model(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/peft/tuners/tuners_utils.py", line 94, in forward
    return self.model.forward(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm3-6b-base/modeling_chatglm.py", line 938, in forward
    loss = self.compute_loss(model, inputs)
  File "/root/lora/finetune_basemodel_demo/trainer.py", line 36, in compute_loss
    return model(**inputs).loss
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    transformer_outputs = self.transformer(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm3-6b-base/modeling_chatglm.py", line 831, in forward
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1156, in forward
    hidden_states, presents, all_hidden_states, all_self_attentions = self.encoder(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1110, in _run_ddp_forward
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm3-6b-base/modeling_chatglm.py", line 641, in forward
    return module_to_run(*inputs[0], **kwargs[0])  # type: ignore[index]
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    layer_ret = layer(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/peft/peft_model.py", line 918, in forward
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm3-6b-base/modeling_chatglm.py", line 545, in forward
    attention_output, kv_cache = self.self_attention(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return self.base_model(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm3-6b-base/modeling_chatglm.py", line 377, in forward
        return forward_call(*args, **kwargs)mixed_x_layer = self.query_key_value(hidden_states)

  File "/root/miniconda3/lib/python3.8/site-packages/peft/tuners/tuners_utils.py", line 94, in forward
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return self.model.forward(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm3-6b-base/modeling_chatglm.py", line 938, in forward
        return forward_call(*args, **kwargs)transformer_outputs = self.transformer(

  File "/root/miniconda3/lib/python3.8/site-packages/peft/tuners/lora.py", line 902, in forward
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    result = F.linear(x, transpose(self.weight, self.fan_in_fan_out), bias=self.bias)
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm3-6b-base/modeling_chatglm.py", line 831, in forward
    hidden_states, presents, all_hidden_states, all_self_attentions = self.encoder(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm3-6b-base/modeling_chatglm.py", line 641, in forward
    layer_ret = layer(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm3-6b-base/modeling_chatglm.py", line 545, in forward
    attention_output, kv_cache = self.self_attention(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm3-6b-base/modeling_chatglm.py", line 377, in forward
    mixed_x_layer = self.query_key_value(hidden_states)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/peft/tuners/lora.py", line 902, in forward
    result = F.linear(x, transpose(self.weight, self.fan_in_fan_out), bias=self.bias)
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`
'''

### Expected behavior / 期待表现

google了一下，说是网络层与层之间的参数不匹配、数据维度、embeding之类的问题

**Comment by meimoheng** [comment]
还是说升级到python3.10就不会出现错误了

**Comment by zRzRzRzRzRzRzR** [comment]
在Ubuntu 22.04 python3.10.12 cuda 12.3 pytorch 2.1写的这个脚本，在这个环境下没有出现问题，我后续观察一下

**Comment by zRzRzRzRzRzRzR** [comment]
在前两天我提供的版本上没有遇到相似问题，升级python应该能解决

**Comment by meimoheng** [comment]
十分感谢，我会继续做尝试

**Comment by Xuanaxx** [comment]
我是python3.10的版本，出现了同样的问题，Google了一下，有说是你提的那个原因；有说是显存不够的问题（检查过后24G的3090显存是足够的）；有说是无法同时运行多个pytorch程序。我将NUM_GPUS改为1后跑通了，但是loss又不太正常了...

**Comment by meimoheng** [comment]
怀疑是cuda版本的问题，我cuda版本11.7，博主12.3，在python pytorch和博主版本一致的情况下报错
