### ISSUE TITLE
你好，我在使用PEFT的ptuning微调ChatGLM3的时候遇到数据加载不进去的问题

### ISSUE THREAD

**Issue by Hongru0306** [THUDM/ChatGLM3#460]
### System Info / 系統信息

torch--1.13.1+cu116
peft--0.5.0
transformers--4.35.2
python--3.9                

### Who can help? / 谁可以帮助到您？

@Btlmd 
是在PEFT微调过程中出现的问题

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

我通过如下设置的我的代码:
```
import torch
from datasets import Dataset
from transformers import AutoTokenizer, AutoModelForCausalLM, DataCollatorForSeq2Seq, TrainingArguments, Trainer
import pandas as pd
from peft import TaskType, get_peft_model, LoraConfig, PromptEncoderConfig, PromptEncoderReparameterizationType


# 数据处理流程,参考GLM3仓库:https://github.com/THUDM/ChatGLM3/blob/main/finetune_chatmodel_demo/preprocess_utils
def process_func(example):
    MAX_LENGTH = 512
    input_ids, labels = [], []
    instruction = tokenizer.encode(text="\n".join(["<|system|>", "现在你要扮演皇帝身边的女人--甄嬛", "<|user|>", 
                                    example["instruction"] + example["input"] + "<|assistant|>"]).strip() + "\n",
                                    add_special_tokens=True, truncation=True, max_length=MAX_LENGTH)
    response = tokenizer.encode(text=example["output"], add_special_tokens=False, truncation=True, max_length=MAX_LENGTH)
    input_ids = instruction + response + [tokenizer.eos_token_id]
    labels = [tokenizer.pad_token_id] * len(instruction) + response + [tokenizer.eos_token_id]
    pad_len = MAX_LENGTH - len(input_ids)
    # print()
    input_ids += [tokenizer.pad_token_id] * pad_len
    labels += [tokenizer.pad_token_id] * pad_len
    labels = [(l if l != tokenizer.pad_token_id else -100) for l in labels]

    return {
        "input_ids": input_ids,
        "labels": labels
    }

args = TrainingArguments(
    output_dir="./output/ChatGLM",
    per_device_train_batch_size=1,
    gradient_accumulation_steps=8,
    logging_steps=20,
    num_train_epochs=1
)
    if "__main__" == __name__:
    # 将JSON文件转换为CSV文件,处理数据集
    df = pd.read_json('./huanhuan.json')
    ds = Dataset.from_pandas(df)
    # 加载tokenizer
    tokenizer = AutoTokenizer.from_pretrained("./model/chatglm3-6b", trust_remote_code=True)
    # 将数据集变化为token形式
    tokenized_ds = ds.map(process_func, remove_columns=ds.column_names)

    # 创建模型
    model = AutoModelForCausalLM.from_pretrained("./model/chatglm3-6b", trust_remote_code=True, low_cpu_mem_usage=True)

    # # 创建loRA参数
    # config = LoraConfig(task_type=TaskType.CAUSAL_LM, target_modules={"query_key_value"}, r=8, lora_alpha=32)

    # 创建Ptuning参数
    # P-tuning
    config = PromptEncoderConfig(task_type=TaskType.CAUSAL_LM, num_virtual_tokens=10,
                                encoder_reparameterization_type=PromptEncoderReparameterizationType.MLP,
                                encoder_dropout=0, encoder_num_layers=5, encoder_hidden_size=1024)


    # 模型合并
    model = get_peft_model(model, config)

    # 指定GLM的Data collator
    data_collator = DataCollatorForSeq2Seq(
        tokenizer,
        model=model,
        label_pad_token_id=-100,
        pad_to_multiple_of=None,
        padding=False
    )

    # 指定训练参数。
    trainer = Trainer(
        model=model,
        args=args,
        train_dataset=tokenized_ds,
        data_collator=data_collator,
    )

    # 开始训练
    trainer.train()
```
上面的代码LoRa可以进行微调，但是Ptuning不可以，会报这样的错:  

```
AttributeError: Caught AttributeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "./anaconda3/envs/llm/lib/python3.9/site-packages/torch/nn/parallel/parallel_apply.py", line 64, in _worker
    output = module(*input, **kwargs)
  File "./anaconda3/envs/llm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "./anaconda3/envs/llm/lib/python3.9/site-packages/peft/peft_model.py", line 966, in forward
    return self.base_model(inputs_embeds=inputs_embeds, **kwargs)
  File "./anaconda3/envs/llm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File ".cache/huggingface/modules/transformers_modules/chatglm3-6b/modeling_chatglm.py", line 938, in forward
    transformer_outputs = self.transformer(
  File "./anaconda3/envs/llm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "./chatglm3-6b/modeling_chatglm.py", line 805, in forward
    batch_size, seq_length = input_ids.shape
AttributeError: 'NoneType' object has no attribute 'shape'
```

- 我尝试使用`hard prompt`，但还是报这个错...  
- 我又在`PEFT`的`Embedding`处打断点,但是运行中直接跳过了`PEFT`处，直接到达`trainer`的报错点，报相同的错。  
- **同样的代码我在`Qwen`,`Bloom`等模型进行的`ptuning`都可以训练,并且上述代码我用LoRa也可以正常训练，实在不知道问题出在哪，想向您求助!**

### Expected behavior / 期待表现

期待您能帮我解决困惑已久的问题，真的非常需要您的帮助！

**Comment by zRzRzRzRzRzRzR** [comment]
这类问题可以在讨论区中提出，目前我们暂时没有处理这个问题，不过，请注意，请检查你的微调格式是否为合理的，会不会影响到防注入等内容
