### ISSUE TITLE
requests.exceptions.ConnectionError on openai_api_demo/openai_api_request.py

### ISSUE THREAD

**Issue by henrywang0314** [THUDM/ChatGLM3#463]
### System Info / 系統信息

requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000249ABC12530>: Failed to establish a new connection: [WinError 10061] 無法連線，因為目標電腦拒絕連線。'))

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

cd openai_api_demo
python openai_api_request.py

### Expected behavior / 期待表现

全程依照指示操作，不知道出了什麼問題。

**Comment by henrywang0314** [comment]
after changing the port number
There is a new error:
PS C:\Users\vic\Desktop\chatGLM> & c:/Users/vic/Desktop/chatGLM/.conda/python.exe c:/Users/vic/Desktop/chatGLM/ChatGLM3/openai_api_demo/openai_api_request.py
Traceback (most recent call last):
  File "C:\Users\vic\Desktop\chatGLM\.conda\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\vic\Desktop\chatGLM\.conda\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\vic\Desktop\chatGLM\.conda\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\vic\Desktop\chatGLM\.conda\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\vic\Desktop\chatGLM\ChatGLM3\openai_api_demo\openai_api_request.py", line 113, in <module>
    function_chat(use_stream=False)
  File "c:\Users\vic\Desktop\chatGLM\ChatGLM3\openai_api_demo\openai_api_request.py", line 94, in function_chat
    create_chat_completion("chatglm3-6b", messages=chat_messages, functions=functions, use_stream=use_stream)
  File "c:\Users\vic\Desktop\chatGLM\ChatGLM3\openai_api_demo\openai_api_request.py", line 40, in create_chat_completion
    decoded_line = response.json()
  File "C:\Users\vic\Desktop\chatGLM\.conda\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Then I print out the response in this line:
response = requests.post(f"{base_url}/v1/chat/completions", json=data, stream=use_stream)
print("response")
<Response [200]>

**Comment by zRzRzRzRzRzRzR** [comment]
用的是request_api.py来请求的吗

**Comment by zRzRzRzRzRzRzR** [comment]
更新到我们的最新代码后，如果还有相似问题，方便给出更多的复现细节，我们今天的更新修了一下Function，可能是传的时候出现问题？
也可以看看[urllib3 issue](https://github.com/urllib3/urllib3/issues/1653)能不能帮助到你

**Comment by henrywang0314** [comment]
當初應該是openai_api.py沒有執行到
現在已經沒有問題了
謝謝你
