### ISSUE TITLE
运行demo时报错

### ISSUE THREAD

**Issue by Funer100** [THUDM/ChatGLM3#469]
### System Info / 系統信息

OSError: Unable to load weights from pytorch checkpoint file for '/mnt/workspace/ChatGLM3/model/pytorch_model-00001-of-00007.bin' at '/mnt/workspace/ChatGLM3/model/pytorch_model-00001-of-00007.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1.在服务器上配置环境git clone modelscope上的代码
2.在目录下新建model文件夹，将从modelscope上下载到本地的模型上传至服务器
3.进入basic_demo，输入export MODEL_PATH=/mnt/workspace/ChatGLM3/model/
4.通过python web_demo.py 运行demo时有报错
UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 11080). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
2023-11-27 23:00:01.570 
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run web_demo2.py [ARGUMENTS]
Loading checkpoint shards:   0%|                                                                                                                                       | 0/7 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/opt/conda/envs/chatglm3-demo/lib/python3.10/site-packages/streamlit/runtime/caching/cache_utils.py", line 264, in _get_or_create_cached_value
    cached_result = cache.read_result(value_key)
  File "/opt/conda/envs/chatglm3-demo/lib/python3.10/site-packages/streamlit/runtime/caching/cache_resource_api.py", line 500, in read_result
    raise CacheKeyNotFoundError()
streamlit.runtime.caching.cache_errors.CacheKeyNotFoundError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/chatglm3-demo/lib/python3.10/site-packages/streamlit/runtime/caching/cache_utils.py", line 312, in _handle_cache_miss
    cached_result = cache.read_result(value_key)
  File "/opt/conda/envs/chatglm3-demo/lib/python3.10/site-packages/streamlit/runtime/caching/cache_resource_api.py", line 500, in read_result
    raise CacheKeyNotFoundError()
streamlit.runtime.caching.cache_errors.CacheKeyNotFoundError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/chatglm3-demo/lib/python3.10/site-packages/transformers/modeling_utils.py", line 484, in load_state_dict
    return torch.load(checkpoint_file, map_location=map_location)
  File "/opt/conda/envs/chatglm3-demo/lib/python3.10/site-packages/torch/serialization.py", line 993, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/opt/conda/envs/chatglm3-demo/lib/python3.10/site-packages/torch/serialization.py", line 447, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/chatglm3-demo/lib/python3.10/site-packages/transformers/modeling_utils.py", line 488, in load_state_dict
    if f.read(7) == "version":
  File "/opt/conda/envs/chatglm3-demo/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 128: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/workspace/ChatGLM3/basic_demo/web_demo2.py", line 29, in <module>
    tokenizer, model = get_model()
  File "/opt/conda/envs/chatglm3-demo/lib/python3.10/site-packages/streamlit/runtime/caching/cache_utils.py", line 212, in wrapper
    return cached_func(*args, **kwargs)
  File "/opt/conda/envs/chatglm3-demo/lib/python3.10/site-packages/streamlit/runtime/caching/cache_utils.py", line 241, in __call__
    return self._get_or_create_cached_value(args, kwargs)
  File "/opt/conda/envs/chatglm3-demo/lib/python3.10/site-packages/streamlit/runtime/caching/cache_utils.py", line 267, in _get_or_create_cached_value
    return self._handle_cache_miss(cache, value_key, func_args, func_kwargs)
  File "/opt/conda/envs/chatglm3-demo/lib/python3.10/site-packages/streamlit/runtime/caching/cache_utils.py", line 321, in _handle_cache_miss
    computed_value = self._info.func(*func_args, **func_kwargs)
  File "/mnt/workspace/ChatGLM3/basic_demo/web_demo2.py", line 22, in get_model
    model = AutoModel.from_pretrained(MODEL_PATH, trust_remote_code=True).float().to(DEVICE).eval()
  File "/opt/conda/envs/chatglm3-demo/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 561, in from_pretrained
    return model_class.from_pretrained(
  File "/opt/conda/envs/chatglm3-demo/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3480, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/opt/conda/envs/chatglm3-demo/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3856, in _load_pretrained_model
    state_dict = load_state_dict(shard_file)
  File "/opt/conda/envs/chatglm3-demo/lib/python3.10/site-packages/transformers/modeling_utils.py", line 500, in load_state_dict
    raise OSError(
OSError: Unable to load weights from pytorch checkpoint file for '/mnt/workspace/ChatGLM3/model/pytorch_model-00001-of-00007.bin' at '/mnt/workspace/ChatGLM3/model/pytorch_model-00001-of-00007.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.

### Expected behavior / 期待表现

运行web等demo时遇到的问题，以为文件损坏，所以重新下载到本地再上传到服务器上运行还是报错，请告诉我有没有什么解决的方法。

**Comment by zRzRzRzRzRzRzR** [comment]
OSError: Unable to load weights from pytorch checkpoint file for '/mnt/workspace/ChatGLM3/model/pytorch_model-00001-of-00007.bin' at '/mnt/workspace/ChatGLM3/model/pytorch_model-00001-of-00007.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.
Expected behavior 


还是文件损坏，这都没找到文件啊
