### ISSUE TITLE
使用 ToolAlpaca 数据集进行微调 报错

### ISSUE THREAD

**Issue by linfx** [THUDM/ChatGLM3#497]
### 系统信息
python3.8
transformer 4.30.2
PyTorch 2.0.1
ubuntu20.04
Cuda 11.8

按着文档执行:
`./scripts/finetune_pt_multiturn.sh  # P-Tuning v2 微调`

```python
root@dsw-31859-5ff67794f8-n8xhq:/mnt/workspace/ChatGLM3/finetune_chatmodel_demo# ./scripts/finetune_pt_multiturn.sh
+ PRE_SEQ_LEN=128
+ LR=2e-2
+ NUM_GPUS=1
+ MAX_SEQ_LEN=2048
+ DEV_BATCH_SIZE=1
+ GRAD_ACCUMULARION_STEPS=16
+ MAX_STEP=60
+ SAVE_INTERVAL=20
++ date +%Y%m%d-%H%M%S
+ DATESTR=20231204-085818
+ RUN_NAME=tool_alpaca_pt
+ BASE_MODEL_PATH=/mnt/workspace/models/chatglm3-6b
+ DATASET_PATH=formatted_data/tool_alpaca.jsonl
+ OUTPUT_DIR=output/tool_alpaca_pt-20231204-085818-128-2e-2
+ mkdir -p output/tool_alpaca_pt-20231204-085818-128-2e-2
+ torchrun --standalone --nnodes=1 --nproc_per_node=1 finetune.py --train_format multi-turn --train_file formatted_data/tool_alpaca.jsonl --max_seq_length 2048 --preprocessing_num_workers 1 --model_name_or_path /mnt/workspace/models/chatglm3-6b --output_dir output/tool_alpaca_pt-20231204-085818-128-2e-2 --per_device_train_batch_size 1 --gradient_accumulation_steps 16 --max_steps 60 --logging_steps 1 --save_steps 20 --learning_rate 2e-2 --use_mps_device 1 --pre_seq_len 128
+ tee output/tool_alpaca_pt-20231204-085818-128-2e-2/train.log
master_addr is only used for static rdzv_backend and when rdzv_endpoint is not specified.
2023-12-04 08:58:24.253850: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-12-04 08:58:24.695582: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-12-04 08:58:25.865052: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
12/04/2023 08:58:29 - WARNING - __main__ - Process rank: 0, device: cuda:0, n_gpu: 1distributed training: True, 16-bits training: False
12/04/2023 08:58:29 - INFO - __main__ - Training/evaluation parameters Seq2SeqTrainingArguments(
_n_gpu=1,
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
bf16=False,
bf16_full_eval=False,
data_seed=None,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_pin_memory=True,
ddp_backend=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=False,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_steps=None,
evaluation_strategy=no,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'fsdp_min_num_params': 0, 'xla': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
generation_config=None,
generation_max_length=None,
generation_num_beams=None,
gradient_accumulation_steps=16,
gradient_checkpointing=False,
greater_is_better=None,
group_by_length=False,
half_precision_backend=auto,
hub_model_id=None,
hub_private_repo=False,
hub_strategy=every_save,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_inputs_for_metrics=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=0.02,
length_column_name=length,
load_best_model_at_end=False,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=output/tool_alpaca_pt-20231204-085818-128-2e-2/runs/Dec04_08-58-29_dsw-31859-5ff67794f8-n8xhq,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=1.0,
logging_strategy=steps,
lr_scheduler_type=linear,
max_grad_norm=1.0,
max_steps=60,
metric_for_best_model=None,
mp_parameters=,
no_cuda=False,
num_train_epochs=3.0,
optim=adamw_hf,
optim_args=None,
output_dir=output/tool_alpaca_pt-20231204-085818-128-2e-2,
overwrite_output_dir=False,
past_index=-1,
per_device_eval_batch_size=8,
per_device_train_batch_size=1,
predict_with_generate=False,
prediction_loss_only=False,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=['tensorboard'],
resume_from_checkpoint=None,
run_name=output/tool_alpaca_pt-20231204-085818-128-2e-2,
save_on_each_node=False,
save_safetensors=False,
save_steps=20,
save_strategy=steps,
save_total_limit=None,
seed=42,
sharded_ddp=[],
skip_memory_metrics=True,
sortish_sampler=False,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
use_ipex=False,
use_legacy_prediction_loop=False,
use_mps_device=True,
warmup_ratio=0.0,
warmup_steps=0,
weight_decay=0.0,
xpu_backend=None,
)
[INFO|configuration_utils.py:667] 2023-12-04 08:58:29,085 >> loading configuration file /mnt/workspace/models/chatglm3-6b/config.json
[INFO|configuration_utils.py:667] 2023-12-04 08:58:29,087 >> loading configuration file /mnt/workspace/models/chatglm3-6b/config.json
[INFO|configuration_utils.py:725] 2023-12-04 08:58:29,088 >> Model config ChatGLMConfig {
  "_name_or_path": "/mnt/workspace/models/chatglm3-6b",
  "add_bias_linear": false,
  "add_qkv_bias": true,
  "apply_query_key_layer_scaling": true,
  "apply_residual_connection_post_layernorm": false,
  "architectures": [
    "ChatGLMModel"
  ],
  "attention_dropout": 0.0,
  "attention_softmax_in_fp32": true,
  "auto_map": {
    "AutoConfig": "configuration_chatglm.ChatGLMConfig",
    "AutoModel": "modeling_chatglm.ChatGLMForConditionalGeneration",
    "AutoModelForCausalLM": "modeling_chatglm.ChatGLMForConditionalGeneration",
    "AutoModelForSeq2SeqLM": "modeling_chatglm.ChatGLMForConditionalGeneration",
    "AutoModelForSequenceClassification": "modeling_chatglm.ChatGLMForSequenceClassification"
  },
  "bias_dropout_fusion": true,
  "classifier_dropout": null,
  "eos_token_id": 2,
  "ffn_hidden_size": 13696,
  "fp32_residual_connection": false,
  "hidden_dropout": 0.0,
  "hidden_size": 4096,
  "kv_channels": 128,
  "layernorm_epsilon": 1e-05,
  "model_type": "chatglm",
  "multi_query_attention": true,
  "multi_query_group_num": 2,
  "num_attention_heads": 32,
  "num_layers": 28,
  "original_rope": true,
  "pad_token_id": 0,
  "padded_vocab_size": 65024,
  "post_layer_norm": true,
  "pre_seq_len": null,
  "prefix_projection": false,
  "quantization_bit": 0,
  "rmsnorm": true,
  "seq_length": 8192,
  "tie_word_embeddings": false,
  "torch_dtype": "float16",
  "transformers_version": "4.30.2",
  "use_cache": true,
  "vocab_size": 65024
}

[INFO|tokenization_utils_base.py:1821] 2023-12-04 08:58:29,091 >> loading file tokenizer.model
[INFO|tokenization_utils_base.py:1821] 2023-12-04 08:58:29,091 >> loading file added_tokens.json
[INFO|tokenization_utils_base.py:1821] 2023-12-04 08:58:29,091 >> loading file special_tokens_map.json
[INFO|tokenization_utils_base.py:1821] 2023-12-04 08:58:29,091 >> loading file tokenizer_config.json
[INFO|modeling_utils.py:2575] 2023-12-04 08:58:29,494 >> loading weights file /mnt/workspace/models/chatglm3-6b/pytorch_model.bin.index.json
[INFO|configuration_utils.py:577] 2023-12-04 08:58:29,495 >> Generate config GenerationConfig {
  "_from_model_config": true,
  "eos_token_id": 2,
  "pad_token_id": 0,
  "transformers_version": "4.30.2"
}

Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [01:09<00:00,  9.89s/it]
[INFO|modeling_utils.py:3295] 2023-12-04 08:59:38,870 >> All model checkpoint weights were used when initializing ChatGLMForConditionalGeneration.

[WARNING|modeling_utils.py:3297] 2023-12-04 08:59:38,870 >> Some weights of ChatGLMForConditionalGeneration were not initialized from the model checkpoint at /mnt/workspace/models/chatglm3-6b and are newly initialized: ['transformer.prefix_encoder.embedding.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
[INFO|modeling_utils.py:2927] 2023-12-04 08:59:38,872 >> Generation config file not found, using a generation config created from the model config.
Traceback (most recent call last):
  File "finetune.py", line 165, in <module>
    main()
  File "finetune.py", line 134, in main
    sanity_check(train_dataset[0]['input_ids'], train_dataset[0]['labels'], tokenizer)
  File "/mnt/workspace/ChatGLM3/finetune_chatmodel_demo/preprocess_utils.py", line 94, in __getitem__
    tokens, loss_masks = format_conversation(data_item, self.tokenizer, CONVERSATOIN_KEY, TOOL_DESC_KEY)
  File "/mnt/workspace/ChatGLM3/finetune_chatmodel_demo/preprocess_utils.py", line 52, in format_conversation
    value = FUNCTION_CALL_PREFIX + format_function_call(FUNCTION_CALL_NAME, conv["parameters"]) + FUNCTION_CALL_POSTFIX
  File "/mnt/workspace/ChatGLM3/finetune_chatmodel_demo/preprocess_utils.py", line 24, in format_function_call
    return astunparse.unparse(func_call).strip()
  File "/opt/conda/lib/python3.8/site-packages/astunparse/__init__.py", line 13, in unparse
    Unparser(tree, file=v)
  File "/opt/conda/lib/python3.8/site-packages/astunparse/unparser.py", line 38, in __init__
    self.dispatch(tree)
  File "/opt/conda/lib/python3.8/site-packages/astunparse/unparser.py", line 66, in dispatch
    meth(tree)
  File "/opt/conda/lib/python3.8/site-packages/astunparse/unparser.py", line 727, in _Call
    self.dispatch(e)
  File "/opt/conda/lib/python3.8/site-packages/astunparse/unparser.py", line 66, in dispatch
    meth(tree)
  File "/opt/conda/lib/python3.8/site-packages/astunparse/unparser.py", line 844, in _keyword
    self.dispatch(t.value)
  File "/opt/conda/lib/python3.8/site-packages/astunparse/unparser.py", line 66, in dispatch
    meth(tree)
  File "/opt/conda/lib/python3.8/site-packages/astunparse/unparser.py", line 551, in _Constant
    if t.kind == "u":
AttributeError: 'Constant' object has no attribute 'kind'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 295) of binary: /opt/conda/bin/python
Traceback (most recent call last):
  File "/opt/conda/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.0.1+cu118', 'console_scripts', 'torchrun')())
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
finetune.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-12-04_08:59:41
  host      : dsw-31859-5ff67794f8-n8xhq
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 295)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

输入输出格式的微调是正常的， 就是多轮对话微调会报错。 是什么问题导至呢？

**Comment by linfx** [comment]
root@dsw-31859-6d67b67bb9-t9tph:/mnt/workspace/ChatGLM3/finetune_chatmodel_demo# python
Python 3.8.16 (default, Jun 12 2023, 18:09:05) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> print(torch.__version__)
2.0.1+cu118
>>>

**Comment by zRzRzRzRzRzRzR** [comment]
python3直接运行也报错吗，确定一下现在是在什么情况下会报你一开始提的那个错误

**Comment by zhangyin-github** [comment]
同样的问题

环境：
Apple M2
24GB
Sonoma 14.1.2
Python 3.8

已经正常运行ChatGLM,能够正常对话

accelerate==0.24.1
aiofiles==23.2.1
altair==5.2.0
annotated-types==0.6.0
anyio==3.7.1
astunparse==1.6.3
attrs==23.1.0
backports.zoneinfo==0.2.1
blinker==1.7.0
cachetools==5.3.2
certifi==2023.11.17
charset-normalizer==3.3.2
click==8.1.7
contourpy==1.1.1
cpm-kernels==1.0.11
cycler==0.12.1
deepspeed==0.12.3
exceptiongroup==1.2.0
fastapi==0.104.1
ffmpy==0.3.1
filelock==3.13.1
fonttools==4.45.1
fsspec==2023.10.0
gitdb==4.0.11
GitPython==3.1.40
gradio==3.50.2
gradio_client==0.6.1
h11==0.14.0
hjson==3.1.0
httpcore==1.0.2
httpx==0.25.2
huggingface-hub==0.19.4
idna==3.6
importlib-metadata==6.8.0
importlib-resources==6.1.1
Jinja2==3.1.2
jsonschema==4.20.0
jsonschema-specifications==2023.11.2
kiwisolver==1.4.5
latex2mathml==3.76.0
loguru==0.7.2
markdown-it-py==3.0.0
MarkupSafe==2.1.3
matplotlib==3.7.4
mdurl==0.1.2
mpmath==1.3.0
networkx==3.1
ninja==1.11.1.1
numpy==1.24.4
orjson==3.9.10
packaging==23.2
pandas==2.0.3
Pillow==10.1.0
pkgutil_resolve_name==1.3.10
protobuf==4.25.1
psutil==5.9.6
py-cpuinfo==9.0.0
pyarrow==14.0.1
pydantic==2.5.2
pydantic_core==2.14.5
pydeck==0.8.1b0
pydub==0.25.1
Pygments==2.17.2
pynvml==11.5.0
pyparsing==3.1.1
python-dateutil==2.8.2
python-multipart==0.0.6
pytz==2023.3.post1
PyYAML==6.0.1
referencing==0.31.1
regex==2023.10.3
requests==2.31.0
rich==13.7.0
rpds-py==0.13.2
safetensors==0.4.1
semantic-version==2.10.0
sentencepiece==0.1.99
six==1.16.0
smmap==5.0.1
sniffio==1.3.0
sse-starlette==1.8.2
starlette==0.27.0
streamlit==1.29.0
sympy==1.12
tenacity==8.2.3
tokenizers==0.13.3
toml==0.10.2
toolz==0.12.0
torch==2.2.0.dev20231130
torchaudio==2.2.0.dev20231130
torchvision==0.17.0.dev20231130
tornado==6.4
tqdm==4.66.1
transformers==4.30.2
typing_extensions==4.9.0rc1
tzdata==2023.3
tzlocal==5.2
urllib3==2.1.0
uvicorn==0.24.0.post1
validators==0.22.0
websockets==11.0.3
zipp==3.17.0

会不会是什么包发布了新版本导致的？

**Comment by linfx** [comment]
> python3

怎么用 python3 运行，，跟 .sh 运行不是一样的吗？

**Comment by linfx** [comment]
> 不要torch.distributed启动

python finetune.py \
>     --train_format multi-turn \
>     --train_file $DATASET_PATH \
>     --max_seq_length $MAX_SEQ_LEN \
>     --preprocessing_num_workers 1 \
>     --model_name_or_path $BASE_MODEL_PATH \
>     --output_dir $OUTPUT_DIR \
>     --per_device_train_batch_size $DEV_BATCH_SIZE \
>     --gradient_accumulation_steps $GRAD_ACCUMULARION_STEPS \
>     --max_steps $MAX_STEP \
>     --logging_steps 1 \
>     --save_steps $SAVE_INTERVAL \
>     --learning_rate $LR \
>     --pre_seq_len $PRE_SEQ_LEN 2>&1 | tee ${OUTPUT_DIR}/train.log


还是报同样的错误

**Comment by zRzRzRzRzRzRzR** [comment]
```
Traceback (most recent call last):
  File "finetune.py", line 165, in <module>
    main()
  File "finetune.py", line 134, in main
    sanity_check(train_dataset[0]['input_ids'], train_dataset[0]['labels'], tokenizer)
  File "/mnt/workspace/ChatGLM3/finetune_chatmodel_demo/preprocess_utils.py", line 94, in __getitem__
    tokens, loss_masks = format_conversation(data_item, self.tokenizer, CONVERSATOIN_KEY, TOOL_DESC_KEY)
  File "/mnt/workspace/ChatGLM3/finetune_chatmodel_demo/preprocess_utils.py", line 52, in format_conversation
    value = FUNCTION_CALL_PREFIX + format_function_call(FUNCTION_CALL_NAME, conv["parameters"]) + FUNCTION_CALL_POSTFIX
  File "/mnt/workspace/ChatGLM3/finetune_chatmodel_demo/preprocess_utils.py", line 24, in format_function_call
    return astunparse.unparse(func_call).strip()
  File "/opt/conda/lib/python3.8/site-packages/astunparse/__init__.py", line 13, in unparse
    Unparser(tree, file=v)
  File "/opt/conda/lib/python3.8/site-packages/astunparse/unparser.py", line 38, in __init__
    self.dispatch(tree)
  File "/opt/conda/lib/python3.8/site-packages/astunparse/unparser.py", line 66, in dispatch
    meth(tree)
  File "/opt/conda/lib/python3.8/site-packages/astunparse/unparser.py", line 727, in _Call
    self.dispatch(e)
  File "/opt/conda/lib/python3.8/site-packages/astunparse/unparser.py", line 66, in dispatch
    meth(tree)
  File "/opt/conda/lib/python3.8/site-packages/astunparse/unparser.py", line 844, in _keyword
    self.dispatch(t.value)
  File "/opt/conda/lib/python3.8/site-packages/astunparse/unparser.py", line 66, in dispatch
    meth(tree)
  File "/opt/conda/lib/python3.8/site-packages/astunparse/unparser.py", line 551, in _Constant
    if t.kind == "u":
AttributeError: 'Constant' object has no attribute 'kind'
```
会不会是数据处理出现问题，在数据处理的地方debug一下，因为这好像还没开始训

**Comment by linfx** [comment]
应该是数据问题， 我换了份数据正常了

**Comment by zhangyin-github** [comment]
> 应该是数据问题， 我换了份数据正常了

能否问下换的哪个数据？是否使用同样的数据预处理程序呢？
