### ISSUE TITLE
输入输出格式微调-单机双卡3090

### ISSUE THREAD

**Issue by Eternal-Yan** [THUDM/ChatGLM3#536]
根据readme.md中./scripts/finetune_pt.sh  报错，有大佬教一下嘛
NotImplementedError: Using RTX 3090 or 4000 series doesn't support faster communication broadband via P2P or IB. Please set `NCCL_P2P_DISABLE="1"` and `NCCL_IB_DISABLE="1" or use `accelerate launch` which will do this automatically.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 415545) of binary: /home/dell/anaconda3/envs/ChatGLM3-main/bin/python3.10
Traceback (most recent call last):
  File "/home/dell/anaconda3/envs/ChatGLM3-main/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/dell/anaconda3/envs/ChatGLM3-main/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/dell/anaconda3/envs/ChatGLM3-main/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/dell/anaconda3/envs/ChatGLM3-main/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/dell/anaconda3/envs/ChatGLM3-main/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/dell/anaconda3/envs/ChatGLM3-main/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
finetune.py FAILED

**Comment by zRzRzRzRzRzRzR** [comment]
查看这里 (解决方案)[https://github.com/Lightning-AI/pytorch-lightning/issues/4420]

**Comment by qqzhao007** [comment]
也参考这篇blog
https://blog.csdn.net/weixin_44320558/article/details/134791740
