### ISSUE TITLE
基于ChatGLM2带的openai_api.py修改支持ChatGLM3

### ISSUE THREAD

**Issue by jonsen** [THUDM/ChatGLM3#55]
直接使用ChatGLM2带的openai_api.py跑ChatGLM3模型时遇到报错，研究了下代码修改了下，能跑起来了。

https://github.com/jonsen/ChatGLM3-OpenAI-API

**Comment by LouisHeck** [comment]
强！我来试试

**Comment by neocao123** [comment]
好像还是报错

**Comment by xinzhu666** [comment]
调用的时候出现以下报错。
python版本`3.10.12`，跑官方的`streamlit run web_demo2.py`可以跑。
```shell
Traceback (most recent call last):
  File "/miniconda_lib_path/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/miniconda_lib_path/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/miniconda_lib_path/python3.10/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/miniconda_lib_path/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/miniconda_lib_path/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/miniconda_lib_path/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/miniconda_lib_path/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/miniconda_lib_path/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/miniconda_lib_path/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/miniconda_lib_path/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/miniconda_lib_path/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/miniconda_lib_path/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/miniconda_lib_path/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/miniconda_lib_path/python3.10/site-packages/starlette/routing.py", line 69, in app
    await response(scope, receive, send)
  File "/miniconda_lib_path/python3.10/site-packages/sse_starlette/sse.py", line 233, in __call__
    async with anyio.create_task_group() as task_group:
  File "/miniconda_lib_path/python3.10/site-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "/miniconda_lib_path/python3.10/site-packages/sse_starlette/sse.py", line 236, in wrap
    await func()
  File "/miniconda_lib_path/python3.10/site-packages/sse_starlette/sse.py", line 221, in stream_response
    async for data in self.body_iterator:
  File "/code_path/ChatGLM3/openai_api.py", line 153, in predict
    yield "{}".format(chunk.model_dump_json(exclude_unset=True))
AttributeError: 'ChatCompletionResponse' object has no attribute 'model_dump_json'
```

**Comment by jonsen** [comment]
将文件中所有 model_dump_json 修改为json即可。

**Comment by yinjianjie** [comment]
用官方的openai_api.py跑 报错啊，则么修改啊
     await self.app(scope, receive, send)
  File "/opt/conda/lib/python3.8/site-packages/starlette/routing.py", line 69, in app
    await response(scope, receive, send)
  File "/opt/conda/lib/python3.8/site-packages/sse_starlette/sse.py", line 247, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "/opt/conda/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "/opt/conda/lib/python3.8/site-packages/sse_starlette/sse.py", line 236, in wrap
    await func()
  File "/opt/conda/lib/python3.8/site-packages/sse_starlette/sse.py", line 221, in stream_response
    async for data in self.body_iterator:
  File "openai_api.py", line 195, in predict
    for new_response in generate_stream_chatglm3(model, tokenizer, params):
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/mnt/workspace/ChatGLM3/utils.py", line 131, in generate_stream_chatglm3
    inputs = tokenizer.build_chat_input(query, history=history, role=role)
AttributeError: 'ChatGLMTokenizer' object has no attribute 'build_chat_input'

**Comment by jonsen** [comment]
@yinjianjie 

我这边没有遇到。报错的没有build_chat_input，可能需要更新下ChatGLM3代码库和依赖包。

> File "/mnt/workspace/ChatGLM3/utils.py", line 131, in generate_stream_chatglm3
> inputs = tokenizer.build_chat_input(query, history=history, role=role)
> AttributeError: 'ChatGLMTokenizer' object has no attribute 'build_chat_input'

更新依赖包：

> pip install --upgrade -r requirements.txt

**Comment by L3LeTrigger-F** [comment]
> @yinjianjie
> 
> 我这边没有遇到。报错的没有build_chat_input，可能需要更新下ChatGLM3代码库和依赖包。
> 
> > File "/mnt/workspace/ChatGLM3/utils.py", line 131, in generate_stream_chatglm3
> > inputs = tokenizer.build_chat_input(query, history=history, role=role)
> > AttributeError: 'ChatGLMTokenizer' object has no attribute 'build_chat_input'
> 
> 更新依赖包：
> 
> > pip install --upgrade -r requirements.txt

我更新后仍然会报错。

**Comment by tianshangwuyun** [comment]
没有build_chat_input 这个怎么解决，最新版都报错

**Comment by CZU32** [comment]
has no attribute 'build_chat_input' 是因为tokenizer没有使用源模型里面ChatGLMTokenizer的类来生成
`from tokenization_chatglm import ChatGLMTokenizer
tokenizer = ChatGLMTokenizer.from_pretrained(TOKENIZER_PATH, trust_remote_code=True)`

原模型类方法：[https://huggingface.co/THUDM/chatglm3-6b/blob/main/tokenization_chatglm.py](tokenization_chatglm)
