### ISSUE TITLE
全量微调之后的权重如何通过‘ChatGLM3/basic_demo/cli_demo.py’跑起来？

### ISSUE THREAD

**Issue by ShuzhaoXie** [THUDM/ChatGLM3#577]
MODEL_PATH和TOKENIZER_PATH都按照飞书文档配置了，尝试了以下两种方式，都没用。。。

# 1
```python
tokenizer = AutoTokenizer.from_pretrained(TOKENIZER_PATH, trust_remote_code=True)
PRE_SEQ_LEN = int(os.environ.get("PRE_SEQ_LEN", 2048))
config = AutoConfig.from_pretrained(MODEL_PATH, trust_remote_code=True, pre_seq_len=PRE_SEQ_LEN)
if 'cuda' in DEVICE: # AMD, NVIDIA GPU can use Half Precision
    model = AutoModel.from_pretrained(MODEL_PATH, trust_remote_code=True, config=config).to(DEVICE).eval()
else: # CPU, Intel GPU and other GPU can use Float16 Precision Only
    model = AutoModel.from_pretrained(MODEL_PATH, trust_remote_code=True, config=config).float().to(DEVICE).eval()

prefix_state_dict = torch.load(os.path.join(PT_PATH, "pytorch_model.bin"))
new_prefix_state_dict = {}
for k, v in prefix_state_dict.items():
    if k.startswith("transformer.prefix_encoder."):
        new_prefix_state_dict[k[len("transformer.prefix_encoder."):]] = v
print("Loaded from pt checkpoints", new_prefix_state_dict.keys())
model.transformer.prefix_encoder.load_state_dict(new_prefix_state_dict)
```

报错：
```bash
Traceback (most recent call last):
  File "/data/sigs_users/szxie/ChatGLM3/basic_demo/cli_demo.py", line 50, in <module>
    model.transformer.prefix_encoder.load_state_dict(new_prefix_state_dict)
  File "/data/sigs_users/szxie/anaconda3/envs/chatglm3-demo/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2152, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for PrefixEncoder:
        Missing key(s) in state_dict: "embedding.weight". 
```

# 2
```python
tokenizer = AutoTokenizer.from_pretrained(TOKENIZER_PATH, trust_remote_code=True)
if 'cuda' in DEVICE: # AMD, NVIDIA GPU can use Half Precision
    model = AutoModel.from_pretrained(MODEL_PATH, trust_remote_code=True).to(DEVICE).eval()
else: # CPU, Intel GPU and other GPU can use Float16 Precision Only
    model = AutoModel.from_pretrained(MODEL_PATH, trust_remote_code=True).float().to(DEVICE).eval()
```
报错：
```bash
OSError: /data/sigs_users/szxie/ChatGLM3/finetune_chatmodel_demo/output/tool_alpaca_ft-20231210-234911-1e-4 does not appear to have a file named configuration_chatglm.py. Checkout 'https://huggingface.co//data/sigs_users/szxie/ChatGLM3/finetune_chatmodel_demo/output/tool_alpaca_ft-20231210-234911-1e-4/None' for available files.
```

**Comment by oan-J** [comment]
第一：
全量微调的部署应该用这个
`cd ../composite_demo`
`MODEL_PATH="path to finetuned model checkpoint" TOKENIZER_PATH="THUDM/chatglm3-6b" streamlit run main.py`

第二：
报错参考：https://blog.csdn.net/m0_53903583/article/details/134930618?spm=1001.2014.3001.5501
MODEL路径下缺失configuration_chatglm.py，因为微调后的output里没有对应的py文件，这些文件在chatglm3-6b里，你把对应的py文件从chatglm3-6b里复制到你的/checkpoint-500路径下就行

**Comment by ShuzhaoXie** [comment]
多谢

**Comment by ShuzhaoXie** [comment]
更新：

用basic_demo里的cli_demo.py也可以使用，参考上面大佬的回答，复制相应文件到checkpoint_path即可：

> 报错参考：https://blog.csdn.net/m0_53903583/article/details/134930618?spm=1001.2014.3001.5501
> MODEL路径下缺失configuration_chatglm.py，因为微调后的output里没有对应的py文件，这些文件在chatglm3-6b里，你把对应的py文件从chatglm3-6b里复制到你的/checkpoint-500路径下就行
