### ISSUE TITLE
调用openai_api.py报错

### ISSUE THREAD

**Issue by lostmaniac** [THUDM/ChatGLM3#578]
### System Info / 系統信息

RTX4090 * 2
CUDA Version: 12.2
Driver Version: 535.129.03
硬盘：SSD，测速380M/S
python == 3.10.12
git仓库分支 main
git提交版本 https://github.com/THUDM/ChatGLM3/commit/3106cae75c1241eb12a2463186c5f617a6886552
使用文件： ./openai_api.py

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/data/miniconda3/envs/ChatGLM3/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/data/miniconda3/envs/ChatGLM3/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/data/miniconda3/envs/ChatGLM3/lib/python3.10/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/data/miniconda3/envs/ChatGLM3/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/data/miniconda3/envs/ChatGLM3/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/data/miniconda3/envs/ChatGLM3/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/data/miniconda3/envs/ChatGLM3/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/data/miniconda3/envs/ChatGLM3/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/data/miniconda3/envs/ChatGLM3/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/data/miniconda3/envs/ChatGLM3/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/data/miniconda3/envs/ChatGLM3/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/data/miniconda3/envs/ChatGLM3/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/data/miniconda3/envs/ChatGLM3/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/data/miniconda3/envs/ChatGLM3/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/data/miniconda3/envs/ChatGLM3/lib/python3.10/site-packages/fastapi/routing.py", line 274, in app
    raw_response = await run_endpoint_function(
  File "/data/miniconda3/envs/ChatGLM3/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/shixinlei/ChatGLM3/openai_api_demo/openai_api.py", line 296, in create_chat_completion
    task_usage = UsageInfo.model_validate(response["usage"])
AttributeError: type object 'UsageInfo' has no attribute 'model_validate'

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

直接启动，然后配合fastgpt的文档qa拆分就会有这个报错

### Expected behavior / 期待表现

解决报错

**Comment by lostmaniac** [comment]
找到问题了，需要升级依赖包，刚刚仔细看了一下提交

**Comment by sliontc** [comment]
> 找到问题了，需要升级依赖包，刚刚仔细看了一下提交

你好，你是怎么解决的？

**Comment by lostmaniac** [comment]
> > 找到问题了，需要升级依赖包，刚刚仔细看了一下提交
> 
> 你好，你是怎么解决的？

我当时是老版本,然后升级一下不能用,后来直接重新安装了一下所有的包就解决了.目前可以用,你可以把报错信息发出来我帮你看一下

**Comment by yemustars** [comment]
<img width="691" alt="Snipaste_1" src="https://github.com/THUDM/ChatGLM3/assets/156065141/f56a5acd-b353-470f-be3b-b39b57091308">
<img width="592" alt="Snipaste_2" src="https://github.com/THUDM/ChatGLM3/assets/156065141/3bb69893-f913-49f5-958b-e40cf991f3a2">

**Comment by yemustars** [comment]
Please check this error, thank you.

**Comment by zRzRzRzRzRzRzR** [comment]
更新一下最新的依赖和代码
