### ISSUE TITLE
Streamlit composite demo  set_page_config()

### ISSUE THREAD

**Issue by yhyu13** [THUDM/ChatGLM3#618]
### System Info / 系統信息

Ubutnu 22.04 cuda12.1 rtx3090

```
streamlit                 1.29.0
```

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

```
conda create -n chatglm3-demo python=3.10
conda activate chatglm3-demo
pip install -r requirements.txt
cd composite_demo
pip install -r requirements.txt
ipython kernel install --name chatglm3-demo --user

streamlit run main.py
```

```
 You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://192.168.1.5:8501

Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:05<00:00,  1.19it/s]
[registered tool] {'description': 'Generates a random number x, s.t. range[0] <= x < range[1]',
 'name': 'random_number_generator',
 'params': [{'description': 'The random seed used by the generator',
             'name': 'seed',
             'required': True,
             'type': 'int'},
            {'description': 'The range of the generated numbers',
             'name': 'range',
             'required': True,
             'type': 'tuple[int, int]'}]}
[registered tool] {'description': 'Get the current weather for `city_name`',
 'name': 'get_weather',
 'params': [{'description': 'The name of the city to be queried',
             'name': 'city_name',
             'required': True,
             'type': 'str'}]}
[registered tool] {'description': 'Use shell to run command',
 'name': 'get_shell',
 'params': [{'description': 'The command should run in Linux shell',
             'name': 'query',
             'required': True,
             'type': 'str'}]}
2023-12-19 07:10:42.421 Uncaught app exception
Traceback (most recent call last):
  File "/home/hangyu5/anaconda3/envs/chatglm3-demo/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "/home/hangyu5/Documents/Git-repoMy/AIResearchVault/repo/LLM/ChatGLM/ChatGLM3/composite_demo/main.py", line 5, in <module>
    st.set_page_config(
  File "/home/hangyu5/anaconda3/envs/chatglm3-demo/lib/python3.10/site-packages/streamlit/runtime/metrics_util.py", line 396, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "/home/hangyu5/anaconda3/envs/chatglm3-demo/lib/python3.10/site-packages/streamlit/commands/page_config.py", line 227, in set_page_config
    ctx.enqueue(msg)
  File "/home/hangyu5/anaconda3/envs/chatglm3-demo/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_run_context.py", line 100, in enqueue
    raise StreamlitAPIException(
streamlit.errors.StreamlitAPIException: `set_page_config()` can only be called once per app page, and must be called as the first Streamlit command in your script.

For more information refer to the [docs](https://docs.streamlit.io/library/api-reference/utilities/st.set_page_config).
```

### Expected behavior / 期待表现

Shoudl run as fine

**Comment by zRzRzRzRzRzRzR** [comment]
Fix it now
