### ISSUE TITLE
运行web_demo_streamlit时报错ModuleNotFoundError: No module named 'transformers'

### ISSUE THREAD

**Issue by changzheng169** [THUDM/ChatGLM3#625]
### System Info / 系統信息

cuda：11.8
torch：2.1
transformers：4.36.2

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

chatglm3) star@star-S8030GM2NE:~/ChatGLM3/basic_demo$ streamlit run web_demo_streamlit.py

2023-12-20 21:45:07.062 Uncaught app exception
Traceback (most recent call last):
File "/home/star/.local/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 534, in _run_script
exec(code, module.dict)
File "/home/star/ChatGLM3/basic_demo/web_demo_streamlit.py", line 16, in
from transformers import AutoModel, AutoTokenizer
ModuleNotFoundError: No module named 'transformers'

### Expected behavior / 期待表现

为什么安装了最新的transformers，还会遇到No module named 'transformers'

**Comment by zRzRzRzRzRzRzR** [comment]
没有遇到你的这个情况，你降级后能用吗
