### ISSUE TITLE
Gradio的Web UI运行后无法交互对话，后端报错“ValueError: not enough values to unpack (expected 2, got 1)”

### ISSUE THREAD

**Issue by HFourier** [THUDM/ChatGLM3#672]
### System Info / 系統信息

硬件：NVIDIA GeForce RTX 3090
系统信息：
Ubuntu20.04
Python 3.10
 Pytorch 2.1.1
CUDA 11.8, cuDNN 8, NVCC, VNC

### Who can help? / 谁可以帮助到您？

@abmfy 

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1. 使用魔搭下载模型
``` 
from modelscope import snapshot_download
model_dir = snapshot_download("ZhipuAI/chatglm3-6b-base", revision = "v1.0.0")
```
2. 修改`basic_demo/web_demo_gradio.py`  line17 和line20 
from modelscope import AutoModel, AutoTokenizer
...
MODEL_PATH = os.environ.get('MODEL_PATH', 'ZhipuAI/chatglm3-6b-base')
...

3. 运行python basic_demo/web_demo_gradio.py 

4. 进入gradio交互界面，输入“你好”，发送后无响应，回到终端，报错如下：
Traceback (most recent call last):
  File "/root/miniconda3/envs/myconda/lib/python3.10/site-packages/gradio/queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "/root/miniconda3/envs/myconda/lib/python3.10/site-packages/gradio/route_utils.py", line 216, in call_process_api
    output = await app.get_blocks().process_api(
  File "/root/miniconda3/envs/myconda/lib/python3.10/site-packages/gradio/blocks.py", line 1555, in process_api
    result = await self.call_function(
  File "/root/miniconda3/envs/myconda/lib/python3.10/site-packages/gradio/blocks.py", line 1207, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/root/miniconda3/envs/myconda/lib/python3.10/site-packages/gradio/utils.py", line 516, in async_iteration
    return await iterator.__anext__()
  File "/root/miniconda3/envs/myconda/lib/python3.10/site-packages/gradio/utils.py", line 509, in __anext__
    return await anyio.to_thread.run_sync(
  File "/root/miniconda3/envs/myconda/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/root/miniconda3/envs/myconda/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
  File "/root/miniconda3/envs/myconda/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "/root/miniconda3/envs/myconda/lib/python3.10/site-packages/gradio/utils.py", line 492, in run_sync_iterator_async
    return next(iterator)
  File "/root/miniconda3/envs/myconda/lib/python3.10/site-packages/gradio/utils.py", line 642, in gen_wrapper
    yield from f(*args, **kwargs)
  File "/ChatGLM3/basic_demo/web_demo_gradio.py", line 74, in predict
    for response, history, past_key_values in model.stream_chat(tokenizer, input, history,
  File "/root/miniconda3/envs/myconda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm3-6b-base/modeling_chatglm.py", line 1078, in stream_chat
    response, new_history = self.process_response(response, history)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm3-6b-base/modeling_chatglm.py", line 1004, in process_response
    metadata, content = response.split("\n", maxsplit=1)
ValueError: not enough values to unpack (expected 2, got 1)

### Expected behavior / 期待表现

 期望能够正常输出

**Comment by zRzRzRzRzRzRzR** [comment]
hf代码要更新

**Comment by HFourier** [comment]
> 去huggingface更新模型代码，模型代码升级了，权重不用变

可以附上跳转连接吗？我在huggingface里只找到了权重文件和json文件

**Comment by HFourier** [comment]
我将/root/.cache/huggingface/modules/transformers_modules/chatglm3-6b-base 下的 tokenization_chatglm.py 、quantization.py、 modeling_chatglm.py和configuration_chatglm.py 都替换成huggingface上下载的，但是问题并没有解决，返回了一样的问题

**Comment by AHPUymhd** [comment]
> 我将/root/.cache/huggingface/modules/transformers_modules/chatglm3-6b-base 下的 tokenization_chatglm.py 、quantization.py、 modeling_chatglm.py和configuration_chatglm.py 都替换成huggingface上下载的，但是问题并没有解决，返回了一样的问题

请问您解决了吗，我还是跟你一样的问题

**Comment by HFourier** [comment]
> > 我将/root/.cache/huggingface/modules/transformers_modules/chatglm3-6b-base 下的 tokenization_chatglm.py 、quantization.py、 modeling_chatglm.py和configuration_chatglm.py 都替换成huggingface上下载的，但是问题并没有解决，返回了一样的问题
> 
> 请问您解决了吗，我还是跟你一样的问题

后面没有没有成功解决这个问题，我记得我后来没有用modelscope而是全部直接用huggingface
