### ISSUE TITLE
RuntimeError: CUDA error: uncorrectable ECC error encountered，代码版本：5346f277f61aa39a83f2bb16e8df40bd634a8a7b

### ISSUE THREAD

**Issue by qurikuduo** [THUDM/ChatGLM3#681]
### System Info / 系統信息

CUDA： CUDA Version: 12.1
python： 3.11.5
pytorch： 2.1.1 py3.11_cuda12.1_cudnn8.9.2_0 pytorch
pytorch-cuda： 12.1 ha16c6d3_5 pytorch
transformers： 4.35.2 pypi_0 pypi
OS： Ubuntu 18.04

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

我修改了官方的 Openai_api 示例，仅仅是指定了我使用哪4块gpu卡，稳定运行了两周。但是今天再次通过api提问时突然报错了。
1.运行openai_api一段时间后，报错：
RuntimeError: CUDA error: uncorrectable ECC error encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

2.重启程序后，仍然报错：
Loading checkpoint shards: 100%|██████████| 7/7 [00:08<00:00,  1.27s/it]
Traceback (most recent call last):
  File "/root/ChatGLM3/openai_api_demo/openai_api.py", line 251, in <module>
    model = load_model_on_gpus(MODEL_PATH, num_gpus=_my_gpu_count)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/ChatGLM3/openai_api_demo/utils.py", line 61, in load_model_on_gpus
    model = dispatch_model(model, device_map=device_map)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/chatglm3/lib/python3.11/site-packages/accelerate/big_modeling.py", line 396, in dispatch_model
    attach_align_device_hook_on_blocks(
  File "/root/anaconda3/envs/chatglm3/lib/python3.11/site-packages/accelerate/hooks.py", line 547, in attach_align_device_hook_on_blocks
    attach_align_device_hook_on_blocks(
  File "/root/anaconda3/envs/chatglm3/lib/python3.11/site-packages/accelerate/hooks.py", line 547, in attach_align_device_hook_on_blocks
    attach_align_device_hook_on_blocks(
  File "/root/anaconda3/envs/chatglm3/lib/python3.11/site-packages/accelerate/hooks.py", line 547, in attach_align_device_hook_on_blocks
    attach_align_device_hook_on_blocks(
  File "/root/anaconda3/envs/chatglm3/lib/python3.11/site-packages/accelerate/hooks.py", line 517, in attach_align_device_hook_on_blocks
    add_hook_to_module(module, hook)
  File "/root/anaconda3/envs/chatglm3/lib/python3.11/site-packages/accelerate/hooks.py", line 156, in add_hook_to_module
    module = hook.init_hook(module)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/chatglm3/lib/python3.11/site-packages/accelerate/hooks.py", line 254, in init_hook
    set_module_tensor_to_device(module, name, self.execution_device)
  File "/root/anaconda3/envs/chatglm3/lib/python3.11/site-packages/accelerate/utils/modeling.py", line 311, in set_module_tensor_to_device
    new_value = old_value.to(device)
                ^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: uncorrectable ECC error encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

3. 重启服务器后，再启动程序，一切正常。

### Expected behavior / 期待表现

有无其他朋友遇到过类似问题？可能是什么问题导致的报错？

**Comment by zRzRzRzRzRzRzR** [comment]
尝试更新我们最新的hf代码和github代码，这问题我记得在hf有解决，也有可能是卡的问题，我们的A100部署了几十天了也没有问题

**Comment by zRzRzRzRzRzRzR** [comment]
也可以检查是不是历史记录超过8k了，记得要清理历史
