### ISSUE TITLE
response为空

### ISSUE THREAD

**Issue by Anorid** [THUDM/ChatGLM3#682]
Prompt:为什么了解疾病
Response:
Prompt:如何维持团队的创新和动力
Response:
Prompt:科研
Response:
Prompt:创新是什么
Traceback (most recent call last):
  File "/root/autodl-tmp/ChatGLM3/finetune_chatmodel_demo/inference.py", line 37, in <module>
    inputs = tokenizer(prompt, return_tensors="pt")
  File "/root/miniconda3/envs/chatglm/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2802, in __call__
    encodings = self._call_one(text=text, text_pair=text_pair, **all_kwargs)
  File "/root/miniconda3/envs/chatglm/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2908, in _call_one
    return self.encode_plus(
  File "/root/miniconda3/envs/chatglm/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2981, in encode_plus
    return self._encode_plus(
  File "/root/miniconda3/envs/chatglm/lib/python3.10/site-packages/transformers/tokenization_utils.py", line 719, in _encode_plus
    first_ids = get_input_ids(text)
  File "/root/miniconda3/envs/chatglm/lib/python3.10/site-packages/transformers/tokenization_utils.py", line 686, in get_input_ids
    tokens = self.tokenize(text, **kwargs)
  File "/root/miniconda3/envs/chatglm/lib/python3.10/site-packages/transformers/tokenization_utils.py", line 617, in tokenize
    tokenized_text.extend(self._tokenize(token))
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm3-6b/tokenization_chatglm.py", line 149, in _tokenize
    return self.tokenizer.tokenize(text, encode_special_tokens=self.encode_special_tokens)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm3-6b/tokenization_chatglm.py", line 47, in tokenize
    return self.sp_model.EncodeAsPieces(s)
  File "/root/miniconda3/envs/chatglm/lib/python3.10/site-packages/sentencepiece/__init__.py", line 545, in EncodeAsPieces
    return self.Encode(input=input, out_type=str, **kwargs)
  File "/root/miniconda3/envs/chatglm/lib/python3.10/site-packages/sentencepiece/__init__.py", line 531, in Encode
    return self._EncodeAsPieces(input, enable_sampling, nbest_size,
  File "/root/miniconda3/envs/chatglm/lib/python3.10/site-packages/sentencepiece/__init__.py", line 316, in _EncodeAsPieces
    return _sentencepiece.SentencePieceProcessor__EncodeAsPieces(self, text, enable_sampling, nbest_size, alpha, add_bos, add_eos, reverse, emit_unk_piece)
TypeError: not a string
是因为数据的问题还是参数的问题，导致的这样的问题，response为空

**Comment by zRzRzRzRzRzRzR** [comment]
emm，估计是微调的过程出现问题，你用任何方式都无法正常推理就是你模型的问题了

**Comment by Anorid** [comment]
PRE_SEQ_LEN=128
LR=1e-4
NUM_GPUS=1
MAX_SOURCE_LEN=1024
MAX_TARGET_LEN=128
DEV_BATCH_SIZE=1
GRAD_ACCUMULARION_STEPS=32
MAX_STEP=40
SAVE_INTERVAL=$MAX_STEP

DATESTR=`date +%Y%m%d-%H%M%S`
RUN_NAME=advertise_gen_pt

BASE_MODEL_PATH=/root/autodl-tmp/ChatGLM3/chatglm3-6b
DATASET_PATH=formatted_data/package.jsonl


是不是因为我的数据量小或者是参数的问题，官方的参数挺大的，数据量也到，我用少量数据进行测试，参数也改了一些，之后就出现的问题，如果是推理的问题，应该怎么反向或者正向推理，求教

**Comment by haozaiiii** [comment]
我也是，跑好几次了，不是数据大小的问题。
finetune出来的pytorch_model.bin文件11个G，lora 出来不应该就几十或者几百兆吗？
