### ISSUE TITLE
base模型lora finetune后预测报错

### ISSUE THREAD

**Issue by haozaiiii** [THUDM/ChatGLM3#687]
(pyl-310) python inference.py \
--model /data/pyh/llm/hf-model/chatglm3-6b-base \
--lora-path /data/pyh/llm/project/ChatGLM3/finetune_basemodel_demo/output/0102_v0/pytorch_model.bin
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:12<00:00,  1.82s/it]
You shouldn't move a model when it is dispatched on multiple devices.
Prompt: 清单内容：砌块墙##1.砌块品种、规格、强度等级:A5加气混凝土砌块；2.墙体类型:内墙；3.砂浆强度等级:Ma5.0专用砂浆。抽取属性：砂浆强度等级-->
Traceback (most recent call last):
  File "/data/pyh/llm/project/ChatGLM3/finetune_basemodel_demo/inference.py", line 44, in <module>
    response = model.generate(input_ids=inputs["input_ids"],
  File "/root/anaconda3/envs/pyl-310/lib/python3.10/site-packages/peft/peft_model.py", line 1130, in generate
    outputs = self.base_model.generate(**kwargs)
  File "/root/anaconda3/envs/pyl-310/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/anaconda3/envs/pyl-310/lib/python3.10/site-packages/transformers/generation/utils.py", line 1718, in generate
    return self.greedy_search(
  File "/root/anaconda3/envs/pyl-310/lib/python3.10/site-packages/transformers/generation/utils.py", line 2579, in greedy_search
    outputs = self(
  File "/root/anaconda3/envs/pyl-310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/anaconda3/envs/pyl-310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/anaconda3/envs/pyl-310/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm3-6b-base/modeling_chatglm.py", line 937, in forward
    transformer_outputs = self.transformer(
  File "/root/anaconda3/envs/pyl-310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/anaconda3/envs/pyl-310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm3-6b-base/modeling_chatglm.py", line 830, in forward
    hidden_states, presents, all_hidden_states, all_self_attentions = self.encoder(
  File "/root/anaconda3/envs/pyl-310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/anaconda3/envs/pyl-310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm3-6b-base/modeling_chatglm.py", line 640, in forward
    layer_ret = layer(
  File "/root/anaconda3/envs/pyl-310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/anaconda3/envs/pyl-310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/anaconda3/envs/pyl-310/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm3-6b-base/modeling_chatglm.py", line 542, in forward
    layernorm_output = self.input_layernorm(hidden_states)
  File "/root/anaconda3/envs/pyl-310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/anaconda3/envs/pyl-310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/anaconda3/envs/pyl-310/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm3-6b-base/modeling_chatglm.py", line 192, in forward
    return (self.weight * hidden_states).to(input_dtype)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1!

**Comment by haozaiiii** [comment]
已解决

**Comment by sumanbanerjee1** [comment]
> 已解决


Please tell me how did you solve this?

**Comment by SunYunyun** [comment]
你好，为啥微调后的bin文件几个G这边大下，是代码问题吗

**Comment by 18122626** [comment]
你好，我也遇到了同样的问题，请问是怎么解决的？
