### ISSUE TITLE
OSError: [WinError 126] 找不到指定的模块。 Error loading "D:\python\lib\site-packages\torch\lib\cudnn_cnn_infer64_8.dll" or one of its dependencies.

### ISSUE THREAD

**Issue by north1nk** [THUDM/ChatGLM3#69]
PS J:\ChatGLM3-main> python web_demo.py
Traceback (most recent call last):
  File "J:\ChatGLM3-main\web_demo.py", line 4, in <module>
    from utils import load_model_on_gpus
  File "J:\ChatGLM3-main\utils.py", line 4, in <module>
    from torch.nn import Module
  File "D:\python\lib\site-packages\torch\__init__.py", line 139, in <module>
    raise err
OSError: [WinError 126] 找不到指定的模块。 Error loading "D:\python\lib\site-packages\torch\lib\cudnn_cnn_infer64_8.dll" or one of its dependencies.

运行web_demo.py  报错

**Comment by north1nk** [comment]
infer64_8.dll这个文件是存在的

**Comment by zRzRzRzRzRzRzR** [comment]
这个报错应该是torch的问题，与本仓库无关，您可以查询一下相关错误的网上的解决方案
