### ISSUE TITLE
AttributeError: 'ChatGLMTokenizer' object has no attribute 'get_command'

### ISSUE THREAD

**Issue by eeezae** [THUDM/ChatGLM3#762]
### System Info / 系統信息

CUDA Version: 12.1
transformers    4.36.2
Python 3.10.12

### Who can help? / 谁可以帮助到您？
@abmfy 

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

streamlit run main.py 启动后，Chat模式从网页询问问题，报错

错误日志如下：

```
== Input ==
 1

==History==
 [{'role': 'system', 'content': "You are ChatGLM3, a large language model trained by Zhipu.AI. Follow the user's instructions carefully. Respond using markdown."}]
ChatGLMTokenizer(name_or_path='/root/.cache/huggingface/modules/transformers_modules/chatglm3-6b/', vocab_size=130344, model_max_length=1000000000000000019884624838656, is_fast=False, padding_side='left', truncation_side='right', special_tokens={'bos_token': '<sop>', 'eos_token': '<eop>', 'unk_token': '<unk>', 'pad_token': '<pad>', 'mask_token': '[MASK]'}, clean_up_tokenization_spaces=True)
2024-01-18 00:42:37.883 Uncaught app exception
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/chatglm3-dGbjxael-py3.10/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "/root/Project/ChatGLM3/composite_demo/main.py", line 73, in <module>
    demo_chat.main(
  File "/root/Project/ChatGLM3/composite_demo/demo_chat.py", line 62, in main
    for response in client.generate_stream(
  File "/root/Project/ChatGLM3/composite_demo/client.py", line 183, in generate_stream
    for new_text, _ in stream_chat(
  File "/root/Project/ChatGLM3/composite_demo/client.py", line 71, in stream_chat
    eos_token_id = [tokenizer.eos_token_id, tokenizer.get_command("<|user|>"),
AttributeError: 'ChatGLMTokenizer' object has no attribute 'get_command'
```

### Expected behavior / 期待表现

解决报错

**Comment by zRzRzRzRzRzRzR** [comment]
huggingface更新一下文件？没有遇到这个错误，确保你的模型是huggingface最新的模型

**Comment by eeezae** [comment]
换国内源重新下载了一遍可以了
