### ISSUE TITLE
gradio.py运行报错

### ISSUE THREAD

**Issue by SunJR24** [THUDM/ChatGLM3#769]
### System Info / 系統信息

在先前的gradio版本3.30.0中，gardio.py是正常的，但是在最新的gradio4.15.0中，首先会报错Textbox' object has no attribute 'style，将user_input = gr.Textbox(show_label=False, placeholder="Input...", lines=10).style(container=False)修改为新更正的user_input = gr.Textbox(show_label=False, placeholder="Input...", lines=10, container=False)后，程序虽然成功启动，但是运行时会报错
====conversation====
 [{'role': 'user', 'content': '测试'}]
Traceback (most recent call last):
  File "E:\Anaconda3\envs\Test-envs\lib\site-packages\gradio\queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
  File "E:\Anaconda3\envs\Test-envs\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "E:\Anaconda3\envs\Test-envs\lib\site-packages\gradio\blocks.py", line 1561, in process_api
    result = await self.call_function(
  File "E:\Anaconda3\envs\Test-envs\lib\site-packages\gradio\blocks.py", line 1191, in call_function
    prediction = await utils.async_iteration(iterator)
  File "E:\Anaconda3\envs\Test-envs\lib\site-packages\gradio\utils.py", line 519, in async_iteration
    return await iterator.__anext__()
  File "E:\Anaconda3\envs\Test-envs\lib\site-packages\gradio\utils.py", line 512, in __anext__
    return await anyio.to_thread.run_sync(
  File "E:\Anaconda3\envs\Test-envs\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\Anaconda3\envs\Test-envs\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\Anaconda3\envs\Test-envs\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\Anaconda3\envs\Test-envs\lib\site-packages\gradio\utils.py", line 495, in run_sync_iterator_async
    return next(iterator)
  File "E:\Anaconda3\envs\Test-envs\lib\site-packages\gradio\utils.py", line 666, in gen_wrapper
    yield from f(*args, **kwargs)
  File "E:\Work-base\A-Project-Base\ChatGLM3-Base\ChatGLM3-main-T\basic_demo\web_demo_gradio.py", line 86, in predict
    model_inputs = tokenizer.apply_chat_template(messages,
AttributeError: 'ChatGLMTokenizer' object has no attribute 'apply_chat_template'

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

在先前的gradio版本3.30.0中，gardio.py是正常的，但是在最新的gradio4.15.0中，首先会报错Textbox' object has no attribute 'style，将user_input = gr.Textbox(show_label=False, placeholder="Input...", lines=10).style(container=False)修改为新更正的user_input = gr.Textbox(show_label=False, placeholder="Input...", lines=10, container=False)后，程序虽然成功启动，但是运行时会报错
====conversation====
 [{'role': 'user', 'content': '测试'}]
Traceback (most recent call last):
  File "E:\Anaconda3\envs\Test-envs\lib\site-packages\gradio\queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
  File "E:\Anaconda3\envs\Test-envs\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "E:\Anaconda3\envs\Test-envs\lib\site-packages\gradio\blocks.py", line 1561, in process_api
    result = await self.call_function(
  File "E:\Anaconda3\envs\Test-envs\lib\site-packages\gradio\blocks.py", line 1191, in call_function
    prediction = await utils.async_iteration(iterator)
  File "E:\Anaconda3\envs\Test-envs\lib\site-packages\gradio\utils.py", line 519, in async_iteration
    return await iterator.__anext__()
  File "E:\Anaconda3\envs\Test-envs\lib\site-packages\gradio\utils.py", line 512, in __anext__
    return await anyio.to_thread.run_sync(
  File "E:\Anaconda3\envs\Test-envs\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\Anaconda3\envs\Test-envs\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\Anaconda3\envs\Test-envs\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\Anaconda3\envs\Test-envs\lib\site-packages\gradio\utils.py", line 495, in run_sync_iterator_async
    return next(iterator)
  File "E:\Anaconda3\envs\Test-envs\lib\site-packages\gradio\utils.py", line 666, in gen_wrapper
    yield from f(*args, **kwargs)
  File "E:\Work-base\A-Project-Base\ChatGLM3-Base\ChatGLM3-main-T\basic_demo\web_demo_gradio.py", line 86, in predict
    model_inputs = tokenizer.apply_chat_template(messages,
AttributeError: 'ChatGLMTokenizer' object has no attribute 'apply_chat_template'

### Expected behavior / 期待表现

在先前的gradio版本3.30.0中，gardio.py是正常的，但是在最新的gradio4.15.0中，首先会报错Textbox' object has no attribute 'style，将user_input = gr.Textbox(show_label=False, placeholder="Input...", lines=10).style(container=False)修改为新更正的user_input = gr.Textbox(show_label=False, placeholder="Input...", lines=10, container=False)后，程序虽然成功启动，但是运行时会报错
====conversation====
 [{'role': 'user', 'content': '测试'}]
Traceback (most recent call last):
  File "E:\Anaconda3\envs\Test-envs\lib\site-packages\gradio\queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
  File "E:\Anaconda3\envs\Test-envs\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "E:\Anaconda3\envs\Test-envs\lib\site-packages\gradio\blocks.py", line 1561, in process_api
    result = await self.call_function(
  File "E:\Anaconda3\envs\Test-envs\lib\site-packages\gradio\blocks.py", line 1191, in call_function
    prediction = await utils.async_iteration(iterator)
  File "E:\Anaconda3\envs\Test-envs\lib\site-packages\gradio\utils.py", line 519, in async_iteration
    return await iterator.__anext__()
  File "E:\Anaconda3\envs\Test-envs\lib\site-packages\gradio\utils.py", line 512, in __anext__
    return await anyio.to_thread.run_sync(
  File "E:\Anaconda3\envs\Test-envs\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\Anaconda3\envs\Test-envs\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\Anaconda3\envs\Test-envs\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\Anaconda3\envs\Test-envs\lib\site-packages\gradio\utils.py", line 495, in run_sync_iterator_async
    return next(iterator)
  File "E:\Anaconda3\envs\Test-envs\lib\site-packages\gradio\utils.py", line 666, in gen_wrapper
    yield from f(*args, **kwargs)
  File "E:\Work-base\A-Project-Base\ChatGLM3-Base\ChatGLM3-main-T\basic_demo\web_demo_gradio.py", line 86, in predict
    model_inputs = tokenizer.apply_chat_template(messages,
AttributeError: 'ChatGLMTokenizer' object has no attribute 'apply_chat_template'

**Comment by zRzRzRzRzRzRzR** [comment]
huggingface代码没更新，去huggingface拉最新配置文件

**Comment by Lee52** [comment]
> huggingface代码没更新，去huggingface拉最新配置文件

我也出现了相同错误AttributeError: 'PreTrainedTokenizerFast' object has no attribute 'apply_chat_template'
应该怎么处理呢

F:\工作\2024年11月\MiniMind\minimind-v1\minimind>python 2-eval.py
模型参数: 26.878464 百万 = 0.026878464 B (Billion)
[Q]: 你叫什么名字
Traceback (most recent call last):
  File "2-eval.py", line 137, in <module>
    new_prompt = tokenizer.apply_chat_template(
AttributeError: 'PreTrainedTokenizerFast' object has no attribute 'apply_chat_template'
