### ISSUE TITLE
微调base模型后部署composite_demo报错缺少pytorch_model.bin, tf_model.h5, model.ckpt.index

### ISSUE THREAD

**Issue by Longleaves** [THUDM/ChatGLM3#791]
### System Info / 系統信息

torch                         2.1.2
torchaudio                    2.1.2+cu118
torchvision                   0.16.2+cu118
cuda                   11.8

### Who can help? / 谁可以帮助到您？

@abmfy @Btlmd 

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1.微调好base模型如图所示：
![图片](https://github.com/THUDM/ChatGLM3/assets/58903935/2ecaec09-0779-4285-80f3-10aca548bfd4)
2.由于一开始报错说缺少config、modeling等文件，我已从chatglm-6b-base中复制：
![图片](https://github.com/THUDM/ChatGLM3/assets/58903935/d77bf042-a575-4e97-a207-d4e1ca256a11)
3.似乎还是报错说缺少文件
```
Traceback (most recent call last):
  File "/home/.conda/envs/chatglm3/lib/python3.11/site-packages/streamlit/runtime/caching/cache_utils.py", line 264, in _get_or_create_cached_value
    cached_result = cache.read_result(value_key)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/.conda/envs/chatglm3/lib/python3.11/site-packages/streamlit/runtime/caching/cache_resource_api.py", line 498, in read_result
    raise CacheKeyNotFoundError()
streamlit.runtime.caching.cache_errors.CacheKeyNotFoundError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/.conda/envs/chatglm3/lib/python3.11/site-packages/streamlit/runtime/caching/cache_utils.py", line 312, in _handle_cache_miss
    cached_result = cache.read_result(value_key)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/.conda/envs/chatglm3/lib/python3.11/site-packages/streamlit/runtime/caching/cache_resource_api.py", line 498, in read_result
    raise CacheKeyNotFoundError()
streamlit.runtime.caching.cache_errors.CacheKeyNotFoundError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/.conda/envs/chatglm3/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "/home/ChatGLM3-main/composite_demo/main.py", line 11, in <module>
    import demo_chat, demo_ci, demo_tool
  File "/home/ChatGLM3-main/composite_demo/demo_chat.py", line 9, in <module>
    client = get_client()
             ^^^^^^^^^^^^
  File "/home/.conda/envs/chatglm3/lib/python3.11/site-packages/streamlit/runtime/caching/cache_utils.py", line 212, in wrapper
    return cached_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/.conda/envs/chatglm3/lib/python3.11/site-packages/streamlit/runtime/caching/cache_utils.py", line 241, in __call__
    return self._get_or_create_cached_value(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/.conda/envs/chatglm3/lib/python3.11/site-packages/streamlit/runtime/caching/cache_utils.py", line 267, in _get_or_create_cached_value
    return self._handle_cache_miss(cache, value_key, func_args, func_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/.conda/envs/chatglm3/lib/python3.11/site-packages/streamlit/runtime/caching/cache_utils.py", line 321, in _handle_cache_miss
    computed_value = self._info.func(*func_args, **func_kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ChatGLM3-main/composite_demo/client.py", line 41, in get_client
    client = HFClient(MODEL_PATH, TOKENIZER_PATH, PT_PATH, DEVICE)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ChatGLM3-main/composite_demo/client.py", line 149, in __init__
    self.model = AutoModel.from_pretrained(model_path, trust_remote_code=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/.local/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 511, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/.local/lib/python3.11/site-packages/transformers/modeling_utils.py", line 2650, in from_pretrained
    raise EnvironmentError(
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory /home/ChatGLM3-main/finetune_basemodel_demo/output/alpaca-20240124-214811-1e-5/checkpoint-500/.
2024-01-26 10:34:39.524 Session with id b54b1e78-82b0-4b18-8873-28b301f5b315 is already connected! Connecting to a new session.
2024-01-26 10:34:39.578 Uncaught app exception
Traceback (most recent call last):
  File "/home/.conda/envs/chatglm3/lib/python3.11/site-packages/streamlit/runtime/caching/cache_utils.py", line 264, in _get_or_create_cached_value
    cached_result = cache.read_result(value_key)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/.conda/envs/chatglm3/lib/python3.11/site-packages/streamlit/runtime/caching/cache_resource_api.py", line 498, in read_result
    raise CacheKeyNotFoundError()
streamlit.runtime.caching.cache_errors.CacheKeyNotFoundError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/.conda/envs/chatglm3/lib/python3.11/site-packages/streamlit/runtime/caching/cache_utils.py", line 312, in _handle_cache_miss
    cached_result = cache.read_result(value_key)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/.conda/envs/chatglm3/lib/python3.11/site-packages/streamlit/runtime/caching/cache_resource_api.py", line 498, in read_result
    raise CacheKeyNotFoundError()
streamlit.runtime.caching.cache_errors.CacheKeyNotFoundError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/.conda/envs/chatglm3/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "/home/ChatGLM3-main/composite_demo/main.py", line 11, in <module>
    import demo_chat, demo_ci, demo_tool
  File "/home/ChatGLM3-main/composite_demo/demo_chat.py", line 9, in <module>
    client = get_client()
             ^^^^^^^^^^^^
  File "/home/.conda/envs/chatglm3/lib/python3.11/site-packages/streamlit/runtime/caching/cache_utils.py", line 212, in wrapper
    return cached_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/.conda/envs/chatglm3/lib/python3.11/site-packages/streamlit/runtime/caching/cache_utils.py", line 241, in __call__
    return self._get_or_create_cached_value(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/.conda/envs/chatglm3/lib/python3.11/site-packages/streamlit/runtime/caching/cache_utils.py", line 267, in _get_or_create_cached_value
    return self._handle_cache_miss(cache, value_key, func_args, func_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/.conda/envs/chatglm3/lib/python3.11/site-packages/streamlit/runtime/caching/cache_utils.py", line 321, in _handle_cache_miss
    computed_value = self._info.func(*func_args, **func_kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ChatGLM3-main/composite_demo/client.py", line 41, in get_client
    client = HFClient(MODEL_PATH, TOKENIZER_PATH, PT_PATH, DEVICE)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ChatGLM3-main/composite_demo/client.py", line 149, in __init__
    self.model = AutoModel.from_pretrained(model_path, trust_remote_code=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/.local/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 511, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/.local/lib/python3.11/site-packages/transformers/modeling_utils.py", line 2650, in from_pretrained
    raise EnvironmentError(
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory /home/ChatGLM3-main/finetune_basemodel_demo/output/alpaca-20240124-214811-1e-5/checkpoint-500/.
```

### Expected behavior / 期待表现

这是微调出现问题，还是demo没有配置对，应该怎么样才能部署好微调后的base模型呢？
非常希望大佬们解答，感谢！

**Comment by zRzRzRzRzRzRzR** [comment]
老的微调代码是只能在inference.py 部署的，新的微调代码会在这两周尝试上线，可以合并

**Comment by Longleaves** [comment]
好的，谢谢大佬。另外我想问下哪里可以定义微调的epoch呢？我想微调多几轮。

**Comment by zRzRzRzRzRzRzR** [comment]
我们现在用的是max step 不是epoch，具体的差别技术文档有
