### ISSUE TITLE
运行webdemo2的时候出现ModuleNotFoundError: No module named 'transformers_modules.'

### ISSUE THREAD

**Issue by starkgao** [THUDM/ChatGLM3#8]
File "G:\ai\ChatGLM\ChatGLM3\web_demo2.py", line 23, in <module>
    tokenizer, model = get_model()
  File "G:\ai\ChatGLM\ChatGLM3\venv\lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 212, in wrapper
    return cached_func(*args, **kwargs)
  File "G:\ai\ChatGLM\ChatGLM3\venv\lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 241, in __call__
    return self._get_or_create_cached_value(args, kwargs)
  File "G:\ai\ChatGLM\ChatGLM3\venv\lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 267, in _get_or_create_cached_value
    return self._handle_cache_miss(cache, value_key, func_args, func_kwargs)
  File "G:\ai\ChatGLM\ChatGLM3\venv\lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 321, in _handle_cache_miss
    computed_value = self._info.func(*func_args, **func_kwargs)
  File "G:\ai\ChatGLM\ChatGLM3\web_demo2.py", line 14, in get_model
    tokenizer = AutoTokenizer.from_pretrained("./models/chatglm3-6b", trust_remote_code=True)
  File "G:\ai\ChatGLM\ChatGLM3\venv\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 676, in from_pretrained
    tokenizer_class = get_class_from_dynamic_module(class_ref, pretrained_model_name_or_path, **kwargs)
  File "G:\ai\ChatGLM\ChatGLM3\venv\lib\site-packages\transformers\dynamic_module_utils.py", line 443, in get_class_from_dynamic_module
    return get_class_in_module(class_name, final_module.replace(".py", ""))
  File "G:\ai\ChatGLM\ChatGLM3\venv\lib\site-packages\transformers\dynamic_module_utils.py", line 164, in get_class_in_module
    module = importlib.import_module(module_path)
  File "D:\Program Files\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'transformers_modules.'
但实际transformers已经安装也是4.30.2

**Comment by jediwolf** [comment]
升级transformers到最新，问题解决，4.30.2根本不能用

**Comment by jeremysong88** [comment]
@jediwolf 👍  描述正确，我将transformers升级到 transformers==4.34.1 后运行正常

**Comment by WWeellkkiinn** [comment]
@jediwolf 完全正确，使用`pip install --upgrade transformers`更新后完美解决问题

**Comment by changzheng169** [comment]
@WWeellkkiinn 为什么我将transformers升级到最新后还是不能用
Successfully installed huggingface-hub-0.20.1 tokenizers-0.15.0 transformers-4.36.2
(chatglm3) star@star-S8030GM2NE:~/ChatGLM3/basic_demo$ streamlit run web_demo_streamlit.py

2023-12-20 21:45:07.062 Uncaught app exception
Traceback (most recent call last):
  File "/home/star/.local/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "/home/star/ChatGLM3/basic_demo/web_demo_streamlit.py", line 16, in <module>
    from transformers import AutoModel, AutoTokenizer
ModuleNotFoundError: No module named 'transformers'
