### ISSUE TITLE
新的错误。

### ISSUE THREAD

**Issue by homo11451419** [THUDM/ChatGLM3#814]
add .quantized(4) before .eval() to use int4 model

_Originally posted by @zRzRzRzRzRzRzR in https://github.com/THUDM/ChatGLM3/issues/811#issuecomment-1921671349_
            
感谢解答，但是似乎出了新的问题。

代码（前面和后面都省略）：
```python
).quantized(4).eval())
```

D:\glm3\ChatGLM3\composite_demo>streamlit run main.py

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://192.168.0.108:8501

Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 7/7 [00:44<00:00,  6.42s/it]
2024-02-02 13:30:04.378 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\ZhaoYunFeng\AppData\Roaming\Python\Python311\site-packages\streamlit\runtime\caching\cache_utils.py", line 264, in _get_or_create_cached_value
    cached_result = cache.read_result(value_key)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZhaoYunFeng\AppData\Roaming\Python\Python311\site-packages\streamlit\runtime\caching\cache_resource_api.py", line 498, in read_result
    raise CacheKeyNotFoundError()
streamlit.runtime.caching.cache_errors.CacheKeyNotFoundError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ZhaoYunFeng\AppData\Roaming\Python\Python311\site-packages\streamlit\runtime\caching\cache_utils.py", line 312, in _handle_cache_miss
    cached_result = cache.read_result(value_key)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZhaoYunFeng\AppData\Roaming\Python\Python311\site-packages\streamlit\runtime\caching\cache_resource_api.py", line 498, in read_result
    raise CacheKeyNotFoundError()
streamlit.runtime.caching.cache_errors.CacheKeyNotFoundError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ZhaoYunFeng\AppData\Roaming\Python\Python311\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "D:\glm3\ChatGLM3\composite_demo\main.py", line 10, in <module>
    import demo_chat, demo_ci, demo_tool
  File "D:\glm3\ChatGLM3\composite_demo\demo_chat.py", line 7, in <module>
    client = get_client()
             ^^^^^^^^^^^^
  File "C:\Users\ZhaoYunFeng\AppData\Roaming\Python\Python311\site-packages\streamlit\runtime\caching\cache_utils.py", line 212, in wrapper
    return cached_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZhaoYunFeng\AppData\Roaming\Python\Python311\site-packages\streamlit\runtime\caching\cache_utils.py", line 241, in __call__
    return self._get_or_create_cached_value(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZhaoYunFeng\AppData\Roaming\Python\Python311\site-packages\streamlit\runtime\caching\cache_utils.py", line 267, in _get_or_create_cached_value
    return self._handle_cache_miss(cache, value_key, func_args, func_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZhaoYunFeng\AppData\Roaming\Python\Python311\site-packages\streamlit\runtime\caching\cache_utils.py", line 321, in _handle_cache_miss
    computed_value = self._info.func(*func_args, **func_kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\glm3\ChatGLM3\composite_demo\client.py", line 26, in get_client
    client = HFClient(MODEL_PATH, TOKENIZER_PATH, PT_PATH)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\glm3\ChatGLM3\composite_demo\client.py", line 155, in __init__
    ).quantized(4).eval())
      ^^^^^^^^^^^^
TypeError: 'bool' object is not callable

**Comment by zRzRzRzRzRzRzR** [comment]
self.model = AutoModel.from_pretrained(
                model_path,
                trust_remote_code=True,
                config=config,
                device_map="auto"
            ).quantized(4).eval()
