### ISSUE TITLE
bge-large-zh-v1.5 指定本地路径：EMBEDDING_PATH = r"E:\Project\Python\ChatGLM3\bge-large-zh-v1.5"

### ISSUE THREAD

**Issue by 09094080-Tao-Jiao** [THUDM/ChatGLM3#818]
### System Info / 系統信息

    bge-large-zh-v1.5 指定本地路径：EMBEDDING_PATH = r"E:\Project\Python\ChatGLM3\bge-large-zh-v1.5"

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

Traceback (most recent call last):
  File "E:\Project\Python\ChatGLM3\openai_api_demo\api_server.py", line 531, in <module>
embedding_model = SentenceTransformer(EMBEDDING_PATH, device="cuda")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\python3.11\Lib\site-packages\sentence_transformers\SentenceTransformer.py", line 194, in __init__
    modules = self._load_sbert_model(
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\python3.11\Lib\site-packages\sentence_transformers\SentenceTransformer.py", line 1062, in _load_sbert_model
    module_path = load_dir_path(
                  ^^^^^^^^^^^^^^
  File "D:\python\python3.11\Lib\site-packages\sentence_transformers\util.py", line 537, in load_dir_path
    repo_path = snapshot_download(**download_kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\python3.11\Lib\site-packages\huggingface_hub\utils\_validators.py", line 110, in _inner_fn
    validate_repo_id(arg_value)
  File "D:\python\python3.11\Lib\site-packages\huggingface_hub\utils\_validators.py", line 164, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: 'E:\Project\Python\ChatGLM3\bge-large-zh-v1.5'.

### Expected behavior / 期待表现

怎么修改

**Comment by zRzRzRzRzRzRzR** [comment]
这个感觉是你路径没带 \\ 或者你模型文件有 - ，不过我在linux是没遇到这类问题
你可以尝试吧bge-large-zh-v1.5 换成 bge_large_zh_v1.5

**Comment by shirubei** [comment]
同样的问题， 做了如下修改跑通了

def load_model_and_tokenizer(
        model_dir: Union[str, Path], trust_remote_code: bool = True
) -> tuple[ModelType, TokenizerType]:
    #model_dir = _resolve_path(model_dir)
    """
    if (model_dir / 'adapter_config.json').exists():
        model = AutoPeftModelForCausalLM.from_pretrained(
            model_dir, trust_remote_code=trust_remote_code, device_map='auto'
        )
        tokenizer_dir = model.peft_config['default'].base_model_name_or_path
    else:
    """
    model = AutoModelForCausalLM.from_pretrained(
        model_dir, trust_remote_code=trust_remote_code, device_map='auto'
    )
    tokenizer_dir = model_dir
    ...
