### ISSUE TITLE
RuntimeError: CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by treya-lin** [THUDM/ChatGLM3#821]
### System Info / 系統信息

Ubuntu 22.04, torch2.1.0,  cuda11.8, python 3.10, GPU 1*4090

### Who can help? / 谁可以帮助到您？

 @abmfy

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

Docker 环境搭建：
```
sudo docker pull pytorch/pytorch:2.1.0-cuda11.8-cudnn8-devel

# 起一个容器，进入，然后安装环境。起容器命令大致如：
sudo docker run -dit \
  --runtime=nvidia \
  --name=${container} \
  -w ${basedir} \
  -p 8090:8090 \
  -e LC_ALL=C.UTF-8 \
  --mount type=bind,source=${hostdir}/resources,target=${basedir}/resources \
  --mount type=bind,source=${hostdir}/workspace/llm_space,target=${basedir}/workspace/llm_space \
  ${image} \
  /bin/bash

apt-get update && apt-get install tree tmux screen vim git
cd workspace/llm_space/ChatGLM3
python -m pip install -r requirements.txt
```

起chatglm3的demo
```
export MODEL_PATH="my_local_path"
streamlit run composite_demo/main.py --server.address 0.0.0.0 --server.port 8090
```
聊天参数和prompt啥没有改 都是默认的，top_p 0.8, temperature 0.95, rep penalty 1.10 output length 256

我本来以为和discussion这个帖子（https://github.com/THUDM/ChatGLM3/discussions/393）一样，所以之前在那里贴了两个case（https://github.com/THUDM/ChatGLM3/discussions/393#discussioncomment-8366344）。
但是仔细看了发现我的那个RUNTIME ERROR是不一样的。所以在这里发一个新的。如果有重复的可以合并……

控制台里面打出来的traceback
```
2024-02-05 07:50:08.688 Uncaught app exception
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "/home/dev/workspace/llm_space/ChatGLM3/composite_demo/main.py", line 72, in <module>
    demo_chat.main(
  File "/home/dev/workspace/llm_space/ChatGLM3/composite_demo/demo_chat.py", line 62, in main
    for response in client.generate_stream(
  File "/home/dev/workspace/llm_space/ChatGLM3/composite_demo/client.py", line 183, in generate_stream
    for new_text, _ in stream_chat(
  File "/home/dev/workspace/llm_space/ChatGLM3/composite_demo/client.py", line 110, in stream_chat
    for outputs in self.stream_generate(**inputs, past_key_values=past_key_values,
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 56, in generator_context
    response = gen.send(request)
  File "/root/.cache/huggingface/modules/transformers_modules/modeling_chatglm.py", line 1159, in stream_generate
    outputs = self(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/modeling_chatglm.py", line 937, in forward
    transformer_outputs = self.transformer(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/modeling_chatglm.py", line 830, in forward
    hidden_states, presents, all_hidden_states, all_self_attentions = self.encoder(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/modeling_chatglm.py", line 640, in forward
    layer_ret = layer(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/modeling_chatglm.py", line 544, in forward
    attention_output, kv_cache = self.self_attention(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/modeling_chatglm.py", line 415, in forward
    value_layer = torch.cat((cache_v, value_layer), dim=0)
**RuntimeError: CUDA error: an illegal memory access was encountered**
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

```

一次出问题的聊天记录。
```
Q1: 你的知识最新更新到什么时候？
A1: 我的知识库最近一次的更新时间是2022年1月。虽然不能保证每个问题的答案都最准确，但我已经具备了相当程度的知识来回答各种问题。如果您有疑问，欢迎随时向我提问！
Q2: 你知道openai吗
A2: OpenAI是一个总部位于美国的人工智能研究公司，成立于2015年。OpenAI的目标是实现安全的通用人工智能（AGI）并让其有益于人类。OpenAI的研究范围包括人工智能的各个方面，例如机器学习、自然语言处理、计算机视觉等。OpenAI的研究成果和论文经常被业界和学术界引用，并且该公司的技术也受到了广泛的关注和使用。
Q3: 你知道openai最新的产品是什么吗？
A3: 是的，OpenAI 经常发布新的产品和功能。截至我知識截止日期2022年1月，OpenAI 的最新产品包括：

GPT-3：一个基于深度学习的自然语言处理模型，可以生成高质量的自然语言文本。GPT-3是OpenAI 公司的一款重要产品，也是世界上最大的公开可用的自然语言处理模型之一。
GPT-2：一个基于深度学习的自然语言处理模型，比GPT-3小一些，但仍然具有非常强大的语言生成能力。GPT-2可以用于许多不同的应用程序，包括自然语言生成、对话系统、文本摘要等。
Transformer：一种基于自注意力机制的神经网络结构，广泛应用于自然语言处理领域。Transformer 模型的出现极大地提高了深度学习在自然语言处理方面的表现。 *自动机器学习（AutoML）：OpenAI 的自动机器学习平台，使研究人员和开发人员能够快速轻松地构建和训练机器学习模型。AutoML 可以用于许多不同的应用程序，包括图像识别、自然语言处理、推荐系统等。
这只是OpenAI 的部分产品和服务，OpenAI 还有许多其他的产品和服务正在开发中。

Q4: 你知道openai有什么语音方面的产品或服务吗
A4: 是的，OpenAI 提供了一些与语音相关的产品和服务。其中最著名的是其语音合成技术，可以使用 deep text-to-speech （TTS）模型将文本转换为自然语音。这种技术可以应用于许多不同的应用程序，包括虚拟助手、语音翻译、朗读、导航等。

此外，OpenAI 还提供了一个叫做“声音”的 API，可以用于在应用程序中添加背景音乐和其他音频效果。这个 API 可以与 TTS 技术一起使用，创建更加真实和自然的语音交互体验。

除此之外，OpenAI 还在研究和开发其他与语音相关的技术和产品，例如语音识别和语音情感分析等。

Q5:你知道whisper这个模型吗
A5: Whisper 是一个基于人工智能的隐私保护工具，旨在帮助用户保护他们的聊天记录和其他敏感数据。它是由美国卡内基梅隆大学的计算机科学家及其它研究人员开发的。

Whisper 的工作原理是通过使用神经网络加密技术，将用户的原始数据替换为一种难以理解的形式。这样，用户可以在▌

RuntimeError: CUDA error: an illegal memory access was encountered CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1. Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
Traceback:
File "/opt/conda/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
File "/home/dev/workspace/llm_space/ChatGLM3/composite_demo/main.py", line 72, in <module>
    demo_chat.main(
File "/home/dev/workspace/llm_space/ChatGLM3/composite_demo/demo_chat.py", line 62, in main
    for response in client.generate_stream(
File "/home/dev/workspace/llm_space/ChatGLM3/composite_demo/client.py", line 183, in generate_stream
    for new_text, _ in stream_chat(
File "/home/dev/workspace/llm_space/ChatGLM3/composite_demo/client.py", line 110, in stream_chat
    for outputs in self.stream_generate(**inputs, past_key_values=past_key_values,
File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 56, in generator_context
    response = gen.send(request)
File "/root/.cache/huggingface/modules/transformers_modules/modeling_chatglm.py", line 1159, in stream_generate
    outputs = self(
File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
File "/root/.cache/huggingface/modules/transformers_modules/modeling_chatglm.py", line 937, in forward
    transformer_outputs = self.transformer(
File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
File "/root/.cache/huggingface/modules/transformers_modules/modeling_chatglm.py", line 830, in forward
    hidden_states, presents, all_hidden_states, all_self_attentions = self.encoder(
File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
File "/root/.cache/huggingface/modules/transformers_modules/modeling_chatglm.py", line 640, in forward
    layer_ret = layer(
File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
File "/root/.cache/huggingface/modules/transformers_modules/modeling_chatglm.py", line 544, in forward
    attention_output, kv_cache = self.self_attention(
File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
File "/root/.cache/huggingface/modules/transformers_modules/modeling_chatglm.py", line 415, in forward
    value_layer = torch.cat((cache_v, value_layer), dim=0)
```

### Expected behavior / 期待表现

希望可以解决这个问题或者至少找到原因

**Comment by zRzRzRzRzRzRzR** [comment]
是不是还起了其他容器，illegal access 我遇到的唯一一次是爆显存了，这个错误是偶然的还是必定复现，偶然的bug很难修，必定复现给一个复现办法

**Comment by treya-lin** [comment]
> 是不是还起了其他容器，illegal access 我遇到的唯一一次是爆显存了，这个错误是偶然的还是必定复现，偶然的bug很难修，必定复现给一个复现办法

你好，谢谢您的及时回复。我没有起别的容器，只有这一个容器。没有爆显存，我有24G显存，每一轮对话后我查看显存都是12G, 13G左右，增幅很慢，报错后没有爆显存。

复现的话，我虽然没有一个问题是一定可以复现的，但是我已经重启这个demo很多次了，从来没有坚持到超过5轮对话，总是会出现这个错误。。。。

**Comment by treya-lin** [comment]
One update. 我尝试不用docker，在宿主机直接配了同样的环境，依然频繁出现这个错误，无法正常使用 :(

**Comment by zRzRzRzRzRzRzR** [comment]
emm，跑其他模型是正常的吗，因为我的机子上是没办法复现的，或者你有什么魔法提示词能必然复现这个问题

**Comment by treya-lin** [comment]
> emm，跑其他模型是正常的吗，因为我的机子上是没办法复现的，或者你有什么魔法提示词能必然复现这个问题

请问你们本地的测试环境具体是什么样的呢？我看想办法所有版本尽量配置成和你们local环境一样。

**Comment by Nydaym** [comment]
你好我也出现了这个问题。我的情况是使用长文本进行提问的情况会出现这个错误。
出现问题的条件：我使用的是32k的那个模型，输入用例是使用5k的长文本和20k的长文本进行对话摘要提取，在使用的过程中当使用5k的文本的情况下大概能对话五到六次，使用20k的情况能正常对话一次，第二次就直接出现这个问题，因此怀疑是不是对话长度的问题，这个过程我把历史设置为空了，但是仍然会出现显存占用的问题，我的显存大概有80G所以应该不是爆显存的问题，给我的感觉就是虽然历史无法打印出来但是仍然占用我的输入长度，并且这个显存无法释放，导致当我的文本在整个对话的过程中只要超过某个阈值就会出现这个问题。

**Comment by zRzRzRzRzRzRzR** [comment]
> > emm，跑其他模型是正常的吗，因为我的机子上是没办法复现的，或者你有什么魔法提示词能必然复现这个问题
> 
> 请问你们本地的测试环境具体是什么样的呢？我看想办法所有版本尽量配置成和你们local环境一样。

其实只要是linux就行了吧，我用的是单卡 4090 单卡 3090  单卡 A100 都没问题，环境就是requirements.txt

Cuda 12.2 torch 2.2.0 或者 2.1.2
