### ISSUE TITLE
chatglm3 示例代码错误，openai.APIConnectionError: Connection error  文件为openai_api_demo/openai_api_request.py

### ISSUE THREAD

**Issue by 1234-i** [THUDM/ChatGLM3#835]
### System Info / 系統信息

使用的是阿里云的pai平台dsw，可以正常运行basic_demo里面的例子cli_demo.py 可以正常运行，可以正常问答。也可以正常运行web_demo_gradio_py，但是页面的网页显示不太正常。
运行 openai_api_demo/openai_api_request.py报错。连接被拒绝。
拉的都是2024年2月11日的最新代码。

### Who can help? / 谁可以帮助到您？

@zRzRzRzRzRzRzR 

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

cd openai_api_demo

pip install tiktoken
openai_api_demo# pip install typing_extensions==4.8.0
pip install sentence_transformers

python openai_api_request.py
运行openai_api_request.py后报错。

### Expected behavior / 期待表现

按道理应该是正常启动8000端口，但是启动当中就报错了“”。排查了一下8000端口也没有被占用。不知道问题发生在哪里？
完整错误信息如下：Traceback (most recent call last):
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/site-packages/httpcore/_backends/sync.py", line 206, in connect_tcp
    sock = socket.create_connection(
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/site-packages/httpx/_transports/default.py", line 67, in map_httpcore_exceptions
    yield
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/site-packages/httpx/_transports/default.py", line 231, in handle_request
    resp = self._pool.handle_request(req)
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 268, in handle_request
    raise exc
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 251, in handle_request
    response = connection.handle_request(request)
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 124, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/site-packages/httpcore/_backends/sync.py", line 205, in connect_tcp
    with map_exceptions(exc_map):
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/site-packages/openai/_base_client.py", line 918, in _request
    response = self._client.send(
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/site-packages/httpx/_client.py", line 915, in send
    response = self._send_handling_auth(
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/site-packages/httpx/_client.py", line 943, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/site-packages/httpx/_client.py", line 980, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/site-packages/httpx/_client.py", line 1016, in _send_single_request
    response = transport.handle_request(request)
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/site-packages/httpx/_transports/default.py", line 230, in handle_request
    with map_httpcore_exceptions():
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/site-packages/httpx/_transports/default.py", line 84, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/site-packages/httpcore/_backends/sync.py", line 206, in connect_tcp
    sock = socket.create_connection(
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/site-packages/httpx/_transports/default.py", line 67, in map_httpcore_exceptions
    yield
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/site-packages/httpx/_transports/default.py", line 231, in handle_request
    resp = self._pool.handle_request(req)
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 268, in handle_request
    raise exc
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 251, in handle_request
    response = connection.handle_request(request)
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 124, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/site-packages/httpcore/_backends/sync.py", line 205, in connect_tcp
    with map_exceptions(exc_map):
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/site-packages/openai/_base_client.py", line 918, in _request
    response = self._client.send(
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/site-packages/httpx/_client.py", line 915, in send
    response = self._send_handling_auth(
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/site-packages/httpx/_client.py", line 943, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/site-packages/httpx/_client.py", line 980, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/site-packages/httpx/_client.py", line 1016, in _send_single_request
    response = transport.handle_request(request)
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/site-packages/httpx/_transports/default.py", line 230, in handle_request
    with map_httpcore_exceptions():
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/site-packages/httpx/_transports/default.py", line 84, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/site-packages/httpcore/_backends/sync.py", line 206, in connect_tcp
    sock = socket.create_connection(
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/site-packages/httpx/_transports/default.py", line 67, in map_httpcore_exceptions
    yield
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/site-packages/httpx/_transports/default.py", line 231, in handle_request
    resp = self._pool.handle_request(req)
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 268, in handle_request
    raise exc
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 251, in handle_request
    response = connection.handle_request(request)
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 124, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/site-packages/httpcore/_backends/sync.py", line 205, in connect_tcp
    with map_exceptions(exc_map):
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/site-packages/openai/_base_client.py", line 918, in _request
    response = self._client.send(
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/site-packages/httpx/_client.py", line 915, in send
    response = self._send_handling_auth(
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/site-packages/httpx/_client.py", line 943, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/site-packages/httpx/_client.py", line 980, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/site-packages/httpx/_client.py", line 1016, in _send_single_request
    response = transport.handle_request(request)
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/site-packages/httpx/_transports/default.py", line 230, in handle_request
    with map_httpcore_exceptions():
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/site-packages/httpx/_transports/default.py", line 84, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/chatglm3/ChatGLM3/openai_api_demo/openai_api_request.py", line 96, in <module>
    simple_chat(use_stream=False)
  File "/opt/chatglm3/ChatGLM3/openai_api_demo/openai_api_request.py", line 67, in simple_chat
    response = client.chat.completions.create(
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/site-packages/openai/_utils/_utils.py", line 275, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/site-packages/openai/resources/chat/completions.py", line 663, in create
    return self._post(
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/site-packages/openai/_base_client.py", line 1200, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/site-packages/openai/_base_client.py", line 889, in request
    return self._request(
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/site-packages/openai/_base_client.py", line 942, in _request
    return self._retry_request(
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/site-packages/openai/_base_client.py", line 1013, in _retry_request
    return self._request(
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/site-packages/openai/_base_client.py", line 942, in _request
    return self._retry_request(
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/site-packages/openai/_base_client.py", line 1013, in _retry_request
    return self._request(
  File "/opt/conda/envs/chatglm3-6b/lib/python3.10/site-packages/openai/_base_client.py", line 952, in _request
    raise APIConnectionError(request=request) from err
openai.APIConnectionError: Connection error.

**Comment by zRzRzRzRzRzRzR** [comment]
访问被拒绝？你试试本地能跑通么，如果本地能跑通 （localhost）或许是网络问题，至于webui的问题，能给更多细节么

**Comment by 1234-i** [comment]
这个官方的示例脚本,本来就是为了本地启动chatglm 的类openai的api，供外部访问的吧？我现在是在有显卡的服务器上面启动不了这个脚本啊。还没到本地调用哪一步呢。仅仅是启动示例脚本就报上面的拒绝访问错误了。

webUI不正确是另外一个问题了。就是basic_demo里面的例子cli_demo.py 可以这台服务器上面正常运行，也可以正常问答。也可以正常运行web_demo_gradio_py，但是页面的网页显示不太正常。（主要是点击了submit没有任何反映）按道理应该在web端就可以正常问答了。但我的不可以。
![image](https://github.com/THUDM/ChatGLM3/assets/50131577/120e367d-b75b-4f3d-8a8d-00c47d3c92d5)

**Comment by 1234-i** [comment]
![image](https://github.com/THUDM/ChatGLM3/assets/50131577/f211f6b0-51cc-4ec9-a642-a4a0ec3d4a21)
想起来一个问题，web的示例代码应该127.0.0.1:7870端口访问的，但是点击以后会被阿里的云服务器转换成一个域名来访问。我的不知道是不是什么库没装导致的显示不正常？

**Comment by zRzRzRzRzRzRzR** [comment]
这不是本地吗，你没有放到工网吗，127就是本地没有联网
