### ISSUE TITLE
    trainer.train()  代码运行到这里的时候报错

### ISSUE THREAD

**Issue by CmyLjj** [THUDM/ChatGLM3#856]
### System Info / 系統信息

Traceback (most recent call last):
  File "/data1/caomy/chatglm3-demo/finetune_demo/finetune_hf.py", line 528, in <module>
    main("data/AdvertiseGen_fix","/data2/common/pretrain_models/chatglm3-6b","configs/lora.yaml")
  File "/data1/caomy/chatglm3-demo/finetune_demo/finetune_hf.py", line 518, in main
    trainer.train()
  File "/data2/caomy/envs/chatglm3/lib/python3.9/site-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
  File "/data2/caomy/envs/chatglm3/lib/python3.9/site-packages/transformers/trainer.py", line 1869, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/data2/caomy/envs/chatglm3/lib/python3.9/site-packages/transformers/trainer.py", line 2781, in training_step
    self.accelerator.backward(loss)
  File "/data2/caomy/envs/chatglm3/lib/python3.9/site-packages/accelerate/accelerator.py", line 1966, in backward
    loss.backward(**kwargs)
  File "/data2/caomy/envs/chatglm3/lib/python3.9/site-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/data2/caomy/envs/chatglm3/lib/python3.9/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
  0%|                                                  | 0/3000 [00:01<?, ?it/s]

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

    trainer.train()Traceback (most recent call last):
  File "/data1/caomy/chatglm3-demo/finetune_demo/finetune_hf.py", line 528, in <module>
    main("data/AdvertiseGen_fix","/data2/common/pretrain_models/chatglm3-6b","configs/lora.yaml")
  File "/data1/caomy/chatglm3-demo/finetune_demo/finetune_hf.py", line 518, in main
    trainer.train()
  File "/data2/caomy/envs/chatglm3/lib/python3.9/site-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
  File "/data2/caomy/envs/chatglm3/lib/python3.9/site-packages/transformers/trainer.py", line 1869, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/data2/caomy/envs/chatglm3/lib/python3.9/site-packages/transformers/trainer.py", line 2781, in training_step
    self.accelerator.backward(loss)
  File "/data2/caomy/envs/chatglm3/lib/python3.9/site-packages/accelerate/accelerator.py", line 1966, in backward
    loss.backward(**kwargs)
  File "/data2/caomy/envs/chatglm3/lib/python3.9/site-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/data2/caomy/envs/chatglm3/lib/python3.9/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
  0%|                                                  | 0/3000 [00:01<?, ?it/s]

### Expected behavior / 期待表现

Traceback (most recent call last):
  File "/data1/caomy/chatglm3-demo/finetune_demo/finetune_hf.py", line 528, in <module>
    main("data/AdvertiseGen_fix","/data2/common/pretrain_models/chatglm3-6b","configs/lora.yaml")
  File "/data1/caomy/chatglm3-demo/finetune_demo/finetune_hf.py", line 518, in main
    trainer.train()
  File "/data2/caomy/envs/chatglm3/lib/python3.9/site-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
  File "/data2/caomy/envs/chatglm3/lib/python3.9/site-packages/transformers/trainer.py", line 1869, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/data2/caomy/envs/chatglm3/lib/python3.9/site-packages/transformers/trainer.py", line 2781, in training_step
    self.accelerator.backward(loss)
  File "/data2/caomy/envs/chatglm3/lib/python3.9/site-packages/accelerate/accelerator.py", line 1966, in backward
    loss.backward(**kwargs)
  File "/data2/caomy/envs/chatglm3/lib/python3.9/site-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/data2/caomy/envs/chatglm3/lib/python3.9/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
  0%|                                                  | 0/3000 [00:01<?, ?it/s]

**Comment by zRzRzRzRzRzRzR** [comment]
这个是配置和硬件问题吧，正常这个代码不会出现C++引擎问题的，检查你的环境
