### ISSUE TITLE
推断报错

### ISSUE THREAD

**Issue by CmyLjj** [THUDM/ChatGLM3#869]
### System Info / 系統信息

我用p-turning微调的在推断inference_hf.py代码  中  tokenizer = AutoTokenizer.from_pretrained(tokenizer_dir, trust_remote_code=True )这块报错AttributeError: can't set attribute 'eos_token'，我不知道什么原因，

### Who can help? / 谁可以帮助到您？

我用p-turning微调的在推断inference_hf.py代码  中  tokenizer = AutoTokenizer.from_pretrained(tokenizer_dir, trust_remote_code=True )这块报错AttributeError: can't set attribute 'eos_token'，我不知道什么原因，

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

ssh://zut@101.43.58.238:6000/mnt/6t/zut/anaconda3/envs/chatglm3-demo/bin/python -u /tmp/chatglm3-demo/finetune_demo/inference_hf.py
Loading checkpoint shards: 100%|██████████████████| 3/3 [00:02<00:00,  1.21it/s]
Traceback (most recent call last):
  File "/tmp/chatglm3-demo/finetune_demo/inference_hf.py", line 58, in <module>
    main("/tmp/chatglm3-demo/finetune_demo/output/checkpoint-300","类型#裤*材质#羊毛*裤长#九分裤*裤口#微喇裤")
  File "/tmp/chatglm3-demo/finetune_demo/inference_hf.py", line 50, in main
    model, tokenizer = load_model_and_tokenizer(model_dir)
  File "/tmp/chatglm3-demo/finetune_demo/inference_hf.py", line 39, in load_model_and_tokenizer
    tokenizer = AutoTokenizer.from_pretrained(
  File "/mnt/6t/zut/anaconda3/envs/chatglm3-demo/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 810, in from_pretrained
    return tokenizer_class.from_pretrained(
  File "/mnt/6t/zut/anaconda3/envs/chatglm3-demo/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2048, in from_pretrained
    return cls._from_pretrained(
  File "/mnt/6t/zut/anaconda3/envs/chatglm3-demo/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2287, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/home/zut/.cache/huggingface/modules/transformers_modules/checkpoint-300/tokenization_chatglm.py", line 93, in __init__
    super().__init__(padding_side=padding_side, clean_up_tokenization_spaces=clean_up_tokenization_spaces, **kwargs)
  File "/mnt/6t/zut/anaconda3/envs/chatglm3-demo/lib/python3.10/site-packages/transformers/tokenization_utils.py", line 363, in __init__
    super().__init__(**kwargs)
  File "/mnt/6t/zut/anaconda3/envs/chatglm3-demo/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1603, in __init__
    super().__init__(**kwargs)
  File "/mnt/6t/zut/anaconda3/envs/chatglm3-demo/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 861, in __init__
    setattr(self, key, value)
AttributeError: can't set attribute 'eos_token'

Process finished with exit code 1

### Expected behavior / 期待表现

ssh://zut@101.43.58.238:6000/mnt/6t/zut/anaconda3/envs/chatglm3-demo/bin/python -u /tmp/chatglm3-demo/finetune_demo/inference_hf.py
Loading checkpoint shards: 100%|██████████████████| 3/3 [00:02<00:00,  1.21it/s]
Traceback (most recent call last):
  File "/tmp/chatglm3-demo/finetune_demo/inference_hf.py", line 58, in <module>
    main("/tmp/chatglm3-demo/finetune_demo/output/checkpoint-300","类型#裤*材质#羊毛*裤长#九分裤*裤口#微喇裤")
  File "/tmp/chatglm3-demo/finetune_demo/inference_hf.py", line 50, in main
    model, tokenizer = load_model_and_tokenizer(model_dir)
  File "/tmp/chatglm3-demo/finetune_demo/inference_hf.py", line 39, in load_model_and_tokenizer
    tokenizer = AutoTokenizer.from_pretrained(
  File "/mnt/6t/zut/anaconda3/envs/chatglm3-demo/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 810, in from_pretrained
    return tokenizer_class.from_pretrained(
  File "/mnt/6t/zut/anaconda3/envs/chatglm3-demo/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2048, in from_pretrained
    return cls._from_pretrained(
  File "/mnt/6t/zut/anaconda3/envs/chatglm3-demo/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2287, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/home/zut/.cache/huggingface/modules/transformers_modules/checkpoint-300/tokenization_chatglm.py", line 93, in __init__
    super().__init__(padding_side=padding_side, clean_up_tokenization_spaces=clean_up_tokenization_spaces, **kwargs)
  File "/mnt/6t/zut/anaconda3/envs/chatglm3-demo/lib/python3.10/site-packages/transformers/tokenization_utils.py", line 363, in __init__
    super().__init__(**kwargs)
  File "/mnt/6t/zut/anaconda3/envs/chatglm3-demo/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1603, in __init__
    super().__init__(**kwargs)
  File "/mnt/6t/zut/anaconda3/envs/chatglm3-demo/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 861, in __init__
    setattr(self, key, value)
AttributeError: can't set attribute 'eos_token'

Process finished with exit code 1

**Comment by zRzRzRzRzRzRzR** [comment]
更新hf代码和本仓库代码到0223版本

**Comment by CmyLjj** [comment]
请问这个0223版本是最新版本吗

**Comment by zRzRzRzRzRzRzR** [comment]
是，模型文件没变，只是配置文件变了
