### ISSUE TITLE
modeling_chatglm.py中process_response函数报错

### ISSUE THREAD

**Issue by jkl375** [THUDM/ChatGLM3#897]
### System Info / 系統信息

transformers==4.38.1

### Who can help? / 谁可以帮助到您？

@yincf

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1. 使用32K的chatglm3模型，demo代码：
```
from transformers import AutoTokenizer, AutoModel
import time
tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm3-6b-32k", trust_remote_code=True)
model = AutoModel.from_pretrained("THUDM/chatglm3-6b-32k", trust_remote_code=True).half().cuda()
model = model.eval()
s = time.time()
response, history = model.chat(tokenizer, "你好"*10000, history=[], max_new_tokens=10)
print(time.time()-s)
print(response)
```
3. 执行代码 `python demo.py`
4. 发现modeling_chatglm.py中process_response函数报错
```
Loading checkpoint shards:   0%|                                                                  | 0/7 [00:00<?, ?it/s]/usr/local/lib/python3.10/dist-packages/torch/_utils.py:836: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████| 7/7 [00:01<00:00,  4.23it/s]
inputs length 10007
Both `max_new_tokens` (=10) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
11111111 好听吗
Traceback (most recent call last):
  File "/app/demo_chatglm.py", line 7, in <module>
    response, history = model.chat(tokenizer, "你好"*10000, history=[], max_new_tokens=10)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm3-6b-32k/modeling_chatglm.py", line 1044, in chat
    response, history = self.process_response(response, history)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm3-6b-32k/modeling_chatglm.py", line 1007, in process_response
    metadata, content = response.split("\n", maxsplit=1)
ValueError: not enough values to unpack (expected 2, got 1)
```
![image](https://github.com/THUDM/ChatGLM3/assets/54523287/41d3fa81-754b-4d76-9742-a80b94fb7e8c)
是因为response字符没有\n

### Expected behavior / 期待表现

执行成功，不会报错

**Comment by jkl375** [comment]
建议改为
```
  resp = response.split("\n", maxsplit=1)
  if len(resp) == 1:
      metadata = ""
      content = resp[0]
  else:
      metadata, content = resp
```

**Comment by zRzRzRzRzRzRzR** [comment]
batch推理不是这么推理的。请看batch 推理的 demo

**Comment by xiayouran** [comment]
同样的问题 @zRzRzRzRzRzRzR @jkl375

**Comment by FanZhang91** [comment]
> batch推理不是这么推理的。请看batch 推理的 demo

@zRzRzRzRzRzRzR 能具体描述一点吗? 用inference_hf推理也报这个错？

**Comment by jkl375** [comment]
> batch推理不是这么推理的。请看batch 推理的 demo
跟batch没关系，你看我的是单句话的推理
