### ISSUE TITLE
lora方式微调后，启动微调模型报错Please pass the argument `trust_remote_code=True` to allow custom code to be run.

### ISSUE THREAD

**Issue by Andy1018** [THUDM/ChatGLM3#904]
### System Info / 系統信息

CentOS Linux release 7.9.2009 (Core)
CUDA Version: 12.1
Python 3.11.8

### Who can help? / 谁可以帮助到您？

@bt

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/anaconda3/envs/chatglm3_test/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "/home/chatglm3/chatglm3_6b/basic_demo/web_demo_streamlit.py", line 69, in <module>
    model, tokenizer = load_model_and_tokenizer('../finetune_demo/output_lora/checkpoint-3000/')
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/chatglm3_test/lib/python3.11/site-packages/streamlit/runtime/caching/cache_utils.py", line 212, in wrapper
    return cached_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/chatglm3_test/lib/python3.11/site-packages/streamlit/runtime/caching/cache_utils.py", line 241, in __call__
    return self._get_or_create_cached_value(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/chatglm3_test/lib/python3.11/site-packages/streamlit/runtime/caching/cache_utils.py", line 268, in _get_or_create_cached_value
    return self._handle_cache_miss(cache, value_key, func_args, func_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/chatglm3_test/lib/python3.11/site-packages/streamlit/runtime/caching/cache_utils.py", line 324, in _handle_cache_miss
    computed_value = self._info.func(*func_args, **func_kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chatglm3/chatglm3_6b/basic_demo/web_demo_streamlit.py", line 46, in load_model_and_tokenizer
    model = AutoPeftModelForCausalLM.from_pretrained(model_dir, trust_remote_code=True, device_map='auto').eval()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/chatglm3_test/lib/python3.11/site-packages/peft/auto.py", line 124, in from_pretrained
    tokenizer = AutoTokenizer.from_pretrained(pretrained_model_name_or_path)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/chatglm3_test/lib/python3.11/site-packages/transformers/models/auto/tokenization_auto.py", line 797, in from_pretrained
    trust_remote_code = resolve_trust_remote_code(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/chatglm3_test/lib/python3.11/site-packages/transformers/dynamic_module_utils.py", line 611, in resolve_trust_remote_code
    raise ValueError(
ValueError: The repository for /home/chatglm3/chatglm3_6b/finetune_demo/output_lora/checkpoint-3000 contains custom code which must be executed to correctly load the model. You can inspect the repository content at https://hf.co//home/chatglm3/chatglm3_6b/finetune_demo/output_lora/checkpoint-3000.
Please pass the argument `trust_remote_code=True` to allow custom code to be run.

### Expected behavior / 期待表现

微调后的模型可以正常启动
def load_model_and_tokenizer(model_dir: Union[str, Path]) -> tuple[ModelType, TokenizerType]:
    model_dir = _resolve_path(model_dir)
    if (model_dir / 'adapter_config.json').exists():
        print(model_dir)
        model = AutoPeftModelForCausalLM.from_pretrained(model_dir, trust_remote_code=True, device_map='auto').eval()
        print(2222)
        tokenizer_dir = model.peft_config['default'].base_model_name_or_path
        print(tokenizer_dir)
    else:
        model = AutoModelForCausalLM.from_pretrained(
            model_dir, trust_remote_code=True, device_map='auto'
        )
        tokenizer_dir = model_dir
    tokenizer = AutoTokenizer.from_pretrained(
        tokenizer_dir, trust_remote_code=True
    )
    return model, tokenizer

**Comment by zRzRzRzRzRzRzR** [comment]
检查一下你的transfomers和peft版本

**Comment by Andy1018** [comment]
Name: peft
Version: 0.8.2


Name: transformers
Version: 4.38.1@

**Comment by Andy1018** [comment]
Name: peft
Version: 0.8.2


Name: transformers
Version: 4.38.1

**Comment by zRzRzRzRzRzRzR** [comment]
降到0.7.1，微调的版本也需要是0.7.1
