### ISSUE TITLE
依赖库错误

### ISSUE THREAD

**Issue by winer3086** [THUDM/ChatGLM3#943]
### System Info / 系統信息

主要软件版本信息如下：
(chatglm3) PS E:\ChatGLM3-main\basic_demo> python --version
Python 3.10.0

(chatglm3) PS E:\ChatGLM3-main\basic_demo> nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:41:10_Pacific_Daylight_Time_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0

(chatglm3) PS E:\ChatGLM3-main\basic_demo> conda list transformers
# packages in environment at D:\Anaconda\envs\chatglm3:
#
# Name                    Version                   Build  Channel
sentence-transformers     2.5.1                    pypi_0    pypi
transformers              4.38.2                   pypi_0    pypi

### Who can help? / 谁可以帮助到您？

**在相关依赖完成以及完成web_demo_gradio.py相关本地目录修改之后，我试图运行demo**
(chatglm3) PS E:\ChatGLM3-main\basic_demo> python E:\ChatGLM3-main\basic_demo\web_demo_gradio.py

Traceback (most recent call last):
  File "E:\ChatGLM3-main\basic_demo\web_demo_gradio.py", line 69, in <module>
    model, tokenizer = load_model_and_tokenizer(MODEL_PATH, trust_remote_code=True)
  File "E:\ChatGLM3-main\basic_demo\web_demo_gradio.py", line 59, in load_model_and_tokenizer
    model = AutoModelForCausalLM.from_pretrained(
  File "D:\Anaconda\envs\chatglm3\lib\site-packages\transformers\models\auto\auto_factory.py", line 521, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "D:\Anaconda\envs\chatglm3\lib\site-packages\transformers\models\auto\configuration_auto.py", line 1120, in from_pretrained
    config_class = get_class_from_dynamic_module(
  File "D:\Anaconda\envs\chatglm3\lib\site-packages\transformers\dynamic_module_utils.py", line 500, in get_class_from_dynamic_module
    return get_class_in_module(class_name, final_module.replace(".py", ""))
  File "D:\Anaconda\envs\chatglm3\lib\site-packages\transformers\dynamic_module_utils.py", line 200, in get_class_in_module
    module = importlib.import_module(module_path)
  File "D:\Anaconda\envs\chatglm3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'transformers_modules.chatglm3-6b'

**我又使用pip来安装，结果报错如下：**
(chatglm3) PS E:\ChatGLM3-main\basic_demo> pip install transformers_modules.chatglm3-6b
ERROR: Could not find a version that satisfies the requirement transformers_modules.chatglm3-6b (from versions: none)
ERROR: No matching distribution found for transformers_modules.chatglm3-6b

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

每次都出现

### Expected behavior / 期待表现

我希望在执行运行实例脚本过程中能够正常运行

**Comment by winer3086** [comment]
web_demo_gradio.py我根据本地文件位置，修改如下：

MODEL_PATH = os.environ.get('E:\\models\\chatglm3-6b', 'E:\\models\\chatglm3-6b')
TOKENIZER_PATH = os.environ.get("E:\\models\\chatglm3-6b",'E:\\models\\chatglm3-6b')

demo.launch(server_name="127.0.0.1", server_port=7870, inbrowser=True, share=True)
