### ISSUE TITLE
chatglm3进行ppo训练时出错，提示没有language model head，另外用一个有model head的

### ISSUE THREAD

**Issue by cove1011** [THUDM/ChatGLM3#963]
### System Info / 系統信息

都是正常的

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

Traceback (most recent call last):
  File "F:\xiazai\MedicalGPT-main\ppo_training.py", line 516, in <module>
    main()
  File "F:\xiazai\MedicalGPT-main\ppo_training.py", line 270, in main
    model = AutoModelForCausalLMWithValueHead.from_pretrained(
  File "C:\Users\admin\.conda\envs\newrlhf\lib\site-packages\trl\models\modeling_base.py", line 276, in from_pretrained
    model = cls(pretrained_model, **multi_adapter_args, **trl_model_args)
  File "C:\Users\admin\.conda\envs\newrlhf\lib\site-packages\trl\models\modeling_value_head.py", line 112, in __init__
    raise ValueError("The model does not have a language model head, please use a model that has one.")
ValueError: The model does not have a language model head, please use a model that has one.

### Expected behavior / 期待表现

希望能解决这个没有language model head的问题

**Comment by zRzRzRzRzRzRzR** [comment]
本仓库 没有设计 PPO 训练，可以到 #253 处理
