### ISSUE TITLE
基础Demo cli_demo.py，单机双卡报错RuntimeError: Expected all tensors to be on the same device, but found at least two devices

### ISSUE THREAD

**Issue by KeshawnHou** [THUDM/ChatGLM3#968]
### System Info / 系統信息

python==3.11

transformers==4.36.2

torch==2.2.1+cu118

Ubuntu: 22.04.1

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

按照官方文档部署chatglm3-6b-128k后，运行基础demo: python cli_demo.py（最新版本），报错：RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument tensors in method wrapper_CUDA_cat)

### Expected behavior / 期待表现

支持单机多卡部署

**Comment by zRzRzRzRzRzRzR** [comment]
两张卡一样么

**Comment by zRzRzRzRzRzRzR** [comment]
根本无法启动还是运行一会出现的

**Comment by KeshawnHou** [comment]
> 根本无法启动还是运行一会出现的

在nvidia-smi能看到模型参数被加载到双卡中。命令行交互时，输入“你好“，就报上面错误。完整报错如下：

Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████| 7/7 [00:04<00:00,  1.61it/s]
欢迎使用 ChatGLM3-6B 模型，输入内容即可进行对话，clear 清空对话历史，stop 终止程序

用户：你好

ChatGLM：Traceback (most recent call last):
  File "/home/usr0/Desktop/Project0/LLM/ChatGLM3/ChatGLM3/basic_demo/cli_demo.py", line 54, in <module>
    main()
  File "/home/usr0/Desktop/Project0/LLM/ChatGLM3/ChatGLM3/basic_demo/cli_demo.py", line 40, in main
    for response, history, past_key_values in model.stream_chat(tokenizer, query, history=history, top_p=1,
  File "/home/usr0/anaconda3/envs/ChatGLM3/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
               ^^^^^^^^^^^^^^
  File "/home/usr0/.cache/huggingface/modules/transformers_modules/THUDM-chatglm3-6b-128k_20240312/modeling_chatglm.py", line 1099, in stream_chat
    for outputs in self.stream_generate(**inputs, past_key_values=past_key_values,
  File "/home/usr0/anaconda3/envs/ChatGLM3/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
               ^^^^^^^^^^^^^^
  File "/home/usr0/.cache/huggingface/modules/transformers_modules/THUDM-chatglm3-6b-128k_20240312/modeling_chatglm.py", line 1186, in stream_generate
    outputs = self(
              ^^^^^
  File "/home/usr0/anaconda3/envs/ChatGLM3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usr0/anaconda3/envs/ChatGLM3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usr0/anaconda3/envs/ChatGLM3/lib/python3.11/site-packages/accelerate/hooks.py", line 166, in new_forward
    output = module._old_forward(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usr0/.cache/huggingface/modules/transformers_modules/THUDM-chatglm3-6b-128k_20240312/modeling_chatglm.py", line 964, in forward
    transformer_outputs = self.transformer(
                          ^^^^^^^^^^^^^^^^^
  File "/home/usr0/anaconda3/envs/ChatGLM3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usr0/anaconda3/envs/ChatGLM3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usr0/.cache/huggingface/modules/transformers_modules/THUDM-chatglm3-6b-128k_20240312/modeling_chatglm.py", line 851, in forward
    hidden_states, presents, all_hidden_states, all_self_attentions = self.encoder(
                                                                      ^^^^^^^^^^^^^
  File "/home/usr0/anaconda3/envs/ChatGLM3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usr0/anaconda3/envs/ChatGLM3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usr0/.cache/huggingface/modules/transformers_modules/THUDM-chatglm3-6b-128k_20240312/modeling_chatglm.py", line 670, in forward
    presents = torch.cat((presents, kv_cache), dim=0)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument tensors in method wrapper_CUDA_cat)

**Comment by hanhan0521** [comment]
当我使用128K模型多卡部署时，我也遇到了这个问题
![image](https://github.com/THUDM/ChatGLM3/assets/95208134/7622aebf-997a-433d-a620-1ce300cb27fd)

**Comment by zRzRzRzRzRzRzR** [comment]
我刚才使用双卡设备，没有遇到相似问题，6b 正常模型能用吗

**Comment by KeshawnHou** [comment]
> 我刚才使用双卡设备，没有遇到相似问题，6b 正常模型能用吗

之前测试ChatGLM3-6B-32K的cli_demo.py没问题，128K不行。我根据报错修改了一下128K的代码，改后的代码这个bug没有了，在Hugging Face的128K模型下提交了一个PR，你们可以参考一下，看看还有没有类似的问题。

**Comment by zRzRzRzRzRzRzR** [comment]
这个问题很有可能是温度设定太低了
不知道是不是温度设置到0
https://github.com/p208p2002/FastChat/commit/264a7ff22963f8161fda2027dc0118596f3f956c 有提到

**Comment by KeshawnHou** [comment]
> 这个问题很有可能是温度设定太低了 不知道是不是温度设置到0 [p208p2002/FastChat@264a7ff](https://github.com/p208p2002/FastChat/commit/264a7ff22963f8161fda2027dc0118596f3f956c) 有提到

当时参数没有改，就是用`cli_demo.py`里的默认参数测试了一下，刚看了一下`temperature=0.01`。128k的`modeling_chatglm.py`里面第670行：`presents = torch.cat((presents, kv_cache), dim=0)`。这个在多卡运算的时候，两个tensor可能会不在同一个GPU上引发报错。

**Comment by luffyyqh** [comment]
同样遇到了这个问题，128k模型会报一样的错，换成基础模型不报错了，但是输出乱码
![2024-03-29 16-52-16屏幕截图](https://github.com/THUDM/ChatGLM3/assets/35060163/beaa87b3-7527-43ad-ad31-a5aee6eaa20d)
显卡是两张A5000（24G），用device_map指定只在一张卡上就没有问题

**Comment by luffyyqh** [comment]
同样遇到了这个问题，128k模型会报一样的错，换成基础模型不报错了，但是输出乱码
![2024-03-29 16-52-16屏幕截图](https://github.com/THUDM/ChatGLM3/assets/35060163/beaa87b3-7527-43ad-ad31-a5aee6eaa20d)
显卡是两张A5000（24G），用device_map指定只在一张卡上就没有问题

**Comment by 0sengseng0** [comment]
> > 我刚才使用双卡设备，没有遇到相似问题，6b 正常模型能用吗
> 
> 之前测试ChatGLM3-6B-32K的cli_demo.py没问题，128K不行。我根据报错修改了一下128K的代码，改后的代码这个bug没有了，在Hugging Face的128K模型下提交了一个PR，你们可以参考一下，看看还有没有类似的问题。

伟人!
